### ISSUE TITLE
simple srun commands fail on new cluster

### ISSUE THREAD

**Issue by notestaff** [aws/aws-parallelcluster#1122]
**Environment:**
 - AWS ParallelCluster / CfnCluster version [aws-parallelcluster-2.3.1]
 - OS: [os7]
 - Scheduler: [slurm]
 - Master instance type: [c5n.2xlarge]
 - Compute instance type: [m5.12xlarge]

**Bug description and how to reproduce:**
[centos@ip-172-31-95-2 ~]$ sinfo
PARTITION AVAIL  TIMELIMIT  NODES  STATE NODELIST
compute*     up   infinite      1   idle ip-172-31-81-213
[centos@ip-172-31-95-2 ~]$ srun ls -l
srun: error: Task launch for 5.0 failed on node ip-172-31-81-213: Communication connection failure
srun: error: Application launch failed: Communication connection failure
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
srun: error: Timed out waiting for job step to complete
[centos@ip-172-31-95-2 ~]$ srun ls -l
srun: Required node not available (down, drained or reserved)
srun: job 6 queued and waiting for resources
srun: job 6 has been allocated resources
srun: error: fwd_tree_thread: can't find address for host ip-172-31-94-221, check slurm.conf
srun: error: Task launch for 6.0 failed on node ip-172-31-94-221: Can't find an address, check slurm.conf
srun: error: Application launch failed: Can't find an address, check slurm.conf
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
srun: error: Timed out waiting for job step to complete
[

**Additional context:**
Any other context about the problem. E.g.:

I was just trying out the cluster, and these errors started cropping up.

**Comment by lukeseawalker** [comment]
looking into, but I wasn't able to reproduce.
Can you please post:
 - configuration file without any credentials or personal data.
 - `/var/log/nodewatcher` from the Compute node and `/var/log/jobwatcher` and `/var/log/sqswatcher` from the Master node

**Comment by jonathonl** [comment]
I found this error in /var/log/jobwatcher. It appears your list of instance types is not up to date.

```
2019-10-16 22:13:59,288 CRITICAL [utils:_get_vcpus_by_instance_type] Unable to get vcpus from instances file. Instance type r5n.xlarge not found.
2019-10-16 22:13:59,288 ERROR [jobwatcher:main] An unexpected error occurred: Unable to get vcpus from instances file. Instance type r5n.xlarge not found.
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.9/envs/node_virtualenv/lib/python3.6/site-packages/common/utils.py", line 298, in _get_vcpus_by_instance_type
    vcpus = int(instances[instance_type]["vcpus"])
KeyError: 'r5n.xlarge'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.9/envs/node_virtualenv/lib/python3.6/site-packages/jobwatcher/jobwatcher.py", line 147, in main
    _poll_scheduler_status(config, asg_name, scheduler_module)
  File "/root/.pyenv/versions/3.6.9/envs/node_virtualenv/lib/python3.6/site-packages/jobwatcher/jobwatcher.py", line 93, in _poll_scheduler_status
    instance_properties = get_instance_properties(config.region, config.proxy_config, instance_type)
  File "/root/.pyenv/versions/3.6.9/envs/node_virtualenv/lib/python3.6/site-packages/common/utils.py", line 231, in get_instance_properties
    vcpus = _get_vcpus_from_pricing_file(region, proxy_config, instance_type)
  File "/root/.pyenv/versions/3.6.9/envs/node_virtualenv/lib/python3.6/site-packages/common/utils.py", line 221, in _get_vcpus_from_pricing_file
    return _get_vcpus_by_instance_type(instances, instance_type)
  File "/root/.pyenv/versions/3.6.9/envs/node_virtualenv/lib/python3.6/site-packages/common/utils.py", line 304, in _get_vcpus_by_instance_type
    raise CriticalError(error_msg)
common.utils.CriticalError: Unable to get vcpus from instances file. Instance type r5n.xlarge not found.
```

**Comment by demartinofra** [comment]
Hi @jonathonl 

The error you reported is related to https://github.com/aws/aws-parallelcluster/issues/1364 and most likely not to the current issue. Please refer to that for updates and thanks for reporting this.
