### ISSUE TITLE
Error: Did not have IAM permissions to process tags on AWS::DynamoDB::Table resource.

### ISSUE THREAD

**Issue by adavanisanti** [aws/aws-parallelcluster#1282]
**Environment:**
 - AWS ParallelCluster version 2.2.1
 - OS: ubuntu
 - Scheduler: Slurm
 - Master instance type: c5.xlarge
 - Compute instance type: c5.xlarge

**Bug description and how to reproduce:**
We kicked off a `pcluster create` using a custom AMI. Cluster creation failed with the following error 

`Did not have IAM permissions to process tags on AWS::DynamoDB::Table resource.`
`The user does not have IAM permissions to process tags on AWS::SQS::Queue resource.`

**Additional context:**
Any other context about the problem. E.g.:
- aws-parallelcluster==2.2.1 did not require `"dynamodb:TagResource"` and `"sqs:TagQueue"` permissions for ParallelClusterUserPolicy before.
- Has this requirement changed?

Could you help with troubleshooting this?

Thanks
Santi

**Comment by enrico-usai** [comment]
Hi @adavanisanti 
the messages you reported should just be "warnings", they should not cause the cluster failure.
The resources are created without the tags and the cluster creation should finish correctly.

These policies are used to let CloudFormation propagate the tags to the created resources 
and they have been already added to [ParallelCluster official documentation](https://docs.aws.amazon.com/parallelcluster/latest/ug/iam.html).

You can double check what is the first Event causing the cluster creation failure in the CloudFormation console, or by passing the `--norollback` flag to the `create` command.

Let us know if it helps.
Enrico

**Comment by enrico-usai** [comment]
Hi @adavanisanti 
the message you reported means that some compute nodes cannot be created 
probably due to some errors in the custom_ami initialization or post install script execution.

We need more context:
 - configuration file without any credentials or personal data.
 - pre/post-install scripts, if any.

The custom_ami is used for both Master and Compute nodes, so if also the Master creation fails, you could create the cluster with `initial_queue_size = 0` , to avoid the creation of the Compute nodes during the test.

In any case, if the cluster creation fails, you can re-execute `create` action using `--norollback` option and check the `/var/log/cfn-init.log`, `/var/log/cloud-init.log` and `/var/log/cloud-init-output.log` files from the Master node.

Enrico

**Comment by enrico-usai** [comment]
@adavanisanti 
 in the _cfn-init.log_ you can search for "fail" or "error" you should found the reason of the failure at the end of the file.

**Comment by adavanisanti** [comment]
@enrico-usai are there any logs from compute nodes written on master node?

**Comment by enrico-usai** [comment]
@adavanisanti starting from ParallelCluster 2.4.0 you can find the compute nodes logs in the `/home/logs/compute`, for previous version you can follow [this guide](https://github.com/aws/aws-parallelcluster/wiki/CloudWatch-Logs) to save the logs in CloudWatch.

I'd suggest to use the latest version (2.4.1).

**Comment by adavanisanti** [comment]
Hi @enrico-usai error we see is below:

```
Running handlers:
[2019-08-29T15:40:11+00:00] ERROR: Running exception handlers
[2019-08-29T15:40:11+00:00] ERROR: Running exception handlers
Running handlers complete
[2019-08-29T15:40:11+00:00] ERROR: Exception handlers complete
[2019-08-29T15:40:11+00:00] ERROR: Exception handlers complete
Chef Client failed. 24 resources updated in 16 seconds
[2019-08-29T15:40:11+00:00] FATAL: Stacktrace dumped to /etc/chef/local-mode-cache/cache/chef-stacktrace.out
[2019-08-29T15:40:11+00:00] FATAL: Stacktrace dumped to /etc/chef/local-mode-cache/cache/chef-stacktrace.out
[2019-08-29T15:40:11+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2019-08-29T15:40:11+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2019-08-29T15:40:11+00:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: mount[/home] (aws-parallelcluster::_compute_base_config line 57) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '32'
---- Begin output of mount -t nfs -o hard,intr,noatime,vers=3,_netdev ip-10-x-x-x.us-west-2.compute.internal:/home /home ----
STDOUT: 
STDERR: mount.nfs: Failed to resolve server ip-10-x-x-x.us-west-2.compute.internal: Name or service not known
---- End output of mount -t nfs -o hard,intr,noatime,vers=3,_netdev ip-10-x-x-x.us-west-2.compute.internal:/home /home ----
Ran mount -t nfs -o hard,intr,noatime,vers=3,_netdev ip-10-x-x-x.us-west-2.compute.internal:/home /home returned 32
[2019-08-29T15:40:11+00:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: mount[/home] (aws-parallelcluster::_compute_base_config line 57) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '32'
---- Begin output of mount -t nfs -o hard,intr,noatime,vers=3,_netdev ip-10-x-x-x.us-west-2.compute.internal:/home /home ----
STDOUT: 
STDERR: mount.nfs: Failed to resolve server ip-10-x-x-x.us-west-2.compute.internal: Name or service not known
---- End output of mount -t nfs -o hard,intr,noatime,vers=3,_netdev ip-10-x-x-x.us-west-2.compute.internal:/home /home ----
Ran mount -t nfs -o hard,intr,noatime,vers=3,_netdev ip-10-x-x-x.us-west-2.compute.internal:/home /home returned 32

2019-08-29 15:40:11,158 [ERROR] Error encountered during build of chefConfig: Command chef failed
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 542, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 260, in build
    changes['commands'] = CommandTool().apply(self._config.commands)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/command_tool.py", line 117, in apply
    raise ToolError(u"Command %s failed" % name)
ToolError: Command chef failed
2019-08-29 15:40:11,159 [ERROR] -----------------------BUILD FAILED!------------------------
2019-08-29 15:40:11,159 [ERROR] Unhandled exception during build: Command chef failed
Traceback (most recent call last):
  File "/usr/local/bin/cfn-init", line 171, in <module>
    worklog.build(metadata, configSets)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 129, in build
    Contractor(metadata).build(configSets, self)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 530, in build
    self.run_config(config, worklog)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 542, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 260, in build
    changes['commands'] = CommandTool().apply(self._config.commands)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/command_tool.py", line 117, in apply
    raise ToolError(u"Command %s failed" % name)
ToolError: Command chef failed
2019-08-29 15:40:11,298 [DEBUG] CloudFormation client initialized with endpoint https://cloudformation.us-west-2.amazonaws.com
2019-08-29 15:40:11,298 [DEBUG] Signaling resource ComputeFleet in stack parallelcluster-prod-default-cluster-5pd7mcnhl3 with unique ID i-0e1cef38fd647c3de and status FAILURE
```
Seems like there is something to do with DNS resolver. Could you suggest how to fix this?

Thanks
Santi

**Comment by adavanisanti** [comment]
@enrico-usai Would it be possible to use IP addresses directly rather than DNS for the NFS mount?

**Comment by adavanisanti** [comment]
@enrico-usai if I pass the below JSON to extra_json configuration parameter according to would it make parallel cluster use PrivateIP instead of PrivateDnsName?

```
{
 "cfn_master": {
                      "Fn::GetAtt": [
                        "MasterServer",
                        "PrivateIp"
                      ]
                   }
}
```

Thanks
Santi

**Comment by enrico-usai** [comment]
Hi @adavanisanti 

Could you please double check the VPC configuration parameters?
As you can read in ParallelCluster [doc](https://docs.aws.amazon.com/parallelcluster/latest/ug/getting-started-configuring-parallelcluster.html), the VPC must have DNS Resolution = yes and DNS Hostnames = yes.

**Comment by enrico-usai** [comment]
About the `cfn_master` question: the _cfn_master_ parameter is used to mount the file system but also for the scheduler configuration.

We already tried to use PrivateIp in place of PrivateDnsName and nfs mount works correctly but schedulers don't. See: https://github.com/aws/aws-parallelcluster/issues/1201#issuecomment-513205107

**Comment by adavanisanti** [comment]
Is there a workaround for schedulers that I can try? 

At this time, I have switched to version 2.4.1. By using privateIp, I’m able to create a cluster and mount folders via nfs.

**Comment by adavanisanti** [comment]
Hi @enrico-usai could you point me to the steps before slurm_parallelcluster_nodes.conf is created? Based on slurm.conf documentation, in addition to NodeName if we have NodeAddr as part of slurm.conf, we should be able to manage the IP addresses. 

Thanks
Santi

**Comment by lukeseawalker** [comment]
Hi @adavanisanti,
`slurm_parallelcluster_nodes.conf` is written for the first time by chef during master startup, see [here](https://github.com/aws/aws-parallelcluster-cookbook/blob/develop/recipes/_master_slurm_config.rb#L37-L42)
The template of this configuration file is located [here](https://github.com/aws/aws-parallelcluster-cookbook/blob/develop/templates/default/slurm_parallelcluster_nodes.conf.erb)

`slurm_parallelcluster_nodes.conf` is then read and written dynamically by the sqswatcher daemon during cluster scaling, see [here](https://github.com/aws/aws-parallelcluster-node/blob/develop/src/sqswatcher/plugins/slurm.py#L64-L91)

Right now the use of private ips is not supported and some additional work is required to reconfigure the schedulers so that they can properly function with it. 

Since the discussion has shifted from its original question I'm going to mark this ticket in autoclose, feel free to open another ticket if you have any other issue.

Thanks
Luca
