### ISSUE TITLE
sqswatcher multiprocessing.context.TimeoutError

### ISSUE THREAD

**Issue by sanman-99** [aws/aws-parallelcluster#1327]
Environment:

    AWS ParallelCluster / CfnCluster version: aws-parallelcluster-2.4.1
    OS: Centos7
    Scheduler: SGE
    Master instance type: m5.4xlarge
    Compute instance type: r5.2xlarge

Bug description and how to reproduce:

I am having a continuous issue that unfortunately I'm not able to exactly reproduce.  It seems that after a period of time, especially with large scaling events (~50+), somehow the SQS queue is getting backed up, which is causing several different issues.  I am seeing new instances terminate before being added to the SGE queue, which then seems to be a compounding issue.  This is happening every few days, and at times there will be thousands of available messages in the SQS queue, which is causing havoc when trying to scale up new nodes.  I then see, "multiprocessing.context.TimeoutError" in the sqswatcher log.  I'm attaching the sqswatcher and jobwatcher log.

As a temporary workaround I essentially have to purge the SQS queue manually and restart the sqswatcher process, and do some manual cleanup in the SGE queue (because nodes are also not being removed properly during termination).    

**Additional context:**
Attached jobwatcher and sqswatcher log files.  

[sqs_job_watcher_sep212019.zip](https://github.com/aws/aws-parallelcluster/files/3639311/sqs_job_watcher_sep212019.zip)

**Comment by sanman-99** [comment]
I have some updated information to help with this troubleshooting.  I was able to capture some specific events during this issue today.  

HOSTNAME of COMPUTE NODE - ip-172-32-47-134, instance ID - i-09b41c078c9f0d89d

On the master node in the sqswatcher log we see the COMPUTE_READY event for this instance and adding it to SGE and then throws the multiprocessing.context.TimeoutError.

`2019-09-24 13:30:21,656 INFO [sqswatcher:_parse_sqs_messages] Processing parallelcluster:COMPUTE_READY event for instance Host(instance_id='i-09b41c078c9f0d89d', hostname='ip-172-32-47-134', slots='8')
2019-09-24 13:30:29,471 INFO [ssh_keyscan:_add_keys_to_known_hosts] Adding keys to known hosts file '/home/centos/.ssh/known_hosts' for host 'ip-172-32-47-134'
2019-09-24 13:30:29,573 INFO [sge_commands:exec_qconf_command] Executing operation 'add administrative hosts' for hosts ip-172-32-63-198,ip-172-32-41-33,ip-172-32-39-222,ip-172-32-47-38,ip-172-32-35-102,ip-172-32-39-91,ip-172-32-56-16,ip-172-32-63-69,ip-172-32-40-8,ip-172-32-32-219,ip-172-32-33-230,ip-172-32-36-86,ip-172-32-36-222,ip-172-32-40-50,ip-172-32-53-203,ip-172-32-32-30,ip-172-32-60-207,ip-172-32-45-110,ip-172-32-61-152,ip-172-32-48-142,ip-172-32-45-9,ip-172-32-46-8,ip-172-32-48-202,ip-172-32-45-167,ip-172-32-52-109,ip-172-32-49-157,ip-172-32-47-239,ip-172-32-35-177,ip-172-32-57-232,ip-172-32-46-146,ip-172-32-62-187,ip-172-32-57-74,ip-172-32-41-96,ip-172-32-47-134,ip-172-32-57-25,ip-172-32-38-231,ip-172-32-61-144,ip-172-32-55-16,ip-172-32-38-186,ip-172-32-50-48,ip-172-32-49-201,ip-172-32-34-4
2019-09-24 13:30:29,646 INFO [sge_commands:exec_qconf_command] Executing operation 'add submit hosts' for hosts ip-172-32-63-198,ip-172-32-41-33,ip-172-32-39-222,ip-172-32-47-38,ip-172-32-35-102,ip-172-32-39-91,ip-172-32-56-16,ip-172-32-63-69,ip-172-32-40-8,ip-172-32-32-219,ip-172-32-33-230,ip-172-32-36-86,ip-172-32-36-222,ip-172-32-40-50,ip-172-32-53-203,ip-172-32-32-30,ip-172-32-60-207,ip-172-32-45-110,ip-172-32-61-152,ip-172-32-48-142,ip-172-32-45-9,ip-172-32-46-8,ip-172-32-48-202,ip-172-32-45-167,ip-172-32-52-109,ip-172-32-49-157,ip-172-32-47-239,ip-172-32-35-177,ip-172-32-57-232,ip-172-32-46-146,ip-172-32-62-187,ip-172-32-57-74,ip-172-32-41-96,ip-172-32-47-134,ip-172-32-57-25,ip-172-32-38-231,ip-172-32-61-144,ip-172-32-55-16,ip-172-32-38-186,ip-172-32-50-48,ip-172-32-49-201,ip-172-32-34-4
2019-09-24 13:31:10,819 INFO [remote_command_executor:run_remote_command] Executing remote command command on centos@ip-172-32-47-134: sudo sh -c 'cd /opt/sge && /opt/sge/inst_sge -noremote -x -auto /opt/parallelcluster/templates/sge/sge_inst.conf'

2019-09-24 13:32:09,793 ERROR [sqswatcher:main] An unexpected error occurred:
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.9/envs/node_virtualenv/lib/python3.6/site-packages/sqswatcher/sqswatcher.py", line 392, in main
    _poll_queue(config, queue, table, asg_name)
  File "/root/.pyenv/versions/3.6.9/envs/node_virtualenv/lib/python3.6/site-packages/sqswatcher/sqswatcher.py", line 376, in _poll_queue
    force_cluster_update,
  File "/root/.pyenv/versions/3.6.9/envs/node_virtualenv/lib/python3.6/site-packages/sqswatcher/sqswatcher.py", line 292, in _process_sqs_messages
    max_cluster_size, sqs_config.cluster_user, update_events, instance_properties
  File "/root/.pyenv/versions/3.6.9/envs/node_virtualenv/lib/python3.6/site-packages/sqswatcher/plugins/sge.py", line 87, in update_cluster
    added_hosts = _add_hosts(hosts_to_add, cluster_user)
  File "/root/.pyenv/versions/3.6.9/envs/node_virtualenv/lib/python3.6/site-packages/sqswatcher/plugins/sge.py", line 41, in _add_hosts
    succeeded_hosts = install_sge_on_compute_nodes(succeeded_hosts, cluster_user)
  File "/root/.pyenv/versions/3.6.9/envs/node_virtualenv/lib/python3.6/site-packages/common/schedulers/sge_commands.py", line 139, in install_sge_on_compute_nodes
    result = RemoteCommandExecutor.run_remote_command_on_multiple_hosts(command, hostnames, cluster_user)
  File "/root/.pyenv/versions/3.6.9/envs/node_virtualenv/lib/python3.6/site-packages/common/remote_command_executor.py", line 113, in run_remote_command_on_multiple_hosts
    results = r.get(timeout=int(ceil(len(hostnames) / float(parallelism)) * (2 * timeout)))
  File "/root/.pyenv/versions/3.6.9/lib/python3.6/multiprocessing/pool.py", line 640, in get
    raise TimeoutError
multiprocessing.context.TimeoutError
`

On the COMPUTE NODE itself I was able to get in just in time to see the following in the nodewatcher log.  Looks like SGE sees it is down for some reason, even though its not and it then just terminates itself.  This is in less than 10 minutes of actually launching.

`2019-09-24 13:32:24,076 WARNING [sge:is_node_down] Node is not attached to scheduler. Reporting as down
2019-09-24 13:32:24,076 WARNING [nodewatcher:_poll_wait_for_node_ready] Node reported as down
2019-09-24 13:32:34,112 WARNING [sge:is_node_down] Node is not attached to scheduler. Reporting as down
2019-09-24 13:32:34,112 WARNING [nodewatcher:_poll_wait_for_node_ready] Node reported as down
2019-09-24 13:32:44,152 WARNING [sge:is_node_down] Node is not attached to scheduler. Reporting as down
2019-09-24 13:32:44,152 WARNING [nodewatcher:_poll_wait_for_node_ready] Node reported as down
2019-09-24 13:32:54,187 WARNING [sge:is_node_down] Node is not attached to scheduler. Reporting as down
2019-09-24 13:32:54,188 WARNING [nodewatcher:_poll_wait_for_node_ready] Node reported as down
2019-09-24 13:33:04,227 WARNING [sge:is_node_down] Node is not attached to scheduler. Reporting as down
2019-09-24 13:33:04,227 WARNING [nodewatcher:_poll_wait_for_node_ready] Node reported as down
2019-09-24 13:33:14,263 WARNING [sge:is_node_down] Node is not attached to scheduler. Reporting as down
2019-09-24 13:33:14,263 WARNING [nodewatcher:_poll_wait_for_node_ready] Node reported as down
2019-09-24 13:33:14,263 ERROR [nodewatcher:_terminate_if_down] Node is marked as down by scheduler or not attached correctly. Terminating...
2019-09-24 13:33:14,267 INFO [nodewatcher:_dump_logs] Dumping logs to /home/logs/compute/i-09b41c078c9f0d89d.tar.gz
2019-09-24 13:33:14,489 INFO [nodewatcher:_maintain_size] DesiredCapacity is 75, MinSize is 1
2019-09-24 13:33:14,489 INFO [nodewatcher:_self_terminate] Self terminating i-09b41c078c9f0d89d
Connection to ip-172-32-47-134 closed by remote host.
Connection to ip-172-32-47-134 closed.`

[sqswatcherlog9242019.zip](https://github.com/aws/aws-parallelcluster/files/3649308/sqswatcherlog9242019.zip)

**Comment by sanman-99** [comment]
I was able to capture more in the nodewatcher logs.  Right before it self terminates it is erroring on running some of the SGE commands.

`2019-09-24 13:30:13,406 INFO [nodewatcher:_wait_for_stack_ready] Waiting for stack parallelcluster-fs-gal-prd-1901-1a-p41 to be ready
2019-09-24 13:30:13,539 INFO [nodewatcher:_wait_for_stack_ready] Stack parallelcluster-fs-gal-prd-1901-1a-p41 is in status: UPDATE_COMPLETE
2019-09-24 13:30:13,607 ERROR [utils:_run_command] Command '['/opt/sge/bin/lx-amd64/qstat', '-xml', '-g', 'dt', '-u', '*', '-f', '-l', 'hostname=ip-172-32-47-134']' returned non-zero exit status 1.
2019-09-24 13:30:13,607 ERROR [sge:is_node_down] Failed when checking if node is down with exception Command '['/opt/sge/bin/lx-amd64/qstat', '-xml', '-g', 'dt', '-u', '*', '-f', '-l', 'hostname=ip-172-32-47-134']' returned non-zero exit status 1.. Reporting node as down.
2019-09-24 13:30:13,608 WARNING [nodewatcher:_poll_wait_for_node_ready] Node reported as down
2019-09-24 13:30:23,640 ERROR [utils:_run_command] Command '['/opt/sge/bin/lx-amd64/qstat', '-xml', '-g', 'dt', '-u', '*', '-f', '-l', 'hostname=ip-172-32-47-134']' returned non-zero exit status 1.
2019-09-24 13:30:23,640 ERROR [sge:is_node_down] Failed when checking if node is down with exception Command '['/opt/sge/bin/lx-amd64/qstat', '-xml', '-g', 'dt', '-u', '*', '-f', '-l', 'hostname=ip-172-32-47-134']' returned non-zero exit status 1.. Reporting node as down.
2019-09-24 13:30:23,640 WARNING [nodewatcher:_poll_wait_for_node_ready] Node reported as down
2019-09-24 13:30:33,675 WARNING [sge:is_node_down] Node is not attached to scheduler. Reporting as down
2019-09-24 13:30:33,676 WARNING [nodewatcher:_poll_wait_for_node_ready] Node reported as down`

**Comment by enrico-usai** [comment]
Hi @sanman-99 ,
could you attach your configuration without any credentials or personal data?

**Comment by sanman-99** [comment]
See attached.  Using the template galprd1901 in the config.  I also attached the parameters for the cloud formation stack.  

What I think is happening is a race condition between processing the SQS messages and adding to SGE and the INITIAL_TERMINATE_TIMEOUT in /root/.pyenv/versions/3.6.9/envs/node_virtualenv/lib64/python3.6/site-packages/nodewatcher/nodewatcher.py.  Looks like its set to 3 minutes, which doesn't seem to be enough time and the nodes are killing themselves before ever added and this causes the pile up of SQS messages and the compounding issue grows.  Just a theory and I appreciate any help.

[parallelclusterconfig_sanman99.txt](https://github.com/aws/aws-parallelcluster/files/3671588/parallelclusterconfig_sanman99.txt)
[pcluster_parameters.xlsx](https://github.com/aws/aws-parallelcluster/files/3671589/pcluster_parameters.xlsx)

**Comment by lukeseawalker** [comment]
Hi @sanman-99,
I'm looking at the logs.
The nodewatcher behaviour is correct, it terminates itself since the node is not configured from the scheduler point of view, with the exception to understand why you are overriding the nodewatcher.py code in the postinstall script and for which purpose you are doing that.

I would like to investigate more the timeout you are having in the sqswatcher, to understand the root cause why sometimes it is not able to add the compute node to the scheduler configuration.
Can you please post an archive with the content of the `/opt/sge/default/common/install_logs/` folder taken from the master node?
Please post also `/home/logs/compute/i-09b41c078c9f0d89d.tar.gz` taken from the master node.

**Comment by sanman-99** [comment]
I'm overriding that setting since Monday (Sep 30) to see if the issue would not happen anymore.  Since I increased the timeout values I have not had the issue, but understand this is a band-aid and not the appropriate solution or confirmation that this is in fact the issue.

I will upload an archive with that content shortly.

**Comment by lukeseawalker** [comment]
Thank you for the clarification.
Waiting for the archive.

**Comment by sanman-99** [comment]
[pcluster1327installlogs.tar.gz](https://github.com/aws/aws-parallelcluster/files/3682555/pcluster1327installlogs.tar.gz)
[i-09b41c078c9f0d89d.tar.gz](https://github.com/aws/aws-parallelcluster/files/3682557/i-09b41c078c9f0d89d.tar.gz)

**Comment by lukeseawalker** [comment]
We have identified the issue and we are working on a fix.
Unfortunately there isn't a easy way to provide you a workaround to go forward, but I will let you know in case we do have an update on this.

**Comment by sanman-99** [comment]
Thank you, would this issue be specific to SGE or would I also see it if I switched to a different scheduler?

**Comment by lukeseawalker** [comment]
With 2.4.1 you should not experience this issue when using SLURM

**Comment by sanman-99** [comment]
Appreciate the work on this.  In order for these changes to take effect on my current 2.4.1 cluster would I have to redeploy a new cluster?

**Comment by medcelerate** [comment]
I believe I am still seeing this issue with slurm on version 2.6 
```
15:19:34
2020-03-23 15:19:34,011 INFO [slurm:has_jobs] Found the following running jobs: 1007 compute wrap evan.cla R 0:01 1 ip-10-0-28-112

15:19:34
2020-03-23 15:19:34,011 INFO [nodewatcher:_poll_instance_status] Instance has active jobs.

15:20:33
2020-03-23 15:20:33,908 INFO [slurm:is_node_down] Node is in state: ''

15:20:33
2020-03-23 15:20:33,908 WARNING [nodewatcher:_poll_wait_for_node_ready] Node reported as down
```

```
 ERROR [nodewatcher:_terminate_if_down] Node is marked as down by scheduler or not attached correctly. Terminating.
```

**Comment by rexcsn** [comment]
@medcelerate Hi, it's difficult to see how your issue is related to the original issue in this thread from the excerpt of the logs that you provided.

Could you open a new issue, provide details to problems you are experiencing, and attach the logs from your instances? Thank you!
