### ISSUE TITLE
Unsupported instance types causing failures at runtime in node daemons

### ISSUE THREAD

**Issue by Adigorla** [aws/aws-parallelcluster#1364]
**Environment:**
 - AWS ParallelCluster / CfnCluster version: aws-parallelcluster-2.4.1
 - OS: alinux
 - Scheduler: Slurm
 - Master instance type: m5.large
 - Compute instance type: r5dn.8xlarge

**Bug description and how to reproduce:**
Pcluster seems unable to create clusters with any r5n or r5dn instances as compute nodes. 
The following segment from /var/log/sqswatch seems to support this:

> 2019-10-14 19:26:52,078 INFO [sqswatcher:main] sqswatcher startup 
2019-10-14 19:26:52,078 INFO [sqswatcher:_get_config] Reading /etc/sqswatcher.cfg
2019-10-14 19:26:52,079 INFO [sqswatcher:_get_config] Configured parameters: region=us-east-2 scheduler=slurm sqsqueue=parallelcluster-test-cls-5-SQS-166E2ZGF9GWXG table_name=parallelcluster-test-cls-5-DynamoDBTable-12I8B2UOM431N cluster_user=ec2-user proxy=NONE stack_name=parallelcluster-test-cls-5
2019-10-14 19:26:52,411 INFO [utils:get_asg_name] ASG parallelcluster-test-cls-5-ComputeFleet-1AMKHSRBMTMLL found for the stack parallelcluster-test-cls-5
2019-10-14 19:26:52,415 INFO [sqswatcher:_poll_queue] Refreshing cluster properties
2019-10-14 19:26:52,485 INFO [utils:get_asg_settings] min/desired/max 1/1/1
2019-10-14 19:26:52,606 CRITICAL [utils:_get_vcpus_by_instance_type] Unable to get vcpus from instances file. Instance type r5dn.8xlarge not found.
2019-10-14 19:26:52,607 ERROR [sqswatcher:main] An unexpected error occurred: Unable to get vcpus from instances file. Instance type r5dn.8xlarge not found.
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.9/envs/node_virtualenv/lib/python3.6/site-packages/common/utils.py", line 298, in _get_vcpus_by_instance_type
    vcpus = int(instances[instance_type]["vcpus"])
KeyError: 'r5dn.8xlarge'

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.9/envs/node_virtualenv/lib/python3.6/site-packages/sqswatcher/sqswatcher.py", line 392, in main
    _poll_queue(config, queue, table, asg_name)
  File "/root/.pyenv/versions/3.6.9/envs/node_virtualenv/lib/python3.6/site-packages/sqswatcher/sqswatcher.py", line 362, in _poll_queue
    instance_properties = get_instance_properties(sqs_config.region, sqs_config.proxy_config, instance_type)
  File "/root/.pyenv/versions/3.6.9/envs/node_virtualenv/lib/python3.6/site-packages/common/utils.py", line 231, in get_instance_properties
    vcpus = _get_vcpus_from_pricing_file(region, proxy_config, instance_type)
  File "/root/.pyenv/versions/3.6.9/envs/node_virtualenv/lib/python3.6/site-packages/common/utils.py", line 221, in _get_vcpus_from_pricing_file
    return _get_vcpus_by_instance_type(instances, instance_type)
  File "/root/.pyenv/versions/3.6.9/envs/node_virtualenv/lib/python3.6/site-packages/common/utils.py", line 304, in _get_vcpus_by_instance_type
    raise CriticalError(error_msg)
common.utils.CriticalError: Unable to get vcpus from instances file. Instance type r5dn.8xlarge not found.
2019-10-14 19:27:22,629 INFO [sqswatcher:main] sqswatcher startup
2019-10-14 19:27:22,630 INFO [sqswatcher:_get_config] Reading /etc/sqswatcher.cfg
2019-10-14 19:27:22,630 INFO [sqswatcher:_get_config] Configured parameters: region=us-east-2 scheduler=slurm sqsqueue=parallelcluster-test-cls-5-SQS-166E2ZGF9GWXG table_name=parallelcluster-test-cls-5-DynamoDBTable-12I8B2UOM431N cluster_user=ec2-user proxy=NONE stack_name=parallelcluster-test-cls-5
2019-10-14 19:27:22,759 INFO [utils:get_asg_name] ASG parallelcluster-test-cls-5-ComputeFleet-1AMKHSRBMTMLL found for the stack parallelcluster-test-cls-5
2019-10-14 19:27:22,760 INFO [sqswatcher:_poll_queue] Refreshing cluster properties
2019-10-14 19:27:22,878 INFO [utils:get_asg_settings] min/desired/max 1/1/1
2019-10-14 19:27:22,996 CRITICAL [utils:_get_vcpus_by_instance_type] Unable to get vcpus from instances file. Instance type r5dn.8xlarge not found.
2019-10-14 19:27:22,996 ERROR [sqswatcher:main] An unexpected error occurred: Unable to get vcpus from instances file. Instance type r5dn.8xlarge not found.
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.9/envs/node_virtualenv/lib/python3.6/site-packages/common/utils.py", line 298, in _get_vcpus_by_instance_type
    vcpus = int(instances[instance_type]["vcpus"])
KeyError: 'r5dn.8xlarge'

Why would this be happening and how can I fix it?
Thanks

**Comment by demartinofra** [comment]
Hi @Adigorla 

thanks for reporting this. Unfortunately we still need to add support for this new instance type in ParallelCluster, however the failure should occur when validating the config file and not at runtime. I'm going to mark this as a bug for now for the validation part and as an enhancement for the support of the new instance type.

**Comment by demartinofra** [comment]
A follow-up question: are you enabling sanity_check in your cluster config? would you mind sharing the config with us?

**Comment by demartinofra** [comment]
Support for r5dn.8xlarge has been added

**Comment by demartinofra** [comment]
Leaving this open since we need to better handle unsupported instance types rather than failing in scaling daemons. Updating title accordingly to reflect the issue

**Comment by demartinofra** [comment]
This is being addressed in https://github.com/aws/aws-parallelcluster/pull/1451

**Comment by lukeseawalker** [comment]
AWS ParallelCluster 2.6.0 with the fix mentioned above has been released
