### ISSUE TITLE
Unable to launch a Grid Engine cluster using a custom AMI with pcluster-2.5.0

### ISSUE THREAD

**Issue by rmarable** [aws/aws-parallelcluster#1537]
**Environment:**
 - AWS ParallelCluster / CfnCluster version [e.g. aws-parallelcluster-2.4.1] 2.5.0
 - OS: [e.g. alinux] Amazon Linux 2
 - Scheduler: [e.g. SGE] SGE
 - Master instance type: [e.g. m5.xlarge] r5.large
 - Compute instance type: [e.g. c5.8xlarge] r5.large

**Bug description and how to reproduce:**

I am unable to build clusters on Amazon Linux 2 using ParallelCluster-2.5.0 when using a custom AMI.

CloudFormation returns:
```
The following resource(s) failed to create: [MasterServerWaitCondition, ComputeFleet].
```

Here is the output from /var/log/cfn-init.log:
```
    +# Notify compute is ready
    +instance_id_url="http://169.254.169.254/latest/meta-data/instance-id"
    +instance_id=$(curl --retry 3 --retry-delay 0 --silent --fail ${instance_id_
url})
    +instance_type_url="http://169.254.169.254/latest/meta-data/instance-type"
    +instance_type=$(curl --retry 3 --retry-delay 0 --silent --fail ${instance_t
ype_url})
    +local_hostname_url="http://169.254.169.254/latest/meta-data/local-hostname"
    +local_hostname=$(curl --retry 3 --retry-delay 0 --silent --fail ${local_hos
tname_url})
    +/root/.pyenv/versions/3.6.9/envs/cookbook_virtualenv/bin/aws --region ${cfn
_region} sqs send-message --queue-url ${cfn_sqs_queue} --message-body '{"Type" :
 "Notification", "Message" : "{\"StatusCode\":\"Complete\",\"Description\":\"Suc
cesfully launched '${instance_id}'\",\"Event\":\"parallelcluster:COMPUTE_READY\"
,\"EC2InstanceId\":\"'${instance_id}'\",\"Slots\":\"'${cfn_instance_slots}'\",\"
LocalHostname\":\"'${local_hostname}'\",\"EC2InstanceType\":\"'${instance_type}'
\"}"}'
    - change mode from '' to '0755'
    - change owner from '' to 'root'
    - change group from '' to 'root'
[2019-12-09T18:58:52+00:00] WARN: Skipping final node save because override_runl
ist was given
[2019-12-09T18:58:52+00:00] WARN: Skipping final node save because override_runl
ist was given

Running handlers:
Running handlers complete
Chef Client finished, 7/8 resources updated in 20 seconds

2019-12-09 18:58:52,842 [DEBUG] No services specified
2019-12-09 18:58:52,843 [INFO] Running config shellRunPreInstall
2019-12-09 18:58:52,844 [DEBUG] No packages specified
2019-12-09 18:58:52,844 [DEBUG] No groups specified
2019-12-09 18:58:52,844 [DEBUG] No users specified
2019-12-09 18:58:52,844 [DEBUG] No sources specified
2019-12-09 18:58:52,844 [DEBUG] No files specified
2019-12-09 18:58:52,844 [DEBUG] Running command runpreinstall
2019-12-09 18:58:52,844 [DEBUG] No test for command runpreinstall
2019-12-09 18:58:52,855 [ERROR] Command runpreinstall (/opt/parallelcluster/scri
pts/fetch_and_run -preinstall) failed
2019-12-09 18:58:52,855 [DEBUG] Command runpreinstall output: /opt/parallelclust
er/scripts/fetch_and_run: line 19: /root/.pyenv/versions/3.6.9/envs/cookbook_vir
tualenv/bin/aws: No such file or directory
parallelcluster: fetch_and_run - Failed to run boot_as_master preinstall

2019-12-09 18:58:52,855 [ERROR] Error encountered during build of shellRunPreIns
tall: Command runpreinstall failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 542
, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 260
, in build
    changes['commands'] = CommandTool().apply(self._config.commands)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/command_tool.py", line 117
, in apply
    raise ToolError(u"Command %s failed" % name)
ToolError: Command runpreinstall failed
2019-12-09 18:58:52,883 [ERROR] -----------------------BUILD FAILED!------------
------------
2019-12-09 18:58:52,883 [ERROR] Unhandled exception during build: Command runpre
install failed
Traceback (most recent call last):
  File "/opt/aws/bin/cfn-init", line 171, in <module>
    worklog.build(metadata, configSets)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 129
, in build
    Contractor(metadata).build(configSets, self)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 530
, in build
    self.run_config(config, worklog)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 542
, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 260
, in build
    changes['commands'] = CommandTool().apply(self._config.commands)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/command_tool.py", line 117
, in apply
    raise ToolError(u"Command %s failed" % name)
ToolError: Command runpreinstall failed
2019-12-09 18:58:53,082 [DEBUG] CloudFormation client initialized with endpoint
https://cloudformation.us-east-1.amazonaws.com
2019-12-09 18:58:53,082 [DEBUG] Signaling resource MasterServerWaitCondition in
stack parallelcluster-marabro1-eve with unique ID i-01249c727125fed2e and status
 FAILURE

**Additional context:**
Any other context about the problem. E.g.:
 - configuration file without any credentials or personal data.
 - pre/post-install scripts, if any
 - screenshots, if useful
 - if the cluster fails creation, please re-execute `create` action using `--norollback` option and attach `/var/log/cfn-init.log`, `/var/log/cloud-init.log` and `/var/log/cloud-init-output.log` files from the Master node
 - if a compute node was terminated due to failure, there will be a directory `/home/logs/compute`. Attach one of the `instance-id.tar.gz` from that directory
 - if you encounter scaling problems please attach `/var/log/nodewatcher` from the Compute node and `/var/log/jobwatcher` and `/var/log/sqswatcher` from the Master node
```
Here is the output from cloud-init-cmd.log:

```
2019-12-09 18:58:52,841 P17628 [INFO] 	    +/root/.pyenv/versions/3.6.9/envs/cookbook_virtualenv/bin/aws --region ${cfn_region} sqs send-message --queue-url ${cfn_sqs_queue} --message-body '{"Type" : "Notification", "Message" : "{\"StatusCode\":\"Complete\",\"Description\":\"Succesfully launched '${instance_id}'\",\"Event\":\"parallelcluster:COMPUTE_READY\",\"EC2InstanceId\":\"'${instance_id}'\",\"Slots\":\"'${cfn_instance_slots}'\",\"LocalHostname\":\"'${local_hostname}'\",\"EC2InstanceType\":\"'${instance_type}'\"}"}'
2019-12-09 18:58:52,841 P17628 [INFO] 	    - change mode from '' to '0755'
2019-12-09 18:58:52,841 P17628 [INFO] 	    - change owner from '' to 'root'
2019-12-09 18:58:52,841 P17628 [INFO] 	    - change group from '' to 'root'
2019-12-09 18:58:52,841 P17628 [INFO] 	[2019-12-09T18:58:52+00:00] WARN: Skipping final node save because override_runlist was given
2019-12-09 18:58:52,841 P17628 [INFO] 	[2019-12-09T18:58:52+00:00] WARN: Skipping final node save because override_runlist was given
2019-12-09 18:58:52,841 P17628 [INFO]
2019-12-09 18:58:52,841 P17628 [INFO] 	Running handlers:
2019-12-09 18:58:52,841 P17628 [INFO] 	Running handlers complete
2019-12-09 18:58:52,841 P17628 [INFO] 	Chef Client finished, 7/8 resources updated in 20 seconds
2019-12-09 18:58:52,841 P17628 [INFO] ------------------------------------------------------------
2019-12-09 18:58:52,841 P17628 [INFO] Completed successfully.
2019-12-09 18:58:52,843 P17628 [INFO] ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
2019-12-09 18:58:52,843 P17628 [INFO] Config shellRunPreInstall
2019-12-09 18:58:52,844 P17628 [INFO] ============================================================
2019-12-09 18:58:52,844 P17628 [INFO] Command runpreinstall
2019-12-09 18:58:52,854 P17628 [INFO] -----------------------Command Output-----------------------
2019-12-09 18:58:52,854 P17628 [INFO] 	/opt/parallelcluster/scripts/fetch_and_run: line 19: /root/.pyenv/versions/3.6.9/envs/cookbook_virtualenv/bin/aws: No such file or directory
2019-12-09 18:58:52,854 P17628 [INFO] 	parallelcluster: fetch_and_run - Failed to run boot_as_master preinstall
2019-12-09 18:58:52,855 P17628 [INFO] ------------------------------------------------------------
2019-12-09 18:58:52,855 P17628 [ERROR] Exited with error code 1
```

It looks like there is a problem with the location where Chef expects to find the AWS CLI within the image.  I am using a version of Python that lives in a custom directory, so perhaps this is the issue?

Here is the output from cloud-init-output.log:

```
+ export HOME=
+ HOME=
+ mkdir /opt/parallelcluster
+ tee /opt/parallelcluster/.bootstrapped
+ echo aws-parallelcluster-2.5.0
aws-parallelcluster-2.5.0
+ '[' NONE '!=' NONE ']'
+ cd /tmp
+ cfn-init -s parallelcluster-marabro1-eve -v -c default -r MasterServerLaunchTemplate --region us-east-1
Error occurred during build: Command runpreinstall failed
+ error_exit 'Failed to run cfn-init. If --norollback was specified, check /var/log/cfn-init.log and /var/log/cloud-init-output.log.'
+ cfn-signal --exit-code=1 '--reason=Failed to run cfn-init. If --norollback was specified, check /var/log/cfn-init.log and /var/log/cloud-init-output.log.' --stack=parallelcluster-marabro1-eve --resource=MasterServerWaitCondition --region=us-east-1
+ exit 1
Dec 09 18:58:53 cloud-init[2703]: util.py[WARNING]: Failed running /var/lib/cloud/instance/scripts/part-002 [1]
/usr/bin/yum
which: no apt-get in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin)
Not apt system
Dec 09 18:58:53 cloud-init[2703]: cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
Dec 09 18:58:53 cloud-init[2703]: util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_user.pyc'>) failed
Cloud-init v. 18.5-2.amzn2 finished at Mon, 09 Dec 2019 18:58:53 +0000. Datasource DataSourceEc2.  Up 378.07 seconds
```
Finally, here is output from /var/log/messages:

```
Dec  9 18:58:28 ip-10-10-10-29 cloud-init: Vendoring ulimit (1.0.0) to /etc/chef
/cookbooks/ulimit
Dec  9 18:58:28 ip-10-10-10-29 cloud-init: Vendoring yum (5.1.0) to /etc/chef/co
okbooks/yum
Dec  9 18:58:28 ip-10-10-10-29 cloud-init: Vendoring yum-epel (3.1.0) to /etc/ch
ef/cookbooks/yum-epel
Dec  9 18:58:30 ip-10-10-10-29 cloud-init: + export HOME=
Dec  9 18:58:30 ip-10-10-10-29 cloud-init: + HOME=
Dec  9 18:58:30 ip-10-10-10-29 cloud-init: + mkdir /opt/parallelcluster
Dec  9 18:58:30 ip-10-10-10-29 cloud-init: + tee /opt/parallelcluster/.bootstrap
ped
Dec  9 18:58:30 ip-10-10-10-29 cloud-init: + echo aws-parallelcluster-2.5.0
Dec  9 18:58:30 ip-10-10-10-29 cloud-init: aws-parallelcluster-2.5.0
Dec  9 18:58:30 ip-10-10-10-29 cloud-init: + '[' NONE '!=' NONE ']'
Dec  9 18:58:30 ip-10-10-10-29 cloud-init: + cd /tmp
Dec  9 18:58:30 ip-10-10-10-29 cloud-init: + cfn-init -s parallelcluster-marabro
1-eve -v -c default -r MasterServerLaunchTemplate --region us-east-1
Dec  9 18:58:49 ip-10-10-10-29 dbus[1979]: [system] Activating via systemd: serv
ice name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.servic
e'
Dec  9 18:58:49 ip-10-10-10-29 systemd: Starting Hostname Service...
Dec  9 18:58:49 ip-10-10-10-29 dbus[1979]: [system] Successfully activated servi
ce 'org.freedesktop.hostname1'
Dec  9 18:58:49 ip-10-10-10-29 systemd: Started Hostname Service.
Dec  9 18:58:52 ip-10-10-10-29 parallelcluster: fetch_and_run - Failed to run bo
ot_as_master preinstall
Dec  9 18:58:52 ip-10-10-10-29 cloud-init: Error occurred during build: Command
runpreinstall failed
Dec  9 18:58:52 ip-10-10-10-29 cloud-init: + error_exit 'Failed to run cfn-init.
 If --norollback was specified, check /var/log/cfn-init.log and /var/log/cloud-i
nit-output.log.'
Dec  9 18:58:52 ip-10-10-10-29 cloud-init: + cfn-signal --exit-code=1 '--reason=
Failed to run cfn-init. If --norollback was specified, check /var/log/cfn-init.l
og and /var/log/cloud-init-output.log.' --stack=parallelcluster-marabro1-eve --r
esource=MasterServerWaitCondition --region=us-east-1
Dec  9 18:58:53 ip-10-10-10-29 cloud-init: + exit 1
Dec  9 18:58:53 ip-10-10-10-29 cloud-init: Dec 09 18:58:53 cloud-init[2703]: uti
l.py[WARNING]: Failed running /var/lib/cloud/instance/scripts/part-002 [1]
Dec  9 18:58:53 ip-10-10-10-29 cloud-init: /usr/bin/yum
Dec  9 18:58:53 ip-10-10-10-29 cloud-init: which: no apt-get in (/usr/local/sbin
:/usr/local/bin:/usr/sbin:/usr/bin)
Dec  9 18:58:53 ip-10-10-10-29 cloud-init: Not apt system
Dec  9 18:58:53 ip-10-10-10-29 cloud-init: Dec 09 18:58:53 cloud-init[2703]: cc_
scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib
/cloud/instance/scripts)
Dec  9 18:58:53 ip-10-10-10-29 cloud-init: Dec 09 18:58:53 cloud-init[2703]: uti
l.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts
_user' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_user.p
yc'>) failed
Dec  9 18:58:53 ip-10-10-10-29 ec2:
Dec  9 18:58:53 ip-10-10-10-29 ec2: ############################################
#################
Dec  9 18:58:53 ip-10-10-10-29 ec2: -----BEGIN SSH HOST KEY FINGERPRINTS-----
Dec  9 18:58:53 ip-10-10-10-29 ec2: 256 SHA256:JKINlNmitHhcgMUJxIag17hRSQTS58tQk
xjGGdiWQaA no comment (ECDSA)
Dec  9 18:58:53 ip-10-10-10-29 ec2: 256 SHA256:LMqPsK17TaRVmHESlhzp4Lrp+O9rcu6Iu
ibVzq64TWI no comment (ED25519)
Dec  9 18:58:53 ip-10-10-10-29 ec2: 2048 SHA256:KBAtIonkfcb8R3uyMk5mpz3PjgOQWPDk
JeZouowjUO0 no comment (RSA)
Dec  9 18:58:53 ip-10-10-10-29 ec2: -----END SSH HOST KEY FINGERPRINTS-----
Dec  9 18:58:53 ip-10-10-10-29 ec2: ############################################
#################
Dec  9 18:58:53 ip-10-10-10-29 cloud-init: Cloud-init v. 18.5-2.amzn2 finished a
t Mon, 09 Dec 2019 18:58:53 +0000. Datasource DataSourceEc2.  Up 378.07 seconds
Dec  9 18:58:53 ip-10-10-10-29 systemd: cloud-final.service: main process exited
, code=exited, status=1/FAILURE
Dec  9 18:58:53 ip-10-10-10-29 systemd: Failed to start Execute cloud user/final
 scripts.
Dec  9 18:58:53 ip-10-10-10-29 systemd: Unit cloud-final.service entered failed
state.
Dec  9 18:58:53 ip-10-10-10-29 systemd: cloud-final.service failed.
Dec  9 18:58:53 ip-10-10-10-29 systemd: Reached target Cloud-init target.
Dec  9 18:58:53 ip-10-10-10-29 systemd: Startup finished in 2.242s (kernel) + 4.
462s (initrd) + 6min 11.410s (userspace) = 6min 18.115s.
Dec  9 18:58:53 ip-10-10-10-29 systemd: Starting Cloud-init target.
Dec  9 18:59:24 ip-10-10-10-29 amazon-ssm-agent: 2019-12-09 18:59:24 INFO Backin
g off health check to every 600 seconds for 1800 seconds.
Dec  9 18:59:24 ip-10-10-10-29 amazon-ssm-agent: 2019-12-09 18:59:24 ERROR Healt
h ping failed with error - AccessDeniedException: User: arn:aws:sts::83512719516
1:assumed-role/parallelcluster-marabro1-eve-RootRole-1C6YA39YPB9B0/i-01249c72712
5fed2e is not authorized to perform: ssm:UpdateInstanceInformation on resource:
arn:aws:ec2:us-east-1:835127195161:instance/i-01249c727125fed2e
Dec  9 18:59:24 ip-10-10-10-29 amazon-ssm-agent: status code: 400, request id: 7
2fa96a3-6549-4401-8937-2e5072909c83
```

Any guidance you can offer would be hugely appreciated.

Thanks!

Rodney

**Comment by rmarable** [comment]
Amazon Linux 2 is still not supported by ParallelCluster.  I am closing this ticket and will revisit when the aforementioned support is available.
