### ISSUE TITLE
Unable to launch a Grid Engine cluster using a CentOS 7 custom AMI and ParallelCluster-2.5.0

### ISSUE THREAD

**Issue by rmarable** [aws/aws-parallelcluster#1545]
**Environment:**
 - AWS ParallelCluster / CfnCluster version: 2.5.0
 - OS: OSX-10.14.6 (Mojave)
 - Scheduler: SGE
 - Master instance type: r5.large
 - Compute instance type: r5.large

**Bug description and how to reproduce:**
I am unable to create ParallelCluster stacks from a custom centos7 AMI:
```
$ pcluster status marabro1-adam
Status: ComputeFleet - CREATE_IN_PROGRESS                                       Status: CREATE_FAILEDer-marabro1-adam - CREATE_FAILED
2019-12-10 16:39:08.908000+00:00 CREATE_FAILED AWS::CloudFormation::Stack parallelcluster-marabro1-adam The following resource(s) failed to create: [MasterServerWaitCondition, ComputeFleet].
2019-12-10 16:39:07.313000+00:00 CREATE_FAILED AWS::AutoScaling::AutoScalingGroup ComputeFleet Resource creation cancelled
2019-12-10 16:39:05.312000+00:00 CREATE_FAILED AWS::CloudFormation::WaitCondition MasterServerWaitCondition Failed to receive 1 resource signal(s) within the specified duration
```
This is from the output of cloud-init.log on the master:
```
2019-12-10 16:09:50,704 - util.py[DEBUG]: Running command ['/var/lib/cloud/instance/scripts/part-002'] with allowed return codes [0] (shell=False, capture=False)
2019-12-10 16:41:33,350 - util.py[WARNING]: Failed running /var/lib/cloud/instance/scripts/part-002 [1]
2019-12-10 16:41:33,351 - util.py[DEBUG]: Failed running /var/lib/cloud/instance/scripts/part-002 [1]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cloudinit/util.py", line 876, in runparts
    subp(prefix + [exe_path], capture=False)
  File "/usr/lib/python2.7/site-packages/cloudinit/util.py", line 2068, in subp
    cmd=args)
ProcessExecutionError: Unexpected error while running command.
Command: ['/var/lib/cloud/instance/scripts/part-002']
Exit code: 1
Reason: -
Stdout: -
Stderr: -
2019-12-10 16:41:33,374 - util.py[DEBUG]: Running command ['/var/lib/cloud/instance/scripts/runcmd'] with allowed return codes [0] (shell=False, capture=False)
2019-12-10 16:41:33,407 - cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
2019-12-10 16:41:33,407 - handlers.py[DEBUG]: finish: modules-final/config-scripts-user: FAIL: running config-scripts-user with frequency once-per-instance
2019-12-10 16:41:33,407 - util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_user.pyc'>) failed
2019-12-10 16:41:33,407 - util.py[DEBUG]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_user.pyc'>) failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cloudinit/stages.py", line 813, in _run_modules
    freq=freq)
  File "/usr/lib/python2.7/site-packages/cloudinit/cloud.py", line 54, in run
    return self._runners.run(name, functor, args, freq, clear_on_fail)
  File "/usr/lib/python2.7/site-packages/cloudinit/helpers.py", line 187, in run
    results = functor(*args)
  File "/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_user.py", line 45, in handle
    util.runparts(runparts_path)
  File "/usr/lib/python2.7/site-packages/cloudinit/util.py", line 883, in runparts
    % (len(failed), len(attempted)))
RuntimeError: Runparts: 1 failures in 2 attempted commands
```
Grid Engine seems to be working on the master:

```
$ qstat -g c
CLUSTER QUEUE                   CQLOAD   USED    RES  AVAIL  TOTAL aoACDS  cdsuE
--------------------------------------------------------------------------------
all.q                             -NA-      0      0      0      0      0      0
```
But there are no compute nodes present and the Grid Engine binaries are not installed on the compute node.

```
$ ls -l /opt/sge
ls: cannot access /opt/sge: No such file or directory
```

On the compute node, I see this error returned in the messages file right as the cluster goes into failure-to-install mode:
```
Dec 10 16:39:03 ip-10-10-10-192 cloud-init: + '[' CREATE_IN_PROGRESS '!=' UPDATE_COMPLETE ']'
Dec 10 16:39:03 ip-10-10-10-192 cloud-init: + sleep 3
Dec 10 16:39:06 ip-10-10-10-192 cloud-init: ++ aws cloudformation describe-stack-resource --stack-name parallelcluster-marabro1-adam --logical-resource-id MasterServerWaitCondition --region us-east-1 --query StackResourceDetail.ResourceStatus --output text
Dec 10 16:39:06 ip-10-10-10-192 cloud-init: + masterServerStatus=CREATE_FAILED
Dec 10 16:39:06 ip-10-10-10-192 cloud-init: + '[' CREATE_FAILED '!=' CREATE_COMPLETE ']'
Dec 10 16:39:06 ip-10-10-10-192 cloud-init: + '[' CREATE_FAILED '!=' UPDATE_COMPLETE ']'
```
**Additional context:**

I have attached the following logs from the master:

[cloud-init.log](https://github.com/aws/aws-parallelcluster/files/3946558/cloud-init.log)
[cfn-wire.log](https://github.com/aws/aws-parallelcluster/files/3946559/cfn-wire.log)
[cfn-init.log](https://github.com/aws/aws-parallelcluster/files/3946560/cfn-init.log)
[cfn-init-cmd.log](https://github.com/aws/aws-parallelcluster/files/3946561/cfn-init-cmd.log)

Here is the cluster configuration:
[marabro1-adam.config.txt](https://github.com/aws/aws-parallelcluster/files/3946585/marabro1-adam.config.txt)

There is no `/home/logs/compute` present.

Thanks in advance for your insight.

**Comment by rmarable** [comment]
After rebuilding the custom AMI from the ground up and running the ParallelCluster AMI preparation script again, I am now able to deploy Grid Engine clusters on centos7 as expected:

```
$ pcluster createami --ami-id [******************] --os centos7 -c pcluster-ami.config

Building AWS ParallelCluster AMI. This could take a while...
<snipped>
Packer status: ==> custom-centos7: Provisioning with shell script: /var/folders/Packer status: ==> custom-centos7: Provisioning with shell script: /var/folders/Packer status:
==> custom-centos7: Provisioning with shell script: /var/folders/Packer status:
==> custom-centos7: Creating AMI custom-ami-aws-parallelcluster-2Packer status: custom-centos7: Adding tag: "parallelcluster_version": "aws-paralPacker status: 	exit code 0
```
I'm going to build this AMI a few more times to make sure this is fixed and will update this case accordingly.

**Comment by rmarable** [comment]
This is working properly.  There must have been something amiss with the original image that was preventing ParallelCluster from installing on top of it.

**Comment by lukeseawalker** [comment]
From the `cfn-init.log` of the master node there was a failure in restarting the network service.
```
service[network] action restart[2019-12-10T16:41:27+00:00] ERROR: service[network] (hostname::default line 63) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /bin/systemctl --system restart network ----
STDOUT: 
STDERR: Job for network.service failed because the control process exited with error code. See "systemctl status network.service" and "journalctl -xe" for details.
---- End output of /bin/systemctl --system restart network ----
```
This cause the compute node not able to mount the shared folder with the scheduler installation and also the reason why there was no /home/logs/compute present in the master host.

If you are still able to access to the maser node, can you please post the output of `systemctl status network.service` and `journalctl -xe` commands?

Thanks
L
