### ISSUE TITLE
Please Improve the Error Handling of "pcluster createami"

### ISSUE THREAD

**Issue by rmarable** [aws/aws-parallelcluster#1549]
**Environment:**
 - AWS ParallelCluster / CfnCluster version [e.g. aws-parallelcluster-2.4.1] 2.5.0
 - OS: [e.g. alinux] OSX-10.14.6 (Mojave) using pyenv (Python-3.7.4)
 - Scheduler: [e.g. SGE] SGE
 - Master instance type: [e.g. m5.xlarge] r5.large
 - Compute instance type: [e.g. c5.8xlarge] r5.large

**Bug description and how to reproduce:**

Please improve the error handling of the ParallelCluster "createami" feature:
```
$ pcluster createami -ai foo -os foo
Building AWS ParallelCluster AMI. This could take a while...

No custom AMI created
Unexpected error of type AttributeError: 'NoneType' object has no attribute 'get_param_value'
Traceback (most recent call last):
  File "/Users/rodneymarable/.pyenv/versions/3.7.4/envs/compbio-ami/lib/python3.7/site-packages/pcluster/cli.py", line 439, in main
    args.func(args)
  File "/Users/rodneymarable/.pyenv/versions/3.7.4/envs/compbio-ami/lib/python3.7/site-packages/pcluster/cli.py", line 81, in create_ami
    pcluster.create_ami(args)
  File "/Users/rodneymarable/.pyenv/versions/3.7.4/envs/compbio-ami/lib/python3.7/site-packages/pcluster/commands.py", line 831, in create_ami
    pcluster_config = PclusterConfig(config_file=args.config_file, fail_on_file_absence=True)
  File "/Users/rodneymarable/.pyenv/versions/3.7.4/envs/compbio-ami/lib/python3.7/site-packages/pcluster/config/pcluster_config.py", line 64, in __init__
    self._init_config_parser(config_file, fail_on_file_absence)
  File "/Users/rodneymarable/.pyenv/versions/3.7.4/envs/compbio-ami/lib/python3.7/site-packages/pcluster/config/pcluster_config.py", line 109, in _init_config_parser
    self.error(error_message)
  File "/Users/rodneymarable/.pyenv/versions/3.7.4/envs/compbio-ami/lib/python3.7/site-packages/pcluster/config/pcluster_config.py", line 446, in error
    if self.fail_on_error:
  File "/Users/rodneymarable/.pyenv/versions/3.7.4/envs/compbio-ami/lib/python3.7/site-packages/pcluster/config/pcluster_config.py", line 225, in fail_on_error
    self._fail_on_error = self.get_section("global").get_param_value("sanity_check")
AttributeError: 'NoneType' object has no attribute 'get_param_value'
```
Ideally, this command should return the following errors:

- Operating system "foo" is unsupported.
- Image "foo" does not exist in this AWS account
- if the "sanity_check" parameter is unset because the operator doesn't have a default pcluster.config file in their home directory, this condition should be reported to the console.

**Comment by lukeseawalker** [comment]
Hi @rmarable,
this has been fixed with https://github.com/aws/aws-parallelcluster/pull/1476
and will be available in the next release.
Can I ask you if you can post your config file so we can double check that we considered all the possible paths?

Thanks,
L

**Comment by rmarable** [comment]
Hi Luca,

I didn't use a config file.
```
$ ls -al .parallelcluster/
total 4104
drwxr-xr-x   3 rodneymarable  staff       96 Dec  1 16:52 .
drwxr-xr-x+ 60 rodneymarable  staff     1920 Dec 11 13:37 ..
-rw-r--r--   1 rodneymarable  staff  1676971 Dec 11 10:01 pcluster-cli.log
```

**Comment by lukeseawalker** [comment]
Fixed in https://github.com/aws/aws-parallelcluster/releases/tag/v2.5.1
