### ISSUE TITLE
Instances command raises exception if cluster rollbacks

### ISSUE THREAD

**Issue by snorfalorpagus** [aws/aws-parallelcluster#166]
If the instances command is called after the cluster has died an exception is raised, rather than something useful.
```
$ cfncluster status mycluster
Status: ROLLBACK_COMPLETE
2017-02-12 22:13:30.189000 CREATE_FAILED AWS::AutoScaling::AutoScalingGroup ComputeFleet Received 1 FAILURE signal(s) out of 1.  Unable to satisfy 100% MinSuccessfulInstancesPercent requirement
$ cfncluster instances mycluster
Traceback (most recent call last):
  File "/Users/snorf/miniconda3/bin/cfncluster", line 9, in <module>
    load_entry_point('cfncluster', 'console_scripts', 'cfncluster')()
  File "/Users/snorf/Desktop/cfncluster/cli/cfncluster/cli.py", line 160, in main
    args.func(args)
  File "/Users/snorf/Desktop/cfncluster/cli/cfncluster/cli.py", line 38, in instances
    cfncluster.instances(args)
  File "/Users/snorf/Desktop/cfncluster/cli/cfncluster/cfncluster.py", line 406, in instances
    instances.extend(get_asg_instances(stack, config))
  File "/Users/snorf/Desktop/cfncluster/cli/cfncluster/cfncluster.py", line 394, in get_asg_instances
    instances = asgconn.get_all_groups(names=[asg[1]])[0].instances
```

**Comment by jocherry** [comment]
So just to clarify, it would be helpful if the instance call on a cluster with no instances returned a helpful message, as opposed to a stack trace?

**Comment by snorfalorpagus** [comment]
@jocherry Yes. I don't think the user of the CLI should even need to know cfncluster is written in Python. The command should return "no instances", and perhaps "check status?". I say this because, unlike the example above, I called the instances command first. It took me a little while to figure out the cluster hadn't started, rather than it being a bug in cfncluster per-say.

**Comment by demartinofra** [comment]
Fixed in https://github.com/aws/aws-parallelcluster/releases/tag/v2.5.1
