### ISSUE TITLE
Cluster creation failed_fetch_and_run - Failed to run boot_as_master postinstall

### ISSUE THREAD

**Issue by huiqinghu** [aws/aws-parallelcluster#1686]
**Environment:**
 - AWS ParallelCluster / CfnCluster version [e.g. aws-parallelcluster-2.5.1]
 - Configuration file (i.e. ~/.parallelcluster/config) without any credentials or personal data.
[config.txt](https://github.com/aws/aws-parallelcluster/files/4308029/config.txt)
[postinstall.txt](https://github.com/aws/aws-parallelcluster/files/4308030/postinstall.txt)

**Bug description and how to reproduce:**
I have attached the config and postinstall file that used to create cluster. The command that I used is "pcluster create test -nr"
The bug that I got is as follows
"
Cluster creation failed.  Failed events:
  - AWS::CloudFormation::Stack parallelcluster-test The following resource(s) failed to create: [MasterServerWaitCondition]. 
  - AWS::CloudFormation::WaitCondition MasterServerWaitCondition Received FAILURE signal with UniqueId i-0e43dda574dba64a1

I had a look at "/var/log/cfn-init.log" and found some error message

2020-03-09 16:02:37,774 [ERROR] Command runpostinstall (/opt/parallelcluster/scripts/fetch_and_run -postinstall) failed
2020-03-09 16:02:37,774 [DEBUG] Command runpostinstall output: download failed: s3://bucket/path/to/postinstall.sh to - An error occurred (403) when calling the HeadObject operation: Forbidden
parallelcluster: fetch_and_run - Failed to run boot_as_master postinstall

2020-03-09 16:02:37,774 [ERROR] Error encountered during build of shellRunPostInstall: Command runpostinstall failed
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 542, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 260, in build
    changes['commands'] = CommandTool().apply(self._config.commands)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/command_tool.py", line 117, in apply
    raise ToolError(u"Command %s failed" % name)
ToolError: Command runpostinstall failed
2020-03-09 16:02:37,776 [ERROR] -----------------------BUILD FAILED!------------------------
2020-03-09 16:02:37,776 [ERROR] Unhandled exception during build: Command runpostinstall failed
Traceback (most recent call last):
  File "/usr/local/bin/cfn-init", line 171, in <module>
    worklog.build(metadata, configSets)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 129, in build
    Contractor(metadata).build(configSets, self)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 530, in build
    self.run_config(config, worklog)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 542, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 260, in build
    changes['commands'] = CommandTool().apply(self._config.commands)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/command_tool.py", line 117, in apply
    raise ToolError(u"Command %s failed" % name)
ToolError: Command runpostinstall failed
2020-03-09 16:02:37,990 [DEBUG] CloudFormation client initialized with endpoint https://cloudformation.eu-west-1.amazonaws.com
2020-03-09 16:02:37,991 [DEBUG] Signaling resource MasterServerWaitCondition in stack parallelcluster-test with unique ID i-0e43dda574dba64a1 and status FAILURE"

error message in "/var/log/cloud-init.log" file:
"
2020-03-09 16:00:59,185 - util.py[DEBUG]: Running command ['/var/lib/cloud/instance/scripts/part-002'] with allowed return codes [0] (shell=False, capture=False)
2020-03-09 16:02:38,075 - util.py[WARNING]: Failed running /var/lib/cloud/instance/scripts/part-002 [1]
2020-03-09 16:02:38,075 - util.py[DEBUG]: Failed running /var/lib/cloud/instance/scripts/part-002 [1]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cloudinit/util.py", line 885, in runparts
    subp(prefix + [exe_path], capture=False)
  File "/usr/lib/python3/dist-packages/cloudinit/util.py", line 2069, in subp
    cmd=args)
cloudinit.util.ProcessExecutionError: Unexpected error while running command.
Command: ['/var/lib/cloud/instance/scripts/part-002']
Exit code: 1
Reason: -
Stdout: -
Stderr: -
2020-03-09 16:02:38,079 - util.py[DEBUG]: Running command ['/var/lib/cloud/instance/scripts/runcmd'] with allowed return codes [0] (shell=False, capture=False)
2020-03-09 16:02:38,084 - cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
2020-03-09 16:02:38,085 - handlers.py[DEBUG]: finish: modules-final/config-scripts-user: FAIL: running config-scripts-user with frequency once-per-instance
2020-03-09 16:02:38,085 - util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py'>) failed
2020-03-09 16:02:38,085 - util.py[DEBUG]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py'>) failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cloudinit/stages.py", line 847, in _run_modules
    freq=freq)
  File "/usr/lib/python3/dist-packages/cloudinit/cloud.py", line 54, in run
    return self._runners.run(name, functor, args, freq, clear_on_fail)
  File "/usr/lib/python3/dist-packages/cloudinit/helpers.py", line 188, in run
    return (True, results)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3/dist-packages/cloudinit/helpers.py", line 76, in lock
    yield self._acquire(name, freq)
  File "/usr/lib/python3/dist-packages/cloudinit/helpers.py", line 187, in run
    results = functor(*args)
  File "/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py", line 45, in handle
    util.runparts(runparts_path)
  File "/usr/lib/python3/dist-packages/cloudinit/util.py", line 892, in runparts
    % (len(failed), len(attempted)))
RuntimeError: Runparts: 1 failures in 2 attempted commands"

Error message in "/var/log/cloud-init-output.log" file
"
Error occurred during build: Command runpostinstall failed
+ error_exit 'Failed to run cfn-init. If --norollback was specified, check /var/log/cfn-init.log and /var/log/cloud-init-output.log.'
+ cfn-signal --exit-code=1 '--reason=Failed to run cfn-init. If --norollback was specified, check /var/log/cfn-init.log and /var/log/cloud-init-output.log.' --stack=parallelcluster-dhcphuiqing-v2 --resource=MasterServerWaitCondition --region=eu-west-1
+ exit 1
Cloud-init v. 19.2-36-g059d049c-0ubuntu2~16.04.1 running 'modules:final' at Mon, 09 Mar 2020 16:00:59 +0000. Up 47.96 seconds.
2020-03-09 16:02:38,075 - util.py[WARNING]: Failed running /var/lib/cloud/instance/scripts/part-002 [1]
Not yum system
/usr/bin/apt-get
2020-03-09 16:02:38,084 - cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
2020-03-09 16:02:38,085 - util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py'>) failed
Cloud-init v. 19.2-36-g059d049c-0ubuntu2~16.04.1 finished at Mon, 09 Mar 2020 16:02:38 +0000. Datasource DataSourceEc2Local.  Up 147.25 seconds"

**Comment by ddeidda** [comment]
Hi,

from your logs seems like the master node is unable to fetch the postinstall script from your s3 resource. Please make sure that ParallelCluster has access to your s3 bucket. If you are granting access to it through the s3_read_write_resource parameter (like it seems from your config file), please make sure that its value matches the bucket arn where the postinstall script is located. Additional info is available here: https://docs.aws.amazon.com/parallelcluster/latest/ug/s3_resources.html
