### ISSUE TITLE
Compute node build failure - Instances keep spinning and terminating 

### ISSUE THREAD

**Issue by alichry** [aws/aws-parallelcluster#1733]
**Environment:**
 - AWS ParallelCluster / CfnCluster version [aws-parallelcluster-2.5.1]
 - Configuration file (i.e. ~/.parallelcluster/config) without any credentials or personal data.
```
[aws]
aws_region_name = us-east-1

[global]
cluster_template = default
update_check = true
sanity_check = true

[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}

[cluster default]
key_name = xxx
initial_queue_size = 0
max_queue_size = 16
maintain_initial_size = true
vpc_settings = default
master_instance_type = t2.micro
master_root_volume_size = 25
compute_instance_type = c5.xlarge
compute_root_volume_size = 25
base_os = centos7
post_install = https://xxxxx/bootstrap.sh
post_install_args = "10.0.4.206"
ebs_settings = default

[scaling deafult]
scaledown_idletime = 5

[ebs default]
# we couldn't find a way to disable shared dir
# so we put 1GB as the minimum size
volume_size = 1

# Uncomment before configuring
[vpc default]
vpc_id = vpc-xxxxxxxxxxxxxx
master_subnet_id = subnet-xxxxxxxxxxxxxxx
```
**Bug description and how to reproduce:**
We've ran pcluster create before modifying ebs settings in the config file. After creation, I tried to disable the shared_dir by decreasing the volume_size, but it didn't help. I ended up deleting the EBS volume. I submitted multiple jobs today, they all worked. I was tackling an issue with an sge warning pertaining job is not allowed to run in any queue (https://forums.aws.amazon.com/thread.jspa?messageID=676978). I've modified the post-install script accordingly but noticed that the instances are spinning and terminating, I reverted the post-install script and instances kept terminating. In other words, after a job submission, an ec2 instances is up and is "initializing". A couple of minutes later, the instance will be terminated and another will be "initializing."

**Additional context:**
Any other context about the problem. E.g.:
 - pre/post-install scripts, if any

Post-install. Small script to synchronize users (just copying users to /etc/passwd from the master node to the compute node)
```
#!/bin/sh
set -e

. "/etc/parallelcluster/cfnconfig"

case "${cfn_node_type}" in
    MasterServer)
        ;;
    ComputeFleet)
	MASTER_NODE_IP="${2:-10.0.4.206}"
	COPYPASSWD_URL="https://xxxx/copypasswd.sh"
	COPYPASSWD_FILE="${HOME}/copypasswd.sh"
	CRONJOB_LINE="*/5 * * * * ${COPYPASSWD_FILE}"
	curl -o "${COPYPASSWD_FILE}" "${COPYPASSWD_URL}"
	chmod +x "${COPYPASSWD_FILE}"
	tmpfile=`mktemp`
	crontab -l > "${tmpfile}" 2> /dev/null || true
	if ! grep -F "${CRONJOB_LINE}" "${tmpfile}"; then
		echo "${CRONJOB_LINE} \"${1}\" ${MASTER_NODE_IP}" >> "${tmpfile}"
		crontab "${tmpfile}"
		rm "${tmpfile}"
		echo "cronjob installed"
	else
		echo "cronjob already installed."
	fi
	;;
    *)
	;;
esac
```
 - if a compute node was terminated due to failure, there will be a directory `/home/logs/compute`. Attach one of the `instance-id.tar.gz` from that directory
The instance i-075d33d23ab2b2530 was recently terminated. Unfortunately, there is no corresponding tarball.
 - if you encounter scaling problems please attach `/var/log/nodewatcher` from the Compute node and `/var/log/jobwatcher` and `/var/log/sqswatcher` from the Master node
There is a scaling problem since there exists 0 pending jobs, yet nodes keep spinning and terminating, ```qstat -s p -u "*"``` returns nothing.
jobwatcher
```
2020-04-11 15:32:08,862 INFO [jobwatcher:_poll_scheduler_status] There are no pending jobs or the requirements on pending jobs cannot be satisfied. Noop.
2020-04-11 15:33:08,755 INFO [utils:get_asg_settings] ASG min/desired/max: 0/1/16
2020-04-11 15:33:08,768 INFO [sge:_get_required_slots] Found the following pending jobs:
[]
2020-04-11 15:33:08,768 INFO [jobwatcher:_poll_scheduler_status] There are no pending jobs or the requirements on pending jobs cannot be satisfied. Noop.
```
sqswatcher
```
2020-04-11 15:36:41,492 INFO [sqswatcher:_retrieve_all_sqs_messages] Retrieving messages from SQS queue
2020-04-11 15:36:43,500 INFO [sqswatcher:_retrieve_all_sqs_messages] Retrieved 0 messages from SQS queue
2020-04-11 15:37:11,502 INFO [sqswatcher:_retrieve_all_sqs_messages] Retrieving messages from SQS queue
2020-04-11 15:37:13,564 INFO [sqswatcher:_retrieve_all_sqs_messages] Retrieved 1 messages from SQS queue
2020-04-11 15:37:13,570 ERROR [sqswatcher:_process_instance_terminate_event] Instance i-062f7e6d2ef1f6c38 not found in the database.
2020-04-11 15:37:13,570 WARNING [sqswatcher:_requeue_message] Re-queuing failed event {"Type": "Notification", "MessageId": "ac42c0dd-c2d1-5ae4-a5dc-97d624b2250a", "TopicArn": "arn:aws:sns:us-east-1:*******:parallelcluster-yyyyy-SNS-*********", "Subject": "Auto Scaling: termination for group \"parallelcluster-yyyyy-ComputeFleet-*********\"", "Message": "{\"Progress\":50,\"AccountId\":\"*********\",\"Description\":\"Terminating EC2 instance: i-062f7e6d2ef1f6c38\",\"RequestId\":\"dcf5c5a7-852c-48b1-4787-e6ff77532413\",\"EndTime\":\"2020-04-11T15:37:07.443Z\",\"AutoScalingGroupARN\":\"arn:aws:autoscaling:us-east-1:******:autoScalingGroup:680da7d3-0d08-4c48-b234-f80f4d55452d:autoScalingGroupName/parallelcluster-yyyyy-ComputeFleet-*********\",\"ActivityId\":\"dcf5c5a7-852c-48b1-4787-e6ff77532413\",\"StartTime\":\"2020-04-11T15:35:04.722Z\",\"Service\":\"AWS Auto Scaling\",\"Time\":\"2020-04-11T15:37:07.443Z\",\"EC2InstanceId\":\"i-062f7e6d2ef1f6c38\",\"StatusCode\":\"InProgress\",\"StatusMessage\":\"\",\"Details\":{\"Subnet ID\":\"subnet-0247d468e5c1121e2\",\"Availability Zone\":\"us-east-1a\"},\"AutoScalingGroupName\":\"parallelcluster-yyyyy-ComputeFleet-*******\",\"Cause\":\"At 2020-04-11T15:35:04Z an instance was taken out of service in response to a user health-check.\",\"Event\":\"autoscaling:EC2_INSTANCE_TERMINATE\"}", "Timestamp": "2020-04-11T15:37:07.506Z", "SignatureVersion": "1", "Signature": "DSlQQ4tA7B6tIMHCcmhPauzi2ywrOnmbM9R/T6/QGKoWR/5Ahi/P9XNduKKeDQwUcuZ7xMIdxQd/1X1uivYFJIx5IauCCNLF72ja2o7JpZO94R3+5TBbE3z0Ja7EzZ8i2ZyDqiRvAkRQBkElCS4W2eVOL91Z/vg6lrx1vNoOprUDaOyruydfAoto789zYmBxqvRBe02V4fZNlOWphFpT6gg1YWZ/WANdG0YqAUV66stNvw0ama6lYyfPyX4qoIGYzyQUF2cr+mGlacKmE5x1uwMbeUygquURHZFLMcsr1dLF1Ys5jOfhmGNfDHM9U0T+p5Z4d2Muu1wzzGtbK7YLcw==", "SigningCertURL": "https://sns.us-east-1.amazonaws.com/SimpleNotificationService-a86cb10b4e1f29c941702d737128f7b6.pem", "UnsubscribeURL": "https://sns.us-east-1.amazonaws.com/?Action=Unsubscribe&SubscriptionArn=arn:aws:sns:us-east-1:********:parallelcluster-yyyyy-SNS-1P6RV36RQDG73:a927026b-add6-4fe9-98da-c6afe90181a4", "TTL": 2}
2020-04-11 15:37:13,579 WARNING [sqswatcher:_parse_sqs_messages] Discarding message sqs.Message(queue_url='https://queue.amazonaws.com/878833948026/parallelcluster-yyyyy-SQS-EPUNM34VBANK', receipt_handle='AQEBeOj3uvmRCbFrzzzwifPQeLeVDCY/QA9mupmC6fVcXiMS5sH8eWUhA71iud91+QjRm6ZMg7M/arkLCj03z1CDFjAGFzdYSO0EblvyxbRQLhZeMw1ObhF5E9Fy5+xCwwp71xkM49f+AzsVG+WZISKzq+YJTgeEqlWpwM81FJt3BQjDfHxWssiq8hDAu8rNsp3WBYkHJteYKGvIFVvXWpnpMCMrUxLOz77NtbKscVUvtih8WN78L2+97d7Y5r50FbQInuH7RDJGnM+7mq71UBegvi7de8UZNRsPRLJgyhwOB9N/EVuan36qxNkGnuVtCJOUHP9aFQfqFYnr7I3vs+NkO+4esDCn3EZzXP4J9UgTOWOb/+5XXdXCLdLY1V7jAKNOyKtSD5lNpOlohHTMk721GC2KJy3nEpBIX5+pPdzPCRI=')
2020-04-11 15:37:41,514 INFO [sqswatcher:_retrieve_all_sqs_messages] Retrieving messages from SQS queue
2020-04-11 15:37:43,523 INFO [sqswatcher:_retrieve_all_sqs_messages] Retrieved 0 messages from SQS queue
2020-04-11 15:38:11,542 INFO [sqswatcher:_poll_queue] Refreshing cluster properties
2020-04-11 15:38:11,641 INFO [utils:get_asg_settings] ASG min/desired/max: 0/1/16
2020-04-11 15:38:11,717 INFO [sqswatcher:_retrieve_all_sqs_messages] Retrieving messages from SQS queue
2020-04-11 15:38:15,619 INFO [sqswatcher:_retrieve_all_sqs_messages] Retrieved 1 messages from SQS queue
2020-04-11 15:38:15,626 ERROR [sqswatcher:_process_instance_terminate_event] Instance i-062f7e6d2ef1f6c38 not found in the database.
2020-04-11 15:38:15,626 WARNING [sqswatcher:_requeue_message] Re-queuing failed event {"Type": "Notification", "MessageId": "ac42c0dd-c2d1-5ae4-a5dc-97d624b2250a", "TopicArn": "arn:aws:sns:us-east-1:*****:parallelcluster-yyyy-SNS-1P6RV36RQDG73", "Subject": "Auto Scaling: termination for group \"parallelcluster-yyyy-ComputeFleet-******\"", "Message": "{\"Progress\":50,\"AccountId\":\"******\",\"Description\":\"Terminating EC2 instance: i-062f7e6d2ef1f6c38\",\"RequestId\":\"dcf5c5a7-852c-48b1-4787-e6ff77532413\",\"EndTime\":\"2020-04-11T15:37:07.443Z\",\"AutoScalingGroupARN\":\"arn:aws:autoscaling:us-east-1:******:autoScalingGroup:680da7d3-0d08-4c48-b234-f80f4d55452d:autoScalingGroupName/parallelcluster-yyyyy-ComputeFleet-*****\",\"ActivityId\":\"dcf5c5a7-852c-48b1-4787-e6ff77532413\",\"StartTime\":\"2020-04-11T15:35:04.722Z\",\"Service\":\"AWS Auto Scaling\",\"Time\":\"2020-04-11T15:37:07.443Z\",\"EC2InstanceId\":\"i-062f7e6d2ef1f6c38\",\"StatusCode\":\"InProgress\",\"StatusMessage\":\"\",\"Details\":{\"Subnet ID\":\"subnet-0247d468e5c1121e2\",\"Availability Zone\":\"us-east-1a\"},\"AutoScalingGroupName\":\"parallelcluster-yyyy-ComputeFleet-*****\",\"Cause\":\"At 2020-04-11T15:35:04Z an instance was taken out of service in response to a user health-check.\",\"Event\":\"autoscaling:EC2_INSTANCE_TERMINATE\"}", "Timestamp": "2020-04-11T15:37:07.506Z", "SignatureVersion": "1", "Signature": "DSlQQ4tA7B6tIMHCcmhPauzi2ywrOnmbM9R/T6/QGKoWR/5Ahi/P9XNduKKeDQwUcuZ7xMIdxQd/1X1uivYFJIx5IauCCNLF72ja2o7JpZO94R3+5TBbE3z0Ja7EzZ8i2ZyDqiRvAkRQBkElCS4W2eVOL91Z/vg6lrx1vNoOprUDaOyruydfAoto789zYmBxqvRBe02V4fZNlOWphFpT6gg1YWZ/WANdG0YqAUV66stNvw0ama6lYyfPyX4qoIGYzyQUF2cr+mGlacKmE5x1uwMbeUygquURHZFLMcsr1dLF1Ys5jOfhmGNfDHM9U0T+p5Z4d2Muu1wzzGtbK7YLcw==", "SigningCertURL": "https://sns.us-east-1.amazonaws.com/SimpleNotificationService-a86cb10b4e1f29c941702d737128f7b6.pem", "UnsubscribeURL": "https://sns.us-east-1.amazonaws.com/?Action=Unsubscribe&SubscriptionArn=arn:aws:sns:us-east-1:*******:parallelcluster-yyyy-SNS-1P6RV36RQDG73:a927026b-add6-4fe9-98da-c6afe90181a4", "TTL": 1}
2020-04-11 15:38:15,636 WARNING [sqswatcher:_parse_sqs_messages] Discarding message sqs.Message(queue_url='https://queue.amazonaws.com/878833948026/parallelcluster-yyyy-S-EPUNM34VBANK', receipt_handle='AQEBpQzzcaPhUP4WfecBOfXGu3VzOSYqGGM1pydf4eDgrYAwkttAsEf3hy6uEVyGx74MQJ6TaCcAoPyP4a0OyV5o/UXf1P3WBrcioFmnAwyjqq96elNLDtWXJeb4NIAyE6goihilLgzGAFRJSuu28i/CYSSF3FFByQZBqxWliKwAAfV7kwZoDm8uUBWTK51AEcb97ChzpTpbIhVkf8j4EgLbenOvy0z1bumO3JwonCAvHgf7DZ4XGwFSy4i4QkF6iqUo9NuNVX4iY2QwPiBlLDvkI7iaBUZSmb7PLJY3Cptulkhuq5O76lM5u/9uYj1gb2Qc1mmJ6+efbLK38hjBtLvdJL66oyraJMWo3CMpFjT9KI48wSTl2KqfDjPbBfhcHyJxHbmHG+jPlUmMS0PqNHY8VYNJ/B4DotS9weW0F6kPgZI=')
2020-04-11 15:38:41,568 INFO [sqswatcher:_retrieve_all_sqs_messages] Retrieving messages from SQS queue
2020-04-11 15:38:43,576 INFO [sqswatcher:_retrieve_all_sqs_messages] Retrieved 0 messages from SQS queue
2020-04-11 15:39:11,596 INFO [sqswatcher:_retrieve_all_sqs_messages] Retrieving messages from SQS queue
2020-04-11 15:39:13,612 INFO [sqswatcher:_retrieve_all_sqs_messages] Retrieved 0 messages from SQS queue

```

cfn-init.log from an instance that got terminated (SSH'd during build and ran ```tail -f /var/log/cfn-init.log```
```
[2020-04-11T15:34:58+00:00] ERROR: Exception handlers complete
[2020-04-11T15:34:58+00:00] ERROR: Exception handlers complete
Chef Client failed. 27 resources updated in 17 seconds
[2020-04-11T15:34:58+00:00] FATAL: Stacktrace dumped to /etc/chef/local-mode-cache/cache/chef-stacktrace.out
[2020-04-11T15:34:58+00:00] FATAL: Stacktrace dumped to /etc/chef/local-mode-cache/cache/chef-stacktrace.out
[2020-04-11T15:34:58+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2020-04-11T15:34:58+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2020-04-11T15:34:58+00:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: mount[/home] (aws-parallelcluster::_compute_base_config line 45) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '32'
---- Begin output of mount -t nfs -o hard,intr,noatime,vers=3,_netdev ip-10-0-4-206.ec2.internal:/home /home ----
STDOUT: 
STDERR: mount.nfs: requested NFS version or transport protocol is not supported
---- End output of mount -t nfs -o hard,intr,noatime,vers=3,_netdev ip-10-0-4-206.ec2.internal:/home /home ----
Ran mount -t nfs -o hard,intr,noatime,vers=3,_netdev ip-10-0-4-206.ec2.internal:/home /home returned 32
[2020-04-11T15:34:58+00:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: mount[/home] (aws-parallelcluster::_compute_base_config line 45) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '32'
---- Begin output of mount -t nfs -o hard,intr,noatime,vers=3,_netdev ip-10-0-4-206.ec2.internal:/home /home ----
STDOUT: 
STDERR: mount.nfs: requested NFS version or transport protocol is not supported
---- End output of mount -t nfs -o hard,intr,noatime,vers=3,_netdev ip-10-0-4-206.ec2.internal:/home /home ----
Ran mount -t nfs -o hard,intr,noatime,vers=3,_netdev ip-10-0-4-206.ec2.internal:/home /home returned 32

2020-04-11 15:34:59,020 [ERROR] Error encountered during build of chefConfig: Command chef failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 542, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 260, in build
    changes['commands'] = CommandTool().apply(self._config.commands)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/command_tool.py", line 117, in apply
    raise ToolError(u"Command %s failed" % name)
ToolError: Command chef failed
2020-04-11 15:34:59,051 [ERROR] -----------------------BUILD FAILED!------------------------
2020-04-11 15:34:59,051 [ERROR] Unhandled exception during build: Command chef failed
Traceback (most recent call last):
  File "/bin/cfn-init", line 171, in <module>
    worklog.build(metadata, configSets)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 129, in build
    Contractor(metadata).build(configSets, self)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 530, in build
    self.run_config(config, worklog)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 542, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 260, in build
    changes['commands'] = CommandTool().apply(self._config.commands)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/command_tool.py", line 117, in apply
    raise ToolError(u"Command %s failed" % name)
ToolError: Command chef failed
2020-04-11 15:35:00,581 [DEBUG] CloudFormation client initialized with endpoint https://cloudformation.us-east-1.amazonaws.com
2020-04-11 15:35:00,581 [DEBUG] Signaling resource ComputeFleet in stack parallelcluster-yyyy with unique ID i-062f7e6d2ef1f6c38 and status FAILURE
```

I expect ```STDERR: mount.nfs: requested NFS version or transport protocol is not supported``` to be the issue?

```pcluster stop``` aided in stopping the spinning and termination of instances.

**Comment by alichry** [comment]
I was not able to reproduce the issue. I recreated the cluster, and I did not observe any build failure.

**Comment by demartinofra** [comment]
Hi Ali,

thanks for reporting this. According to your logs and as you already pointed out, the issue seems to be related to compute nodes not being able to mount the shared `/home` dir over NFS at boot. Such nodes are being replaced by ParallelCluster because they fail at boot, hence you see instances spinning up and terminating in a loop.

I'm now wondering what could have caused the issue on your previous cluster. `STDERR: mount.nfs: requested NFS version or transport protocol is not supported` could be returned as error also when the NFS server running on the master node stops or is unresponsive. If you still have the old cluster could you check the status of nfs service by running: 
```
service nfs status
showmount -e localhost
```

Have you ran any command on the master node that might have interfered with the nfs server in your first cluster?

**Comment by alichry** [comment]
Hello :)
Thank you for your reply. 

I did not run any commands pertaining nfs, I took a look at the exports file and fstab after deleting the EBS volumed that corresponds to the /shared directory. The /shared directory still existed after the deletion, so it was not a problem. Only printing commands like ```lsblk``` and ```df -h```, nothing that can affect nfs. On the current cluster, my shared_dir size is only 1Gb (I did not delete the EBS)

The only systems command I ran are installing nginx only. I may have stopped and later on started the master node multiple times. 

Unfortunately, I have deleted the old cluster. In case it happens again, I'll be sure to run those!

**Comment by demartinofra** [comment]
>  The only systems command I ran are installing nginx only. I may have stopped and later on started the master node multiple times.

I'm wondering if any of these operations left the nfs server in a stopped state.

I'm going to resolve this for now but feel free to re-open this issue in case you hit the same error or have any related questions and we'll be more than happy to provide support :)
