### ISSUE TITLE
Unexpected error of type TypeError: 'Section' object is not iterable

### ISSUE THREAD

**Issue by armaneshaghi** [aws/aws-parallelcluster#1990]
**Environment:**
 - AWS ParallelCluster 2.8.1 on Mac OS X 10.15.5 

**Bug description and how to reproduce:**

I encounter the following error as soon as I run `pcluster confiugre`  in eu-west-2:

```
Status: parallelclusternetworking-pub-20200830163401 - CREATE_COMPLETE          
The stack has been created
Unexpected error of type TypeError: 'Section' object is not iterable
Traceback (most recent call last):
  File "/Users/mac/anaconda/envs/development/lib/python3.6/site-packages/pcluster/cli.py", line 454, in main
    args.func(args)
  File "/Users/mac/anaconda/envs/development/lib/python3.6/site-packages/pcluster/cli.py", line 39, in configure
    easyconfig.configure(args)
  File "/Users/mac/anaconda/envs/development/lib/python3.6/site-packages/pcluster/configure/easyconfig.py", line 188, in configure
    pcluster_config.to_file()
  File "/Users/mac/anaconda/envs/development/lib/python3.6/site-packages/pcluster/config/pcluster_config.py", line 265, in to_file
    self.get_section("cluster").to_file(self.config_parser)
  File "/Users/mac/anaconda/envs/development/lib/python3.6/site-packages/pcluster/config/param_types.py", line 1412, in to_file
    param.to_file(config_parser, write_defaults)
  File "/Users/mac/anaconda/envs/development/lib/python3.6/site-packages/pcluster/config/param_types.py", line 1202, in to_file
    sections.update(self.pcluster_config.get_section(self.referred_section_key, section_label.strip()))
TypeError: 'Section' object is not iterable

```

**Comment by armaneshaghi** [comment]
I am not sure what the specific problem was but seems to be an incompatibility between new (2.8.1) pcluster and older awscli. In any case, you need  a fresh install of awscli and pcluster if you encounter the above issue.
