### ISSUE TITLE
SignatureDoesNotMatch from sqswatcher and jobwatcher, even with chronyd running and configured

### ISSUE THREAD

**Issue by joeydumont** [aws/aws-parallelcluster#2055]
**Environment:**
 - aws-parallelcluster-2.5.1
 - centos7
 - Scheduler: slurm
 - Master instance type: t3.micro
 - Compute instance type: m5a.xlarge

**Bug description and how to reproduce:**
sqswatcher and jobwatcher report `SignatureDoesNotMatch` errors after the head node as been running for a while. Isssue #1651 recommends setting up chronyd to look at time from AWS servers, but that's already running and configured on this cluster. 

A reboot of the head node fixed the issue, but this is not ideal. Because of the reboot, and because of CentOS7 `journalctl` config, I can't review the previous boot logs, so I'm not sure if chronyd had an issue before.

Is time drift the only explanation for this?

`/var/log/sqswatcher` snippet:

```
2020-09-17 13:01:43,704 INFO [sqswatcher:_get_config] Reading /etc/sqswatcher.cfg
2020-09-17 13:01:43,704 INFO [sqswatcher:_get_config] Configured parameters: region=ca-central-1 scheduler=slurm sqsqueue=parallelcluster-hpcbioinf-dev-SQS-MIXPMB1OSMZ6 table_name=parallelcluster-hpcbioinf-dev-D
ynamoDBTable-14ZF9ENM7VFM7 cluster_user=centos proxy=NONE stack_name=parallelcluster-hpcbioinf-dev max_processed_messages=200
2020-09-17 13:01:43,738 CRITICAL [sqswatcher:_get_sqs_queue] Unable to get the SQS queue 'parallelcluster-hpcbioinf-dev-SQS-MIXPMB1OSMZ6'. Failed with exception: An error occurred (SignatureDoesNotMatch) when ca
lling the GetQueueUrl operation: Signature expired: 20200917T130143Z is now earlier than 20200917T145222Z (20200917T150722Z - 15 min.)
2020-09-17 13:01:48,763 CRITICAL [sqswatcher:_get_sqs_queue] Unable to get the SQS queue 'parallelcluster-hpcbioinf-dev-SQS-MIXPMB1OSMZ6'. Failed with exception: An error occurred (SignatureDoesNotMatch) when ca
lling the GetQueueUrl operation: Signature expired: 20200917T130148Z is now earlier than 20200917T145227Z (20200917T150727Z - 15 min.)
2020-09-17 13:01:53,790 CRITICAL [sqswatcher:_get_sqs_queue] Unable to get the SQS queue 'parallelcluster-hpcbioinf-dev-SQS-MIXPMB1OSMZ6'. Failed with exception: An error occurred (SignatureDoesNotMatch) when ca
lling the GetQueueUrl operation: Signature expired: 20200917T130153Z is now earlier than 20200917T145233Z (20200917T150733Z - 15 min.)
2020-09-17 13:01:53,791 ERROR [sqswatcher:main] An unexpected error occurred: An error occurred (SignatureDoesNotMatch) when calling the GetQueueUrl operation: Signature expired: 20200917T130153Z is now earlier 
than 20200917T145233Z (20200917T150733Z - 15 min.)
Traceback (most recent call last):
  File "/usr/local/pyenv/versions/3.6.9/envs/node_virtualenv/lib/python3.6/site-packages/sqswatcher/sqswatcher.py", line 426, in main
    queue = _get_sqs_queue(config.region, config.sqsqueue, config.proxy_config)
  File "/usr/local/pyenv/versions/3.6.9/envs/node_virtualenv/lib/python3.6/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/usr/local/pyenv/versions/3.6.9/envs/node_virtualenv/lib/python3.6/site-packages/retrying.py", line 212, in call
    raise attempt.get()
  File "/usr/local/pyenv/versions/3.6.9/envs/node_virtualenv/lib/python3.6/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/local/pyenv/versions/3.6.9/envs/node_virtualenv/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/pyenv/versions/3.6.9/envs/node_virtualenv/lib/python3.6/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/usr/local/pyenv/versions/3.6.9/envs/node_virtualenv/lib/python3.6/site-packages/sqswatcher/sqswatcher.py", line 128, in _get_sqs_queue
    queue = sqs.get_queue_by_name(QueueName=queue_name)
  File "/usr/local/pyenv/versions/3.6.9/envs/node_virtualenv/lib/python3.6/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/usr/local/pyenv/versions/3.6.9/envs/node_virtualenv/lib/python3.6/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/usr/local/pyenv/versions/3.6.9/envs/node_virtualenv/lib/python3.6/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/pyenv/versions/3.6.9/envs/node_virtualenv/lib/python3.6/site-packages/botocore/client.py", line 626, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (SignatureDoesNotMatch) when calling the GetQueueUrl operation: Signature expired: 20200917T130153Z is now earlier than 20200917T145233Z (20200917T150733Z - 15 
min.)
```

`/var/log/jobwatcher/` snippet:
```
2020-09-17 13:01:19,648 INFO [jobwatcher:main] jobwatcher startup
2020-09-17 13:01:19,648 INFO [jobwatcher:_get_config] Reading /etc/jobwatcher.cfg
2020-09-17 13:01:19,648 INFO [jobwatcher:_get_config] Configured parameters: region=ca-central-1 scheduler=slurm stack_name=parallelcluster-hpcbioinf-dev pcluster_dir=/opt/parallelcluster proxy=NONE
2020-09-17 13:01:19,669 ERROR [jobwatcher:main] An unexpected error occurred: Unable to get ASG for stack parallelcluster-hpcbioinf-dev. Failed with exception: An error occurred (SignatureDoesNotMatch) when call
ing the DescribeTags operation: Signature expired: 20200917T130119Z is now earlier than 20200917T150155Z (20200917T150655Z - 5 min.)
Traceback (most recent call last):
  File "/usr/local/pyenv/versions/3.6.9/envs/node_virtualenv/lib/python3.6/site-packages/common/utils.py", line 80, in get_asg_name
    response = asg_client.describe_tags(Filters=[{"Name": "Value", "Values": [stack_name]}])
  File "/usr/local/pyenv/versions/3.6.9/envs/node_virtualenv/lib/python3.6/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/pyenv/versions/3.6.9/envs/node_virtualenv/lib/python3.6/site-packages/botocore/client.py", line 626, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (SignatureDoesNotMatch) when calling the DescribeTags operation: Signature expired: 20200917T130119Z is now earlier than 20200917T150155Z (20200917T150655Z - 5 
min.)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/pyenv/versions/3.6.9/envs/node_virtualenv/lib/python3.6/site-packages/jobwatcher/jobwatcher.py", line 153, in main
    asg_name = get_asg_name(config.stack_name, config.region, config.proxy_config)
  File "/usr/local/pyenv/versions/3.6.9/envs/node_virtualenv/lib/python3.6/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/usr/local/pyenv/versions/3.6.9/envs/node_virtualenv/lib/python3.6/site-packages/retrying.py", line 206, in call
    return attempt.get(self._wrap_exception)
  File "/usr/local/pyenv/versions/3.6.9/envs/node_virtualenv/lib/python3.6/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/local/pyenv/versions/3.6.9/envs/node_virtualenv/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/pyenv/versions/3.6.9/envs/node_virtualenv/lib/python3.6/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/usr/local/pyenv/versions/3.6.9/envs/node_virtualenv/lib/python3.6/site-packages/common/utils.py", line 88, in get_asg_name
    raise CriticalError("Unable to get ASG for stack {0}. Failed with exception: {1}".format(stack_name, e))
common.utils.CriticalError: Unable to get ASG for stack parallelcluster-hpcbioinf-dev. Failed with exception: An error occurred (SignatureDoesNotMatch) when calling the DescribeTags operation: Signature expired: 20200917T130119Z is now earlier than 20200917T150155Z (20200917T150655Z - 5 min.)
```

**Comment by lukeseawalker** [comment]
Hi @joeydumont,
it is likely that the time drift is the root cause here.

Are you sure that chrony daemon was up and running when you had the issue?

We recently discovered a problem in the start of the chrony daemon, due to the fact that the restart command defined in the service configuration of the chrony service is not checking if the process is stopped before starting the new one, causing the new process to not being able to start in same cases.
It's difficult to say this is what was causing your issue, since, as you said, it's not possible to retrieve logs from previous boot.

If this is going to happen again, can you please do the following:
* verify if service is actually running with `systemctl status chronyd`
* verify if service is correctly configured with `chronyc tracking`. The output should contain a `Reference ID` pointing to the `169.254.169.123`

Thanks
L

**Comment by joeydumont** [comment]
Thanks, I'll look for the service file definition and fix it.
