### ISSUE TITLE
Upgrade to 2.10.0: Unknown parameter in NetworkInterfaces

### ISSUE THREAD

**Issue by cread** [aws/aws-parallelcluster#2251]
**Required Info:**
 - AWS ParallelCluster version [e.g. 2.9.0]: 2.10.0
 - Full cluster configuration without any credentials or personal data

```
[cluster default]
key_name = xxx
base_os = ubuntu1804
scheduler = slurm
master_instance_type = r5n.2xlarge
master_root_volume_size = 50
encrypted_ephemeral = true
vpc_settings = default
queue_settings = compute

[vpc default]
vpc_id = vpc-xxx
master_subnet_id = subnet-xxx
use_public_ips = false

[queue compute]
compute_type = spot
enable_efa = false
disable_hyperthreading = true
compute_resource_settings = r5n4

[compute_resource r5n4]
instance_type = r5n.4xlarge
min_count = 0
max_count = 32
```

 - Cluster name: slurm-bug
 - [Optional] Arn of the cluster CloudFormation main stack:

**Bug description and how to reproduce:**
Simply try to create a cluster with the above config. Fails with:

```
$ pcluster create -c cluster_bug.conf slurm-bug
Beginning cluster creation for cluster: slurm-bug
Unexpected error of type ParamValidationError: Parameter validation failed:
Unknown parameter in NetworkInterfaces[0]: "NetworkCardIndex", must be one of: AssociatePublicIpAddress, DeleteOnTermination, Description, DeviceIndex, Groups, Ipv6AddressCount, Ipv6Addresses, NetworkInterfaceId, PrivateIpAddress, PrivateIpAddresses, SecondaryPrivateIpAddressCount, SubnetId, AssociateCarrierIpAddress, InterfaceType
Traceback (most recent call last):
  File "/xxx/lib/python3.8/site-packages/pcluster/cli.py", line 467, in main
    args.func(args)
  File "/xxx/lib/python3.8/site-packages/pcluster/cli.py", line 38, in create
    pcluster.create(args)
  File "/xxx/lib/python3.8/site-packages/pcluster/commands.py", line 209, in create
    pcluster_config.validate()
  File "/xxx/lib/python3.8/site-packages/pcluster/config/pcluster_config.py", line 495, in validate
    self.__test_configuration()
  File "/xxx/lib/python3.8/site-packages/pcluster/config/pcluster_config.py", line 551, in __test_configuration
    self.cluster_model.test_configuration(self)
  File "/xxx/lib/python3.8/site-packages/pcluster/models/hit/hit_cluster_model.py", line 87, in test_configuration
    self._ec2_run_instance(
  File "/xxx/lib/python3.8/site-packages/pcluster/cluster_model.py", line 66, in _ec2_run_instance
    boto3.client("ec2").run_instances(**kwargs)
  File "/xxx/lib/python3.8/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/xxx/lib/python3.8/site-packages/botocore/client.py", line 607, in _make_api_call
    request_dict = self._convert_to_request_dict(
  File "/xxx/lib/python3.8/site-packages/botocore/client.py", line 655, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
  File "/xxx/lib/python3.8/site-packages/botocore/validate.py", line 297, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Unknown parameter in NetworkInterfaces[0]: "NetworkCardIndex", must be one of: AssociatePublicIpAddress, DeleteOnTermination, Description, DeviceIndex, Groups, Ipv6AddressCount, Ipv6Addresses, NetworkInterfaceId, PrivateIpAddress, PrivateIpAddresses, SecondaryPrivateIpAddressCount, SubnetId, AssociateCarrierIpAddress, InterfaceType
```

**Comment by rexcsn** [comment]
Hi,

I suspect this is because you are using an older version of Boto3, please try to upgrade to the latest version of Boto3 with `pip install boto3 --upgrade`

Thank you.

**Comment by cread** [comment]
You suspected correctly! Thanks for the quick reply.

I was still on a 1.14.x release. I now see that the requirements do specify:
```
boto3>=1.16.14
```

**Comment by rexcsn** [comment]
Hi @cread ,

Great!
Did you install 2.10.0 from pypi? Just trying to see if there is an issue with our dependency requirements

**Comment by cread** [comment]
I installed from conda-forge. I'm working on a PR now for them.

**Comment by enrico-usai** [comment]
Thanks Chris for creating the patch in conda-forge repo!
