### ISSUE TITLE
Version mismatch with chef and seven_zip

### ISSUE THREAD

**Issue by 91bsjun** [aws/aws-parallelcluster#2706]
- AWS ParallelCluster version : 2.0.2

Can I assign the version of specific cookbook?
or can I update chef in master node?

<pre>
[2021-05-04T04:26:30+00:00] WARN: Overridden Run List: [recipe[aws-parallelcluster::_prep_env]]
resolving cookbooks for run list: ["aws-parallelcluster::_prep_env"]
Synchronizing Cookbooks:
  - aws-parallelcluster (2.0.2)
  - build-essential (8.1.1)
  - tar (2.1.1)
  - poise-python (1.7.0)
  - selinux (2.1.1)
  - nfs (2.5.1)
  - sysctl (1.0.5)
  - yum (5.1.0)
  - yum-epel (3.1.0)
  - openssh (2.6.3)
  - apt (7.0.0)
  - hostname (0.4.2)
  - line (1.0.6)
  - seven_zip (4.0.0)
  - mingw (2.1.1)
  - poise (2.8.2)
  - poise-languages (2.1.2)
  - ohai (5.3.0)
  - iptables (7.1.0)
  - hostsfile (3.0.1)
  - poise-archive (1.5.0)

Running handlers:
[2021-05-04T04:26:31+00:00] ERROR: Running exception handlers
[2021-05-04T04:26:31+00:00] ERROR: Running exception handlers
Running handlers complete
[2021-05-04T04:26:31+00:00] ERROR: Exception handlers complete
[2021-05-04T04:26:31+00:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 15 seconds
[2021-05-04T04:26:31+00:00] FATAL: Stacktrace dumped to /etc/chef/local-mode-cache/cache/chef-stacktrace.out
[2021-05-04T04:26:31+00:00] FATAL: Stacktrace dumped to /etc/chef/local-mode-cache/cache/chef-stacktrace.out
[2021-05-04T04:26:31+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2021-05-04T04:26:31+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2021-05-04T04:26:31+00:00] FATAL: Chef::Exceptions::CookbookChefVersionMismatch: Cookbook 'seven_zip' version '4.0.0' depends on chef version [">= 16.0"], but the running chef version is 14.2.0
[2021-05-04T04:26:31+00:00] FATAL: Chef::Exceptions::CookbookChefVersionMismatch: Cookbook 'seven_zip' version '4.0.0' depends on chef version [">= 16.0"], but the running chef version is 14.2.0

2021-05-04 04:26:31,685 [ERROR] Error encountered during build of chefPrepEnv: Command chef failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 542, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 260, in build
    changes['commands'] = CommandTool().apply(self._config.commands)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/command_tool.py", line 117, in apply
    raise ToolError(u"Command %s failed" % name)
ToolError: Command chef failed
2021-05-04 04:26:31,687 [ERROR] -----------------------BUILD FAILED!------------------------
2021-05-04 04:26:31,687 [ERROR] Unhandled exception during build: Command chef failed
Traceback (most recent call last):
  File "/bin/cfn-init", line 171, in <module>
    worklog.build(metadata, configSets)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 129, in build
    Contractor(metadata).build(configSets, self)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 530, in build
    self.run_config(config, worklog)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 542, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 260, in build
    changes['commands'] = CommandTool().apply(self._config.commands)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/command_tool.py", line 117, in apply
    raise ToolError(u"Command %s failed" % name)
ToolError: Command chef failed
2021-05-04 04:26:31,796 [DEBUG] CloudFormation client initialized with endpoint https://cloudformation.us-east-2.amazonaws.com
2021-05-04 04:26:31,796 [DEBUG] Signaling resource ComputeFleet in stack parallelcluster-CMShpc with unique ID i-0f0e72a2245c876be and status FAILURE
</pre>

**Comment by rexcsn** [comment]
Hi @91bsjun ,

Seems like you are using a very old version of the product, v2.0.2. We strongly recommend upgrading to the latest version which is v2.10.3.
The issue is caused by a change in the cookbook dependency. We start to manage third party packages in our own cookbook since v2.8.0, so versions >= 2.8.0 would not have experienced this problem.

Not recommended, but if you have to unblock the issue for earlier version, you would need to modify the cookbook code and use a custom cookbook.
You will need to add `depends 'seven_zip', '~> 3.2.0'` to `metadata.rb` to pin to an earlier version of `seven_zip` package, and use the custom cookbook to create a cluster following [this guide](https://docs.aws.amazon.com/parallelcluster/latest/ug/custom_cookbook.html)

Thanks.

**Comment by 91bsjun** [comment]
Thank you @rexcsn .
It's time to update my grandpa HPC.. :)
