### ISSUE TITLE
Compute nodes are scaling but qhost show nothing

### ISSUE THREAD

**Issue by mukulagrawal78** [aws/aws-parallelcluster#3133]
Hi,
I ran into a puzzling issue and I am looking for some guidance on where to starting debugging.

I am using pcluster 2.11.0, ubuntu 20.04, custom AMI built on top of the published AMI, SGE scheduler.
submitted a job using qsub. AWS console shows nodes come up just fine but qhost shows zero nodes. qstate shows job hanging in qw state. I see no problems in cloud-init, cfn-init, or chef. Everything looks good. AWS cloudformation console does not show any errors and shows stack completion successful.

Seems like some kind of queue setup issue to me. Are the jobs going into wrong queue and cluster is scaling in response to some other queue?

Any pointers?

**Comment by mukulagrawal78** [comment]
**SQSWatcher** is showing some errors on log:

2021-08-16 16:33:07,271 INFO [transport:_log] Authentication (publickey) failed.
2021-08-16 16:33:07,273 ERROR [transport:_log] Unknown exception: q must be exactly 160, 224, or 256 bits long
2021-08-16 16:33:07,275 ERROR [transport:_log] Traceback (most recent call last):
2021-08-16 16:33:07,275 ERROR [transport:_log]   File "/opt/parallelcluster/pyenv/versions/3.7.10/envs/node_virtualenv/lib/python3.7/site-packages/paramiko/transport.py", line 2109, in run
2021-08-16 16:33:07,275 ERROR [transport:_log]     handler(self.auth_handler, m)
2021-08-16 16:33:07,275 ERROR [transport:_log]   File "/opt/parallelcluster/pyenv/versions/3.7.10/envs/node_virtualenv/lib/python3.7/site-packages/paramiko/auth_handler.py", line 298, in _parse_service_accept
2021-08-16 16:33:07,275 ERROR [transport:_log]     sig = self.private_key.sign_ssh_data(blob)
2021-08-16 16:33:07,275 ERROR [transport:_log]   File "/opt/parallelcluster/pyenv/versions/3.7.10/envs/node_virtualenv/lib/python3.7/site-packages/paramiko/dsskey.py", line 116, in sign_ssh_data
2021-08-16 16:33:07,275 ERROR [transport:_log]     ).private_key(backend=default_backend())
2021-08-16 16:33:07,275 ERROR [transport:_log]   File "/opt/parallelcluster/pyenv/versions/3.7.10/envs/node_virtualenv/lib/python3.7/site-packages/cryptography/hazmat/primitives/asymmetric/dsa.py", line 244, in private_key
2021-08-16 16:33:07,275 ERROR [transport:_log]     return backend.load_dsa_private_numbers(self)
2021-08-16 16:33:07,275 ERROR [transport:_log]   File "/opt/parallelcluster/pyenv/versions/3.7.10/envs/node_virtualenv/lib/python3.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 826, in load_dsa_private_numbers
2021-08-16 16:33:07,275 ERROR [transport:_log]     dsa._check_dsa_private_numbers(numbers)
2021-08-16 16:33:07,275 ERROR [transport:_log]   File "/opt/parallelcluster/pyenv/versions/3.7.10/envs/node_virtualenv/lib/python3.7/site-packages/cryptography/hazmat/primitives/asymmetric/dsa.py", line 282, in _check_dsa_private_numbers
2021-08-16 16:33:07,275 ERROR [transport:_log]     _check_dsa_parameters(parameters)
2021-08-16 16:33:07,275 ERROR [transport:_log]   File "/opt/parallelcluster/pyenv/versions/3.7.10/envs/node_virtualenv/lib/python3.7/site-packages/cryptography/hazmat/primitives/asymmetric/dsa.py", line 274, in _check_dsa_parameters
2021-08-16 16:33:07,275 ERROR [transport:_log]     raise ValueError("q must be exactly 160, 224, or 256 bits long")
2021-08-16 16:33:07,275 ERROR [transport:_log] ValueError: q must be exactly 160, 224, or 256 bits long
2021-08-16 16:33:07,275 ERROR [transport:_log]
2021-08-16 16:33:07,276 ERROR [remote_command_executor:__init__] Failed when connecting to host ip-172-30-0-208 with error: q must be exactly 160, 224, or 256 bits long
2021-08-16 16:33:07,276 ERROR [remote_command_executor:_pickable_run_remote_command] Failed when executing remote command on node ip-172-30-0-208 with error q must be exactly 160, 224, or 256 bits long
"sqswatcher" 661L, 79571C


**CloudWatch Logs** show some errors


2021-08-16T17:27:35Z W! [outputs.cloudwatchlogs] Retried 115 time, going to sleep 33.362479147s before retrying.
2021-08-16T17:27:38Z E! [outputs.cloudwatchlogs] Aws error received when sending logs to /aws/parallelcluster/df0c2b3e/ip-172-30-0-137.i-0beae3b20baa7eb91.sge-qmaster: AccessDeniedException: User: arn:aws:sts::912971501471:assumed-role/parallelcluster-df0c2b3e-RootRole-1XOHVCR5MQ52U/i-0beae3b20baa7eb91 is not authorized to perform: logs:PutLogEvents on resource: arn:aws:logs:us-west-2:912971501471:log-group:/aws/parallelcluster/df0c2b3e:log-stream:ip-172-30-0-137.i-0beae3b20baa7eb91.sge-qmaster
        status code: 400, request id: 373ef461-b4b4-435c-ba23-fd594cafaf62

**Comment by chenwany** [comment]
Hi,
From the question you mentioned about:
```
Seems like some kind of queue setup issue to me. Are the jobs going into wrong queue and cluster is scaling in response to some other queue?
```
Parallelcluster doesn’t support multiple queues for SGE. Multiple queues is supported only for Slurm scheduler. Could you share with us the configuration of creating the cluster?
```
I am using pcluster 2.11.0, ubuntu 20.04, custom AMI built on top of the published AMI, SGE scheduler.
```
Could you share us the way you build custom AMI from published AMI? Here is our documentation: https://docs.aws.amazon.com/parallelcluster/latest/ug/tutorials_02_ami_customization.html

From SQSWatcher log, seems ssh can not establish connection to the compute nodes
```
2021-08-16 16:33:07,271 INFO [transport:_log] Authentication (publickey) failed.
2021-08-16 16:33:07,273 ERROR [transport:_log] Unknown exception: q must be exactly 160, 224, or 256 bits long
```
From CloudWatch Logs, seems iam role lacks the permission of logs:PutLogEvents, do you use custom IAM role that may lack some permissions?

Thank you!

**Comment by mukulagrawal78** [comment]
@chenwany 
`Parallelcluster doesn’t support multiple queues for SGE. Multiple queues is supported only for Slurm scheduler. Could you share with us the configuration of creating the cluster?`

Sorry for confusion. We dont do any custom SGE configuration. We tries to use SGE out of the box. I was just thinking loud about what may be going worng. Do I need to do any custom config of SGE --- placing users in specific queue or anything like that?

```
Could you share us the way you build custom AMI from published AMI? Here is our documentation: https://docs.aws.amazon.com/parallelcluster/latest/ug/tutorials_02_ami_customization.html
```
Yes, thats exactly what we did. My custom ami ID is: ami-096dfb2e80ae2b833. We fired a new instance from ami-03bb77caf81b15cc5. Installed a a bunch of software and utilities. Saved new AMI ami-096dfb2e80ae2b833.
Thats about it.

`From SQSWatcher log, seems ssh can not establish connection to the compute nodes`
We do some /etc/ssh/ssh_config modifications. May be this is the problem. We concatenated our changes on top what was already there in the AMI. Do you do any runtime ssh config that our modifications may be breaking? Can you give some guidance of what needs to stay in ssh config?

`From CloudWatch Logs, seems iam role lacks the permission of logs:PutLogEvents, do you use custom IAM role that may lack some permissions?
`

This one is really puzzling to me. The user that creates cluster has the AdministratorAccess policy attached. Beyond that we let pcluster create any IAM roles that are needed. We are not changing anything there. Any idea how this can this fail? Is this only needed for CloudWatch monitoring or is it also essential for pcluster to function properly?

Is there any other place I should look further to debug this ?

**Comment by chenwany** [comment]
Hi,
Thanks for your confirmation on SGE settings!
```
We do some /etc/ssh/ssh_config modifications. May be this is the problem. We concatenated our changes on top what was already there in the AMI. Do you do any runtime ssh config that our modifications may be breaking? Can you give some guidance of what needs to stay in ssh config?
```
For ssh access, we modifying something of ssh access to make sure all compute nodes are able to communicate with headnode without SSH passwords. There are some runtime ssh config during cluster creation, not during ami creation,
Here's our codes on configuring headnode ssh during cluster creation:
https://github.com/aws/aws-parallelcluster-cookbook/blob/3045850a8f62c667bf47fd5d865a4e8849dd4459/recipes/head_node_base_config.rb#:~:text=%23%20Setup%20SSH%20auth%20for%20cluster%20user
Here is a sample of my ssh config in the headnode:
```
[ec2-user@ip-172-31-7-196 ~]$ cat /etc/ssh/ssh_config
# This file was generated by Chef
# Do NOT modify this file by hand!

Host *
UseRoaming no
GssapiAuthentication yes
Match exec "ssh_target_checker.sh %h"
  StrictHostKeyChecking no
  UserKnownHostsFile /dev/null
```
Could you share with us what customers do on customization ssh_config?

For the custom ami, customers are installing a bunch of software and utilities. It is also recommend to use post-install script to install what customers need to avoid introduce something to break cluster setup. See here for post_install script: https://docs.aws.amazon.com/parallelcluster/latest/ug/cluster-definition.html#post-install

For cloudwatch log problem, I am not sure about it now. Could you share me with the logs and configuration file? 
Thanks!

**Comment by mukulagrawal78** [comment]
@chenwany thanks for the reply. I compared the ssh config, and this looks fine as above. I have a question: once cluster is up, are other linux users that are configured on the master node able to submit jobs to SGE or is the cluster configured such that only "ubuntu" user is able to use SGE queue?

I will collect config and logs and send later.

**Comment by mukulagrawal78** [comment]
Hello folks,
I was able to resolve this. Thanks for your help. 
Before I close the ticket, just 2 clarifications for my understanding. Could you please conform if following is correct.

1/ It seems to me that previously in cfn 1.6.* versions sqswatcher did not need ssh, but now sqswatcher is failing if ssh keys are not available. Is this correct?
2/ It seems to me that Grid Engine, as setup in parallelcluster, does not really use ssh. Its the sqswatcher that needs ssh. Correct? If I manually add nodes to the queue, qsub, qstat, qhost everything works just fine even though ssh was broken.
