### ISSUE TITLE
chef error during parallelcluster deployment

### ISSUE THREAD

**Issue by hsimran13** [aws/aws-parallelcluster#3364]
Hello,

I am trying to deploy parallelcluster but the cloudformation stack is failing.  Was hoping someone can help me figure out the issue with chef:

$ pcluster version
{
  "version": "3.0.0"
}

Created a new custom AMI by running:
pcluster build-image --image-id ParallelCluster-3-0-ubuntu2004 --image-configuration image-config-pcluster.yaml --region us-west-2
$ pcluster list-images --region us-west-2 --image-status AVAILABLE
{
  "images": [
    {
      "imageId": "ParallelCluster-3-0-ubuntu2004",
      "imageBuildStatus": "BUILD_COMPLETE",
      "ec2AmiInfo": {
        "amiId": "ami-xxx"
      },
      "region": "us-west-2",
      "version": "3.0.0"
    }
  ]
}

Created a config for pcluster:
$ ls -l cluster-config.yaml
-rw-------  1 simran  staff  5589 Oct 19 16:48 cluster-config.yaml

Deploying the cluster using:
$ pcluster create-cluster --cluster-name simtest-cluster --cluster-configuration cluster-config.yaml
{
  "cluster": {
    "clusterName": "simtest-cluster",
    "cloudformationStackStatus": "CREATE_IN_PROGRESS",
    "cloudformationStackArn": "arn:aws:cloudformation:us-west-2:xxx:stack/simtest-cluster/29f076f0-3137-11ec-b247-02ca360f9713",
    "region": "us-west-2",
    "version": "3.0.0",
    "clusterStatus": "CREATE_IN_PROGRESS"
  },
  "validationMessages": [
    {
      "level": "WARNING",
      "type": "UrlValidator",
      "message": "The url 'https://10.x.x.x/pcluster-setup.sh' causes URLError, the error reason is '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1125)'."
    }
  ]
}

Cloudformation fails with this message:
WaitCondition received failed message: 'Failed to run cfn-init. If --norollback was specified, check /var/log/cfn-init.log and /var/log/cloud-init-output.log.' for uniqueId: i-02ffc3d49d1a82e8f

I logged into the head node during deployment and see the following in /var/log/cfn-init.log:
2021-10-19 23:56:18,716 [DEBUG] No test for command chef
2021-10-19 23:57:09,041 [ERROR] Command chef (chef-client --local-mode --config /etc/chef/client.rb --log_level info --logfile /var/log/chef-client.log --force-formatter --no-color --chef-zero-port 8889 --json-attributes /etc/chef/dna.json) failed
2021-10-19 23:57:09,041 [DEBUG] Command chef output: Redirecting to cinc-client

2021-10-19 23:57:09,041 [ERROR] Error encountered during build of chefConfig: Command chef failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/cfnbootstrap/construction.py", line 573, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/local/lib/python3.8/dist-packages/cfnbootstrap/construction.py", line 272, in build
    changes['commands'] = CommandTool().apply(
  File "/usr/local/lib/python3.8/dist-packages/cfnbootstrap/command_tool.py", line 127, in apply
    raise ToolError(u"Command %s failed" % name)
cfnbootstrap.construction_errors.ToolError: Command chef failed
2021-10-19 23:57:09,044 [ERROR] -----------------------BUILD FAILED!------------------------
2021-10-19 23:57:09,044 [ERROR] Unhandled exception during build: Command chef failed
Traceback (most recent call last):
  File "/usr/local/bin/cfn-init", line 176, in <module>
    worklog.build(metadata, configSets)
  File "/usr/local/lib/python3.8/dist-packages/cfnbootstrap/construction.py", line 135, in build
    Contractor(metadata).build(configSets, self)
  File "/usr/local/lib/python3.8/dist-packages/cfnbootstrap/construction.py", line 561, in build
    self.run_config(config, worklog)
  File "/usr/local/lib/python3.8/dist-packages/cfnbootstrap/construction.py", line 573, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/local/lib/python3.8/dist-packages/cfnbootstrap/construction.py", line 272, in build
    changes['commands'] = CommandTool().apply(
  File "/usr/local/lib/python3.8/dist-packages/cfnbootstrap/command_tool.py", line 127, in apply
    raise ToolError(u"Command %s failed" % name)
cfnbootstrap.construction_errors.ToolError: Command chef failed

**Comment by hsimran13** [comment]
This seems to have been related to the IAM role missing access.  I was able to resolve this issue by using the pcluster provided instance role/policies.
