### ISSUE TITLE
cfncluster compute node not scaling down

### ISSUE THREAD

**Issue by rmilne** [aws/aws-parallelcluster#339]
I have an issue where the first job submitted to SGE in a cfncluster with an initial size of 0 will trigger one node to scale up, then a second node to scale up.  This first node does not seem to  scale down after, even long after the instance hour is up and the SGE queue is empty.

Here's an overview of the scaling group activity history:  Notice node i-0fb665a4dd31296e3 was not scaled down.

```
| Successful | Terminating EC2 instance: i-06bc2389f007ca8a7 | 2018 March 22 10:49:31 UTC-5 | 2018 March 22 10:50:15 UTC-5
  | Successful | Launching a new EC2 instance: i-06bc2389f007ca8a7 | 2018 March 22 07:51:48 UTC-5 | 2018 March 22 07:52:50 UTC-5
  | Successful | Terminating EC2 instance: i-0a6dcbe65db339dc4 | 2018 March 21 22:01:52 UTC-5 | 2018 March 21 22:02:35 UTC-5
  | Successful | Launching a new EC2 instance: i-0a6dcbe65db339dc4 | 2018 March 21 20:03:51 UTC-5 | 2018 March 21 20:04:52 UTC-5
  | Successful | Launching a new EC2 instance: i-0fb665a4dd31296e3 | 2018 March 21 19:51:38 UTC-5 | 2018 March 21 19:52:40 UTC-5
```

Two node are likely being spun up because of the initial time to start up a node, I've increased scaling_cooldown to 600, but I will try longer.  I don't think that will solve this issue though.  Relevant settings for this issue are:

```
initial_queue_size = 0
maintain_initial_size = false
max_queue_size = 16
```

sqswatcher logs from master node:
```
2018-03-21 21:19:20,336 INFO [sqswatcher:pollQueue] eventType=autoscaling:EC2_INSTANCE_TERMINATE
2018-03-21 21:19:20,336 INFO [sqswatcher:pollQueue] instanceId=i-0336d5c921a800d52
2018-03-21 21:19:20,371 ERROR [sqswatcher:pollQueue] Did not find i-0336d5c921a800d52 in the metadb

2018-03-22 01:07:01,037 INFO [sqswatcher:pollQueue] eventType=cfncluster:COMPUTE_READY
2018-03-22 01:07:01,037 INFO [sqswatcher:pollQueue] instanceId=i-0a6dcbe65db339dc4
2018-03-22 01:07:01,111 INFO [sqswatcher:pollQueue] Adding Hostname: [Reservation:r-0917530e351bd0948]
2018-03-22 01:07:01,111 INFO [sge:addHost] Adding ip-172-31-61-168 with 35 slots
ip-172-31-61-168.ec2.internal added to administrative host list
ip-172-31-61-168.ec2.internal added to submit host list
root@ip-172-31-57-85.ec2.internal added "ip-172-31-61-168.ec2.internal" to exechost list
2018-03-22 01:07:01,140 INFO [sge:addHost] Connecting to host: ip-172-31-61-168 iter: 0
2018-03-22 01:07:01,160 INFO [transport:_log] Connected (version 2.0, client OpenSSH_7.2p2)
2018-03-22 01:07:01,220 INFO [transport:_log] Authentication (publickey) successful!
root@ip-172-31-57-85.ec2.internal modified "@allhosts" in host group list
root@ip-172-31-57-85.ec2.internal modified "all.q" in cluster queue list
2018-03-22 03:02:53,616 INFO [sqswatcher:pollQueue] eventType=autoscaling:EC2_INSTANCE_TERMINATE
2018-03-22 03:02:53,616 INFO [sqswatcher:pollQueue] instanceId=i-0a6dcbe65db339dc4
2018-03-22 03:02:53,657 INFO [sge:removeHost] Removing ip-172-31-61-168
root@ip-172-31-57-85.ec2.internal removed "ip-172-31-61-168.ec2.internal" from administrative host list
root@ip-172-31-57-85.ec2.internal modified "all.q" in cluster queue list
root@ip-172-31-57-85.ec2.internal modified "@allhosts" in host group list
root@ip-172-31-57-85.ec2.internal removed "ip-172-31-61-168.ec2.internal" from execution host list
root@ip-172-31-57-85.ec2.internal removed "ip-172-31-61-168.ec2.internal" from submit host list
2018-03-22 12:55:38,740 INFO [sqswatcher:pollQueue] eventType=cfncluster:COMPUTE_READY
2018-03-22 12:55:38,741 INFO [sqswatcher:pollQueue] instanceId=i-06bc2389f007ca8a7
2018-03-22 12:55:38,831 INFO [sqswatcher:pollQueue] Adding Hostname: [Reservation:r-0d35ff94132854e48]
2018-03-22 12:55:38,832 INFO [sge:addHost] Adding ip-172-31-62-87 with 35 slots
ip-172-31-62-87.ec2.internal added to administrative host list
ip-172-31-62-87.ec2.internal added to submit host list
root@ip-172-31-57-85.ec2.internal added "ip-172-31-62-87.ec2.internal" to exechost list
2018-03-22 12:55:38,864 INFO [sge:addHost] Connecting to host: ip-172-31-62-87 iter: 0
2018-03-22 12:55:38,903 INFO [transport:_log] Connected (version 2.0, client OpenSSH_7.2p2)
2018-03-22 12:55:38,993 INFO [transport:_log] Authentication (publickey) successful!
root@ip-172-31-57-85.ec2.internal modified "@allhosts" in host group list
root@ip-172-31-57-85.ec2.internal modified "all.q" in cluster queue list
2018-03-22 15:50:41,165 INFO [sqswatcher:pollQueue] eventType=autoscaling:EC2_INSTANCE_TERMINATE
2018-03-22 15:50:41,165 INFO [sqswatcher:pollQueue] instanceId=i-06bc2389f007ca8a7
2018-03-22 15:50:41,202 INFO [sge:removeHost] Removing ip-172-31-62-87
root@ip-172-31-57-85.ec2.internal removed "ip-172-31-62-87.ec2.internal" from administrative host list
root@ip-172-31-57-85.ec2.internal modified "all.q" in cluster queue list
root@ip-172-31-57-85.ec2.internal modified "@allhosts" in host group list
root@ip-172-31-57-85.ec2.internal removed "ip-172-31-62-87.ec2.internal" from execution host list
root@ip-172-31-57-85.ec2.internal removed "ip-172-31-62-87.ec2.internal" from submit host list
2018-03-22 16:46:20,531 INFO [sqswatcher:pollQueue] eventType=autoscaling:EC2_INSTANCE_TERMINATE
2018-03-22 16:46:20,531 INFO [sqswatcher:pollQueue] instanceId=i-0fb665a4dd31296e3
2018-03-22 16:46:20,561 ERROR [sqswatcher:pollQueue] Did not find i-0fb665a4dd31296e3 in the metadb
```

I manually changed the scaling group desired instances from 1 to 0 via the AWS console to remove i-0fb665a4dd31296e3

It looks like sqswatcher did not see any COMPUTE_READY from i-0fb665a4dd31296e3

Update edit:   It happened again today and I logged into the node in question.  Nodewatcher was not running at all, there were errors in the cfn and cloud init logs, for example:

```
2018-03-23 12:53:29,137 - util.py[DEBUG]: Running command ['/var/lib/cloud/instance/scripts/part-002'] with allowed return codes [0] (shell=False, capture=False)
2018-03-23 12:54:51,503 - util.py[WARNING]: Failed running /var/lib/cloud/instance/scripts/part-002 [1]
2018-03-23 12:54:51,503 - util.py[DEBUG]: Failed running /var/lib/cloud/instance/scripts/part-002 [1]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cloudinit/util.py", line 806, in runparts
    subp(prefix + [exe_path], capture=False)
  File "/usr/lib/python3/dist-packages/cloudinit/util.py", line 1847, in subp
    cmd=args)
cloudinit.util.ProcessExecutionError: Unexpected error while running command.
Command: ['/var/lib/cloud/instance/scripts/part-002']
Exit code: 1
Reason: -
Stdout: -
Stderr: -
2018-03-23 12:54:51,504 - cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
2018-03-23 12:54:51,504 - handlers.py[DEBUG]: finish: modules-final/config-scripts-user: FAIL: running config-scripts-user with frequency once-per-instance
2018-03-23 12:54:51,504 - util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py'>) failed
2018-03-23 12:54:51,504 - util.py[DEBUG]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py'>) failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cloudinit/stages.py", line 793, in _run_modules
    freq=freq)
  File "/usr/lib/python3/dist-packages/cloudinit/cloud.py", line 54, in run
    return self._runners.run(name, functor, args, freq, clear_on_fail)
  File "/usr/lib/python3/dist-packages/cloudinit/helpers.py", line 188, in run
    return (True, results)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3/dist-packages/cloudinit/helpers.py", line 76, in lock
    yield self._acquire(name, freq)
  File "/usr/lib/python3/dist-packages/cloudinit/helpers.py", line 187, in run
    results = functor(*args)
  File "/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py", line 45, in handle
    util.runparts(runparts_path)
  File "/usr/lib/python3/dist-packages/cloudinit/util.py", line 813, in runparts
    % (len(failed), len(attempted)))
RuntimeError: Runparts: 1 failures in 1 attempted commands
```

**Comment by rajachan** [comment]
@rmilne - From your sqswatcher log snippet, it looks like it could not find the hostname that corresponds to `i-0fb665a4dd31296e3` from the DynamoDB table that CfnCluster maintains for it to be able to remove it from the scheduler. This could have happened only if an instance did not publish a COMPUTE_READY message to begin with. This message is published as part of compute instance startup, using a [compute_ready](https://github.com/awslabs/cfncluster-cookbook/blob/e3f93c1396dbb223dd507b6388b0df89c12cb13b/files/default/compute_ready) helper script within the instance. 

That aside, nodewatcher is the actual component that would terminate a compute instance, so that not running is the core problem here.  You can look at the contents of `/var/log/nodewatcher` on that compute instance to see if you can find any hints of why the watcher failed.

**Comment by rmilne** [comment]
@rajachan  - Yes, sorry I didn't update this thread earlier I made a post in the forum:  https://forums.aws.amazon.com/thread.jspa?threadID=277995&tstart=0

After looking at the logs on a "Failed" compute node like this one, while the system is initializing with chef and the cfncluster cookbook it runs into a problem running the "berk" command with a timeout exception.  From there the system never sends COMPUTE_READY and there's no detection of this failure by cfncluster, so the scaling group's desired nodes count is X+1 until manually changed back down (where X is the number before the failure).

**Comment by rmilne** [comment]
I believe these start up issues are causing nodes to be spun up and when nodewatcher never starts these nodes will never shut themselves down.

This morning there were 7 Compute nodes running when I checked, only one had registered itself with the Master node.  With c5.9xlarge instances, this a fairly decent waste of money per hour.  I believe there needs to be some management of startup issues in the Master node so this does not happen.

**Comment by bwbarrett** [comment]
From the forum post @rmilne referenced, Berk is failing due to some transient network issue.  Berk itself has retries, so I'm not sure there's much we can do to try and recover from said transient network issue.  It was long enough that the underlying retry structure gave up.

That being said, leaving the node up and running after initialization failed is poor behavior we need to fix.  We probably need a debugging parameter to the cloudformation template to control this behavior (so that debugging custom AMI builds and the like doesn't become impossible), but we should never leave defunct instances running.  I've tagged this issue as a blocking bug for the next release.

**Comment by krogebry** [comment]
I've seen this happen in different contexts with anything that requires a 3rd party resource.  Sometimes it's gemfiles, sometimes it's packages for the system and sometimes it's resources that chef tries to pull down.  At any rate, the solution is to usually isolate the remote resources and do 1 of 2 things:

1) (best case): refactor the code to pull the resource down from a "local" s3 bucket.
2) Bake the requirement directly to the AMI.

Option 2 usually requires more mechanics around baking AMI pipelines as well as tuning to the chef bits for a more idempotent state.

**Comment by krogebry** [comment]
One last note on this, aside from those two options mentioned above, there really isn't anything that I've found that will absolutely prevent the occasional network blip.  In most cases we just terminate the instance and get a fresh resource.  Looking forward to seeing how that plays out with a HPC cluster. ;)
