### ISSUE TITLE
HeadNodeWaitCondition timeout during cluster creation

### ISSUE THREAD

**Issue by srdecny** [aws/aws-parallelcluster#3604]
I am trying to create a ParallelCluster instance using pcluster3 with `pcluster create-cluster --cluster-name ssd-cluster --cluster-configuration pcluster.yaml --rollback-on-failure false`. However, after ~20 or more minutes the creation fails (due to a timeout), and the following error messages can be seen in CloudFormation: `The following resource(s) failed to create: [20211214193014].` and `WaitCondition timed out. Received 0 conditions when expecting 1`. The config is copied from the required example one in this repo, just with FSx and monitoring added.

**Required Info:**
 pcluster version:  3.0.2
Cluster config (`pcluster.yaml`):
```
Image:
  Os: ubuntu2004
HeadNode:
  InstanceType: m5n.xlarge
  Networking:
    SubnetId: <SUBNET_ID>
  Ssh:
    KeyName: <KEY_NAME>
Scheduling:
  Scheduler: slurm
  SlurmQueues:
    - Name: queue1
      Networking:
        SubnetIds:
          - <SUBNET_ID>
      ComputeResources:
        - Name: compute-resource1
          InstanceType: c5.2xlarge
SharedStorage:
  - MountDir: /fsx
    Name: ssd-fsx
    StorageType: FsxLustre
    FsxLustreSettings:
      StorageCapacity: 1200
      DeploymentType: PERSISTENT_1
      StorageType: SSD
      PerUnitStorageThroughput: 50
Monitoring:
  DetailedMonitoring: false
  Logs:
    CloudWatch:
      Enabled: true
      RetentionInDays: 30
      DeletionPolicy: Retain
  Dashboards:
    CloudWatch:
      Enabled: true
```

After this failure, I ssh'd into the head node to retrieve the logs, but I do not find much.

`/var/log/cfn-init.log` contains the following:
```
2021-12-14 19:45:08,617 [DEBUG] CloudFormation client initialized with endpoint https://cloudformation.us-east-1.amazonaws.com
2021-12-14 19:45:08,618 [DEBUG] Describing resource HeadNodeLaunchTemplate in stack ssd-cluster
2021-12-14 19:46:08,618 [WARNING] Timeout of 60 seconds breached
2021-12-14 19:46:08,618 [ERROR] Client-side timeout
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/cfnbootstrap/util.py", line 189, in _retry
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/cfnbootstrap/util.py", line 262, in _timeout
    raise TimeoutError(
cfnbootstrap.util.TimeoutError
2021-12-14 19:46:08,618 [DEBUG] Sleeping for 0.995217 seconds before retrying
2021-12-14 19:46:09,615 [DEBUG] Describing resource HeadNodeLaunchTemplate in stack ssd-cluster
2021-12-14 19:47:09,615 [WARNING] Timeout of 60 seconds breached
2021-12-14 19:47:09,615 [ERROR] Client-side timeout
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/cfnbootstrap/util.py", line 189, in _retry
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/cfnbootstrap/util.py", line 262, in _timeout
    raise TimeoutError(
cfnbootstrap.util.TimeoutError
< The same timeout keeps repeating>
```
`/var/log/cloud-init.log`:

```
2021-12-14 19:39:48,051 - subp.py[DEBUG]: Running command [''] with allowed return codes [0] (shell=False, capture=False)
2021-12-14 19:50:25,617 - subp.py[DEBUG]: Unexpected error while running command.
Command: ['/var/lib/cloud/instance/scripts/part-002']
Exit code: 1
Reason: -
Stdout: -
Stderr: -
2021-12-14 19:50:25,617 - cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
2021-12-14 19:50:25,618 - handlers.py[DEBUG]: finish: modules-final/config-scripts-user: FAIL: running config-scripts-user with frequency once-per-instance
2021-12-14 19:50:25,618 - util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py'>) failed
2021-12-14 19:50:25,618 - util.py[DEBUG]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py'>) failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cloudinit/stages.py", line 965, in _run_modules
    ran, _r = cc.run(run_name, mod.handle, func_args,
  File "/usr/lib/python3/dist-packages/cloudinit/cloud.py", line 54, in run
    return self._runners.run(name, functor, args, freq, clear_on_fail)
  File "/usr/lib/python3/dist-packages/cloudinit/helpers.py", line 186, in run
    results = functor(*args)
  File "/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py", line 45, in handle
    subp.runparts(runparts_path)
  File "/usr/lib/python3/dist-packages/cloudinit/subp.py", line 384, in runparts
    raise RuntimeError(
RuntimeError: Runparts: 1 failures (part-002) in 1 attempted commands
2021-12-14 19:50:25,622 - stages.py[DEBUG]: Running module ssh-authkey-fingerprints (<module 'cloudinit.config.cc_ssh_authkey_fingerprints' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_ssh_authkey_fingerprints.py'>) with frequency once-per-instance
2021-12-14 19:50:25,622 - handlers.py[DEBUG]: start: modules-final/config-ssh-authkey-fingerprints: running config-ssh-authkey-fingerprints with frequency once-per-instance
2021-12-14 19:50:25,622 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-08bbb7149a8b69d74/sem/config_ssh_authkey_fingerprints - wb: [644] 25 bytes
2021-12-14 19:50:25,623 - helpers.py[DEBUG]: Running config-ssh-authkey-fingerprints using lock (<FileLock using file '/var/lib/cloud/instances/i-08bbb7149a8b69d74/sem/config_ssh_authkey_fingerprints'>)
2021-12-14 19:50:25,623 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2021-12-14 19:50:25,624 - util.py[DEBUG]: Read 689 bytes from /etc/ssh/sshd_config
2021-12-14 19:50:25,624 - util.py[DEBUG]: Reading from /home/ubuntu/.ssh/authorized_keys (quiet=False)
2021-12-14 19:50:25,624 - util.py[DEBUG]: Read 394 bytes from /home/ubuntu/.ssh/authorized_keys
2021-12-14 19:50:25,626 - handlers.py[DEBUG]: finish: modules-final/config-ssh-authkey-fingerprints: SUCCESS: config-ssh-authkey-fingerprints ran successfully
2021-12-14 19:50:25,626 - stages.py[DEBUG]: Running module keys-to-console (<module 'cloudinit.config.cc_keys_to_console' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_keys_to_console.py'>) with frequency once-per-instance
2021-12-14 19:50:25,626 - handlers.py[DEBUG]: start: modules-final/config-keys-to-console: running config-keys-to-console with frequency once-per-instance
2021-12-14 19:50:25,627 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-08bbb7149a8b69d74/sem/config_keys_to_console - wb: [644] 25 bytes
2021-12-14 19:50:25,627 - helpers.py[DEBUG]: Running config-keys-to-console using lock (<FileLock using file '/var/lib/cloud/instances/i-08bbb7149a8b69d74/sem/config_keys_to_console'>)
2021-12-14 19:50:25,627 - subp.py[DEBUG]: Running command ['/usr/lib/cloud-init/write-ssh-key-fingerprints', '', 'ssh-dss'] with allowed return codes [0] (shell=False, capture=True)
2021-12-14 19:50:25,659 - handlers.py[DEBUG]: finish: modules-final/config-keys-to-console: SUCCESS: config-keys-to-console ran successfully
2021-12-14 19:50:25,659 - stages.py[DEBUG]: Running module phone-home (<module 'cloudinit.config.cc_phone_home' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_phone_home.py'>) with frequency once-per-instance
2021-12-14 19:50:25,659 - handlers.py[DEBUG]: start: modules-final/config-phone-home: running config-phone-home with frequency once-per-instance
2021-12-14 19:50:25,660 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-08bbb7149a8b69d74/sem/config_phone_home - wb: [644] 25 bytes
2021-12-14 19:50:25,660 - helpers.py[DEBUG]: Running config-phone-home using lock (<FileLock using file '/var/lib/cloud/instances/i-08bbb7149a8b69d74/sem/config_phone_home'>)
2021-12-14 19:50:25,660 - cc_phone_home.py[DEBUG]: Skipping module named phone-home, no 'phone_home' configuration found
2021-12-14 19:50:25,660 - handlers.py[DEBUG]: finish: modules-final/config-phone-home: SUCCESS: config-phone-home ran successfully
2021-12-14 19:50:25,660 - stages.py[DEBUG]: Running module final-message (<module 'cloudinit.config.cc_final_message' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_final_message.py'>) with frequency always
2021-12-14 19:50:25,661 - handlers.py[DEBUG]: start: modules-final/config-final-message: running config-final-message with frequency always
2021-12-14 19:50:25,661 - helpers.py[DEBUG]: Running config-final-message using lock (<cloudinit.helpers.DummyLock object at 0x7fbad9f75af0>)
2021-12-14 19:50:25,661 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2021-12-14 19:50:25,661 - util.py[DEBUG]: Read 15 bytes from /proc/uptime
2021-12-14 19:50:25,666 - util.py[DEBUG]: Cloud-init v. 21.3-1-g6803368d-0ubuntu1~20.04.4 finished at Tue, 14 Dec 2021 19:50:25 +0000. Datasource DataSourceEc2Local.  Up 685.45 seconds
2021-12-14 19:50:25,666 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/boot-finished - wb: [644] 80 bytes
2021-12-14 19:50:25,667 - handlers.py[DEBUG]: finish: modules-final/config-final-message: SUCCESS: config-final-message ran successfully
2021-12-14 19:50:25,667 - stages.py[DEBUG]: Running module power-state-change (<module 'cloudinit.config.cc_power_state_change' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_power_state_change.py'>) with frequency once-per-instance
2021-12-14 19:50:25,667 - handlers.py[DEBUG]: start: modules-final/config-power-state-change: running config-power-state-change with frequency once-per-instance
2021-12-14 19:50:25,667 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-08bbb7149a8b69d74/sem/config_power_state_change - wb: [644] 25 bytes
2021-12-14 19:50:25,668 - helpers.py[DEBUG]: Running config-power-state-change using lock (<FileLock using file '/var/lib/cloud/instances/i-08bbb7149a8b69d74/sem/config_power_state_change'>)
2021-12-14 19:50:25,668 - cc_power_state_change.py[DEBUG]: no power_state provided. doing nothing
2021-12-14 19:50:25,668 - handlers.py[DEBUG]: finish: modules-final/config-power-state-change: SUCCESS: config-power-state-change ran successfully
2021-12-14 19:50:25,668 - main.py[DEBUG]: Ran 22 modules with 1 failures
2021-12-14 19:50:25,668 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpx5fg1o8_) - w: [644] 673 bytes/chars
2021-12-14 19:50:25,669 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/result.json (via temporary file /var/lib/cloud/data/tmpb79lr6q2) - w: [644] 167 bytes/chars
2021-12-14 19:50:25,669 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/result.json' => '../../var/lib/cloud/data/result.json'
2021-12-14 19:50:25,669 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2021-12-14 19:50:25,669 - util.py[DEBUG]: Read 15 bytes from /proc/uptime
2021-12-14 19:50:25,669 - util.py[DEBUG]: cloud-init mode 'modules' took 637.706 seconds (637.71)
2021-12-14 19:50:25,669 - handlers.py[DEBUG]: finish: modules-final: FAIL: running modules for final
```

`/var/log/chef-client.log` does not exist.

**Comment by srdecny** [comment]
Perhaps the problem is the subnet ID specified is already existing and apparently the head node does not have Internet access, as I have just noticed. Other instances residing inside that subnet do have access to the Internet, as it's a public subnet with a table route entry pointing to an Internet Gateway.

I have manually assigned a Security Group to the head node's network adapter that is the same SG used for other instance in the same subnet that has Internet connectivity. Even after that, the head node has no internet connectivity. The SG allows all outbound traffic on all protocols, and allows inbound traffic for SSH and all TCP inside the VPC. The instance with Internet connectivity has Public IPv4 address, but as far as I know, that should not affect things.

**Comment by srdecny** [comment]
Okay, so the issue was `pcluster` does not by-default assign public IP addresses to head and compute nodes, so they don't have internet access inside that subnet. 

After adding `ElasticIp: true` to the`HeadNode.Networking` section and `AssignPublicIp: true` to `Scheduling.SlurmQueues.Networking`, I am able to launch a pcluster with Internet connectivity.

**Comment by jsmedmar** [comment]
Hi @srdecny could you share the final configuration that worked for you? I'm having the same issue, but after following your suggestion, my problem persisted.

**Comment by srdecny** [comment]
@jsmedmar Hi, the underlying issue in my case was the nodes did not have Internet connectivity, so AWS's automation scripts failed. Make sure your VPC + the subnet you're deploying ParallelCluster to allows Internet connectivity. Or try upgrading to latest ParallelCluster, I think they fixed this issue in a recent update.

I don't have the original configuration anymore, sorry.

**Comment by MustaphaU** [comment]
I am faced with a similar issue. ParallelCluster creation fails due to failure to create the `HeadNodeWaitCondition`. I have created the issue under this repo: https://github.com/aws-samples/genai-video-super-resolution/issues/3 \
