### ISSUE TITLE
pcluster 3.1.4 build-image fails on Mac, python 3.7.4

### ISSUE THREAD

**Issue by pradeeban** [aws/aws-parallelcluster#4214]
Hi,
When I run the below,

`$ pcluster build-image --image-id ami-emoryhummingbird --image-configuration IMAGE_CONFIG.yaml --region us-east-2`

It fails with the logs as below:
`b'    at startup (internal/bootstrap/node.js:283:19)\n'
b'    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)\n'
{
  "message": "ParallelCluster image build infrastructure creation failed.\nExpecting value: line 1 column 1 (char 0)"
}
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 284, in stop
    self._process.stdin.close()
BrokenPipeError: [Errno 32] Broken pipe
`

The config file is,
```
Build:
  InstanceType: r6i.xlarge
  ParentImage: ami-58f5db3d
```
The detailed logs indicate,
```
$ tail -f ~/.parallelcluster/pcluster-cli.log

2022-07-22 22:34:38,744 - INFO - entrypoint.py:226:run() - Handling CLI command build-image
2022-07-22 22:34:38,745 - INFO - entrypoint.py:227:run() - Parsed CLI arguments: args(Namespace(dryrun=None, func=functools.partial(<function dispatch at 0x7fd554cfb050>, {'list-clusters': {'params': [{'name': 'region', 'body': False, 'description': 'List clusters deployed to a given AWS Region.', 'required': False, 'type': 'string'}, {'name': 'next-token', 'body': False, 'description': 'Token to use for paginated requests.', 'required': False, 'type': 'string'}, {'name': 'cluster-status', 'body': False, 'description': 'Filter by cluster status. (Defaults to all clusters.)', 'required': False, 'multi': True, 'enum': ['CREATE_IN_PROGRESS', 'CREATE_FAILED', 'CREATE_COMPLETE', 'DELETE_IN_PROGRESS', 'DELETE_FAILED', 'UPDATE_IN_PROGRESS', 'UPDATE_COMPLETE', 'UPDATE_FAILED'], 'type': 'string'}], 'func': 'pcluster.api.controllers.cluster_operations_controller.list_clusters', 'description': 'Retrieve the list of existing clusters.'}, 'create-cluster': {'params': [{'name': 'region', 'body': False, 'description': 'AWS Region that the operation corresponds to.', 'required': False, 'type': 'string'}, {'name': 'suppress-validators', 'body': False, 'description': 'Identifies one or more config validators to suppress. Format: (ALL|type:[A-Za-z0-9]+)', 'required': False, 'multi': True, 'pattern': '^(ALL|type:[A-Za-z0-9]+)$', 'type': 'string'}, {'name': 'validation-failure-level', 'body': False, 'description': "Min validation level that will cause the creation to fail. (Defaults to 'ERROR'.)", 'required': False, 'enum': ['INFO', 'WARNING', 'ERROR'], 'type': 'string'}, {'name': 'dryrun', 'body': False, 'description': "Only perform request validation without creating any resource. May be used to validate the cluster configuration. (Defaults to 'false'.)", 'required': False, 'type': 'boolean'}, {'name': 'rollback-on-failure', 'body': False, 'description': "When set it automatically initiates a cluster stack rollback on failures. (Defaults to 'true'.)", 'required': False, 'type': 'boolean'}, {'name': 'cluster-name', 'body': True, 'required': True, 'description': 'Name of the cluster that will be created.', 'pattern': '^[a-zA-Z][a-zA-Z0-9-]+$', 'type': 'string'}, {'name': 'cluster-configuration', 'body': True, 'required': True, 'description': 'Cluster configuration as a YAML document.', 'type': 'file'}], 'func': 'pcluster.api.controllers.cluster_operations_controller.create_cluster', 'description': 'Create a managed cluster in a given region.', 'body_name': 'create_cluster_request_content'}, 'delete-cluster': {'params': [{'name': 'cluster-name', 'body': False, 'description': 'Name of the cluster', 'required': True, 'pattern': '^[a-zA-Z][a-zA-Z0-9-]+$', 'type': 'string'}, {'name': 'region', 'body': False, 'description': 'AWS Region that the operation corresponds to.', 'required': False, 'type': 'string'}], 'func': 'pcluster.api.controllers.cluster_operations_controller.delete_cluster', 'description': 'Initiate the deletion of a cluster.'}, 'describe-cluster': {'params': [{'name': 'cluster-name', 'body': False, 'description': 'Name of the cluster', 'required': True, 'pattern': '^[a-zA-Z][a-zA-Z0-9-]+$', 'type': 'string'}, {'name': 'region', 'body': False, 'description': 'AWS Region that the operation corresponds to.', 'required': False, 'type': 'string'}], 'func': 'pcluster.api.controllers.cluster_operations_controller.describe_cluster', 'description': 'Get detailed information about an existing cluster.'}, 'update-cluster': {'params': [{'name': 'cluster-name', 'body': False, 'description': 'Name of the cluster', 'required': True, 'pattern': '^[a-zA-Z][a-zA-Z0-9-]+$', 'type': 'string'}, {'name': 'suppress-validators', 'body': False, 'description': 'Identifies one or more config validators to suppress. Format: (ALL|type:[A-Za-z0-9]+)', 'required': False, 'multi': True, 'pattern': '^(ALL|type:[A-Za-z0-9]+)$', 'type': 'string'}, {'name': 'validation-failure-level', 'body': False, 'description': "Min validation level that will cause the update to fail. (Defaults to 'ERROR'.)", 'required': False, 'enum': ['INFO', 'WARNING', 'ERROR'], 'type': 'string'}, {'name': 'region', 'body': False, 'description': 'AWS Region that the operation corresponds to.', 'required': False, 'type': 'string'}, {'name': 'dryrun', 'body': False, 'description': "Only perform request validation without creating any resource. May be used to validate the cluster configuration and update requirements. (Defaults to 'false'.)", 'required': False, 'type': 'boolean'}, {'name': 'force-update', 'body': False, 'description': "Force update by ignoring the update validation errors. (Defaults to 'false'.)", 'required': False, 'type': 'boolean'}, {'name': 'cluster-configuration', 'body': True, 'required': True, 'description': 'Cluster configuration as a YAML document.', 'type': 'file'}], 'func': 'pcluster.api.controllers.cluster_operations_controller.update_cluster', 'description': 'Update a cluster managed in a given region.', 'body_name': 'update_cluster_request_content'}, 'describe-compute-fleet': {'params': [{'name': 'cluster-name', 'body': False, 'description': 'Name of the cluster', 'required': True, 'pattern': '^[a-zA-Z][a-zA-Z0-9-]+$', 'type': 'string'}, {'name': 'region', 'body': False, 'description': 'AWS Region that the operation corresponds to.', 'required': False, 'type': 'string'}], 'func': 'pcluster.api.controllers.cluster_compute_fleet_controller.describe_compute_fleet', 'description': 'Describe the status of the compute fleet.'}, 'update-compute-fleet': {'params': [{'name': 'cluster-name', 'body': False, 'description': 'Name of the cluster', 'required': True, 'pattern': '^[a-zA-Z][a-zA-Z0-9-]+$', 'type': 'string'}, {'name': 'region', 'body': False, 'description': 'AWS Region that the operation corresponds to.', 'required': False, 'type': 'string'}, {'name': 'status', 'body': True, 'required': True, 'enum': ['START_REQUESTED', 'STOP_REQUESTED', 'ENABLED', 'DISABLED'], 'type': 'string'}], 'func': 'pcluster.api.controllers.cluster_compute_fleet_controller.update_compute_fleet', 'description': 'Update the status of the cluster compute fleet.', 'body_name': 'update_compute_fleet_request_content'}, 'delete-cluster-instances': {'params': [{'name': 'cluster-name', 'body': False, 'description': 'Name of the cluster', 'required': True, 'pattern': '^[a-zA-Z][a-zA-Z0-9-]+$', 'type': 'string'}, {'name': 'region', 'body': False, 'description': 'AWS Region that the operation corresponds to.', 'required': False, 'type': 'string'}, {'name': 'force', 'body': False, 'description': "Force the deletion also when the cluster with the given name is not found. (Defaults to 'false'.)", 'required': False, 'type': 'boolean'}], 'func': 'pcluster.api.controllers.cluster_instances_controller.delete_cluster_instances', 'description': 'Initiate the forced termination of all cluster compute nodes. Does not work with AWS Batch clusters.'}, 'describe-cluster-instances': {'params': [{'name': 'cluster-name', 'body': False, 'description': 'Name of the cluster', 'required': True, 'pattern': '^[a-zA-Z][a-zA-Z0-9-]+$', 'type': 'string'}, {'name': 'region', 'body': False, 'description': 'AWS Region that the operation corresponds to.', 'required': False, 'type': 'string'}, {'name': 'next-token', 'body': False, 'description': 'Token to use for paginated requests.', 'required': False, 'type': 'string'}, {'name': 'node-type', 'body': False, 'description': 'Filter the instances by node type.', 'required': False, 'enum': ['HeadNode', 'ComputeNode'], 'type': 'string'}, {'name': 'queue-name', 'body': False, 'description': 'Filter the instances by queue name.', 'required': False, 'type': 'string'}], 'func': 'pcluster.api.controllers.cluster_instances_controller.describe_cluster_instances', 'description': 'Describe the instances belonging to a given cluster.'}, 'list-cluster-log-streams': {'params': [{'name': 'cluster-name', 'body': False, 'description': 'Name of the cluster', 'required': True, 'pattern': '^[a-zA-Z][a-zA-Z0-9-]+$', 'type': 'string'}, {'name': 'region', 'body': False, 'description': 'Region that the given cluster belongs to.', 'required': False, 'type': 'string'}, {'name': 'filters', 'body': False, 'description': "Filter the log streams. Format: 'Name=a,Values=1 Name=b,Values=2,3'.\nAccepted filters are:\nprivate-dns-name - The short form of the private DNS name of the instance (e.g. ip-10-0-0-101).\nnode-type - The node type, the only accepted value for this filter is HeadNode.", 'required': False, 'multi': True, 'type': 'string'}, {'name': 'next-token', 'body': False, 'description': 'Token to use for paginated requests.', 'required': False, 'type': 'string'}], 'func': 'pcluster.api.controllers.cluster_logs_controller.list_cluster_log_streams', 'description': 'Retrieve the list of log streams associated with a cluster.'}, 'get-cluster-log-events': {'params': [{'name': 'cluster-name', 'body': False, 'description': 'Name of the cluster', 'required': True, 'pattern': '^[a-zA-Z][a-zA-Z0-9-]+$', 'type': 'string'}, {'name': 'log-stream-name', 'body': False, 'description': 'Name of the log stream.', 'required': True, 'type': 'string'}, {'name': 'region', 'body': False, 'description': 'AWS Region that the operation corresponds to.', 'required': False, 'type': 'string'}, {'name': 'next-token', 'body': False, 'description': 'Token to use for paginated requests.', 'required': False, 'type': 'string'}, {'name': 'start-from-head', 'body': False, 'description': "If the value is true, the earliest log events are returned first. If the value is false, the latest log events are returned first. (Defaults to 'false'.)", 'required': False, 'type': 'boolean'}, {'name': 'limit', 'body': False, 'description': "The maximum number of log events returned. If you don't specify a value, the maximum is as many log events as can fit in a response size of 1 MB, up to 10,000 log events.", 'required': False, 'type': 'integer'}, {'name': 'start-time', 'body': False, 'description': "The start of the time range, expressed in ISO 8601 format (e.g. '2021-01-01T20:00:00Z'). Events with a timestamp equal to this time or later than this time are included.", 'required': False, 'type': 'string'}, {'name': 'end-time', 'body': False, 'description': "The end of the time range, expressed in ISO 8601 format (e.g. '2021-01-01T20:00:00Z'). Events with a timestamp equal to or later than this time are not included.", 'required': False, 'type': 'string'}], 'func': 'pcluster.api.controllers.cluster_logs_controller.get_cluster_log_events', 'description': 'Retrieve the events associated with a log stream.'}, 'get-cluster-stack-events': {'params': [{'name': 'cluster-name', 'body': False, 'description': 'Name of the cluster', 'required': True, 'pattern': '^[a-zA-Z][a-zA-Z0-9-]+$', 'type': 'string'}, {'name': 'region', 'body': False, 'description': 'AWS Region that the operation corresponds to.', 'required': False, 'type': 'string'}, {'name': 'next-token', 'body': False, 'description': 'Token to use for paginated requests.', 'required': False, 'type': 'string'}], 'func': 'pcluster.api.controllers.cluster_logs_controller.get_cluster_stack_events', 'description': 'Retrieve the events associated with the stack for a given cluster.'}, 'list-images': {'params': [{'name': 'region', 'body': False, 'description': 'List images built in a given AWS Region.', 'required': False, 'type': 'string'}, {'name': 'next-token', 'body': False, 'description': 'Token to use for paginated requests.', 'required': False, 'type': 'string'}, {'name': 'image-status', 'body': False, 'description': 'Filter images by the status provided.', 'required': True, 'enum': ['AVAILABLE', 'PENDING', 'FAILED'], 'type': 'string'}], 'func': 'pcluster.api.controllers.image_operations_controller.list_images', 'description': 'Retrieve the list of existing custom images.'}, 'build-image': {'params': [{'name': 'suppress-validators', 'body': False, 'description': 'Identifies one or more config validators to suppress. Format: (ALL|type:[A-Za-z0-9]+)', 'required': False, 'multi': True, 'pattern': '^(ALL|type:[A-Za-z0-9]+)$', 'type': 'string'}, {'name': 'validation-failure-level', 'body': False, 'description': "Min validation level that will cause the creation to fail. (Defaults to 'ERROR'.)", 'required': False, 'enum': ['INFO', 'WARNING', 'ERROR'], 'type': 'string'}, {'name': 'dryrun', 'body': False, 'description': "Only perform request validation without creating any resource. It can be used to validate the image configuration. (Defaults to 'false'.)", 'required': False, 'type': 'boolean'}, {'name': 'rollback-on-failure', 'body': False, 'description': "When set, will automatically initiate an image stack rollback on failure. (Defaults to 'false'.)", 'required': False, 'type': 'boolean'}, {'name': 'region', 'body': False, 'description': 'AWS Region that the operation corresponds to.', 'required': False, 'type': 'string'}, {'name': 'image-configuration', 'body': True, 'required': True, 'description': 'Image configuration as a YAML document.', 'type': 'file'}, {'name': 'image-id', 'body': True, 'required': True, 'description': 'Id of the Image that will be built.', 'pattern': '^[a-zA-Z][a-zA-Z0-9-]+$', 'type': 'string'}], 'func': 'pcluster.api.controllers.image_operations_controller.build_image', 'description': 'Create a custom ParallelCluster image in a given region.', 'body_name': 'build_image_request_content'}, 'delete-image': {'params': [{'name': 'image-id', 'body': False, 'description': 'Id of the image.', 'required': True, 'pattern': '^[a-zA-Z][a-zA-Z0-9-]+$', 'type': 'string'}, {'name': 'region', 'body': False, 'description': 'AWS Region that the operation corresponds to.', 'required': False, 'type': 'string'}, {'name': 'force', 'body': False, 'description': "Force deletion in case there are instances using the AMI or in case the AMI is shared. (Defaults to 'false'.)", 'required': False, 'type': 'boolean'}], 'func': 'pcluster.api.controllers.image_operations_controller.delete_image', 'description': 'Initiate the deletion of the custom ParallelCluster image.'}, 'describe-image': {'params': [{'name': 'image-id', 'body': False, 'description': 'Id of the image.', 'required': True, 'pattern': '^[a-zA-Z][a-zA-Z0-9-]+$', 'type': 'string'}, {'name': 'region', 'body': False, 'description': 'AWS Region that the operation corresponds to.', 'required': False, 'type': 'string'}], 'func': 'pcluster.api.controllers.image_operations_controller.describe_image', 'description': 'Get detailed information about an existing image.'}, 'list-image-log-streams': {'params': [{'name': 'image-id', 'body': False, 'description': 'Id of the image.', 'required': True, 'pattern': '^[a-zA-Z][a-zA-Z0-9-]+$', 'type': 'string'}, {'name': 'region', 'body': False, 'description': 'Region that the given image belongs to.', 'required': False, 'type': 'string'}, {'name': 'next-token', 'body': False, 'description': 'Token to use for paginated requests.', 'required': False, 'type': 'string'}], 'func': 'pcluster.api.controllers.image_logs_controller.list_image_log_streams', 'description': 'Retrieve the list of log streams associated with an image.'}, 'get-image-log-events': {'params': [{'name': 'image-id', 'body': False, 'description': 'Id of the image.', 'required': True, 'pattern': '^[a-zA-Z][a-zA-Z0-9-]+$', 'type': 'string'}, {'name': 'log-stream-name', 'body': False, 'description': 'Name of the log stream.', 'required': True, 'type': 'string'}, {'name': 'region', 'body': False, 'description': 'AWS Region that the operation corresponds to.', 'required': False, 'type': 'string'}, {'name': 'next-token', 'body': False, 'description': 'Token to use for paginated requests.', 'required': False, 'type': 'string'}, {'name': 'start-from-head', 'body': False, 'description': "If the value is true, the earliest log events are returned first. If the value is false, the latest log events are returned first. (Defaults to 'false'.)", 'required': False, 'type': 'boolean'}, {'name': 'limit', 'body': False, 'description': "The maximum number of log events returned. If you don't specify a value, the maximum is as many log events as can fit in a response size of 1 MB, up to 10,000 log events.", 'required': False, 'type': 'integer'}, {'name': 'start-time', 'body': False, 'description': "The start of the time range, expressed in ISO 8601 format (e.g. '2021-01-01T20:00:00Z'). Events with a timestamp equal to this time or later than this time are included.", 'required': False, 'type': 'string'}, {'name': 'end-time', 'body': False, 'description': "The end of the time range, expressed in ISO 8601 format (e.g. '2021-01-01T20:00:00Z'). Events with a timestamp equal to or later than this time are not included.", 'required': False, 'type': 'string'}], 'func': 'pcluster.api.controllers.image_logs_controller.get_image_log_events', 'description': 'Retrieve the events associated with an image build.'}, 'get-image-stack-events': {'params': [{'name': 'image-id', 'body': False, 'description': 'Id of the image.', 'required': True, 'pattern': '^[a-zA-Z][a-zA-Z0-9-]+$', 'type': 'string'}, {'name': 'region', 'body': False, 'description': 'AWS Region that the operation corresponds to.', 'required': False, 'type': 'string'}, {'name': 'next-token', 'body': False, 'description': 'Token to use for paginated requests.', 'required': False, 'type': 'string'}], 'func': 'pcluster.api.controllers.image_logs_controller.get_image_stack_events', 'description': 'Retrieve the events associated with the stack for a given image build.'}, 'list-official-images': {'params': [{'name': 'region', 'body': False, 'description': 'AWS Region that the operation corresponds to.', 'required': False, 'type': 'string'}, {'name': 'os', 'body': False, 'description': 'Filter by OS distribution (Default is to not filter.)', 'required': False, 'type': 'string'}, {'name': 'architecture', 'body': False, 'description': 'Filter by architecture (Default is to not filter.)', 'required': False, 'type': 'string'}], 'func': 'pcluster.api.controllers.image_operations_controller.list_official_images', 'description': 'List Official ParallelCluster AMIs.'}}), image_configuration='Build:\n  InstanceType: r6i.xlarge\n  ParentImage: ami-58f5db3d', image_id='ami-emoryhummingbird', operation='build-image', query=None, region='us-east-2', rollback_on_failure=None, suppress_validators=None, validation_failure_level=None)), extra_args([])
2022-07-22 22:34:38,796 - INFO - common.py:46:_set_region() - Setting AWS Region to us-east-2
2022-07-22 22:34:38,914 - INFO - common.py:136:_log_boto3_calls() - Executing boto3 call: region=us-east-2, service=ec2, operation=DescribeImages, params={'ImageIds': [], 'Filters': [{'Name': 'tag:parallelcluster:image_id', 'Values': ['ami-emoryhummingbird']}, {'Name': 'tag:parallelcluster:build_status', 'Values': ['available']}], 'Owners': ['self']}
2022-07-22 22:34:39,224 - INFO - common.py:136:_log_boto3_calls() - Executing boto3 call: region=us-east-2, service=cloudformation, operation=DescribeStacks, params={'StackName': 'ami-emoryhummingbird'}
2022-07-22 22:34:39,463 - INFO - cfn.py:97:describe_stack() - Could not describe CloudFormation stack ami-emoryhummingbird: An error occurred (ValidationError) when calling the DescribeStacks operation: Stack with id ami-emoryhummingbird does not exist
2022-07-22 22:34:39,476 - INFO - common.py:136:_log_boto3_calls() - Executing boto3 call: region=us-east-2, service=ec2, operation=DescribeImages, params={'ImageIds': ['ami-58f5db3d']}
2022-07-22 22:34:39,600 - INFO - common.py:136:_log_boto3_calls() - Executing boto3 call: region=us-east-2, service=ec2, operation=DescribeInstanceTypeOfferings, params={}
2022-07-22 22:34:40,133 - INFO - common.py:136:_log_boto3_calls() - Executing boto3 call: region=us-east-2, service=ec2, operation=DescribeInstanceTypes, params={'InstanceTypes': ['r6i.xlarge']}
2022-07-22 22:34:40,423 - INFO - common.py:136:_log_boto3_calls() - Executing boto3 call: region=us-east-2, service=sts, operation=GetCallerIdentity, params={}
2022-07-22 22:34:40,629 - INFO - common.py:136:_log_boto3_calls() - Executing boto3 call: region=us-east-2, service=s3, operation=HeadBucket, params={'Bucket': 'parallelcluster-344028c9583f7617-v1-do-not-delete'}
2022-07-22 22:34:40,917 - INFO - common.py:136:_log_boto3_calls() - Executing boto3 call: region=us-east-2, service=s3, operation=HeadObject, params={'Bucket': 'parallelcluster-344028c9583f7617-v1-do-not-delete', 'Key': 'parallelcluster/.bootstrapped'}
2022-07-22 22:34:41,027 - INFO - common.py:136:_log_boto3_calls() - Executing boto3 call: region=us-east-2, service=s3, operation=PutObject, params={'Bucket': 'parallelcluster-344028c9583f7617-v1-do-not-delete', 'Body': 'Build:\n  InstanceType: r6i.xlarge\n  ParentImage: ami-58f5db3d', 'Key': 'parallelcluster/3.1.4/images/ami-emoryhummingbird-9rwzhl5fymqidoqj/configs/image-config.yaml'}
2022-07-22 22:34:41,172 - INFO - imagebuilder.py:461:create() - Building ParallelCluster image: ami-emoryhummingbird
2022-07-22 22:34:41,424 - ERROR - logger.py:74:write() - b'/private/var/folders/vz/hv1vsbpx21322d4x12xytw9c0000gn/T/tmp4uzacod5/bin/jsii-runtime.js:3843\n'
2022-07-22 22:34:41,425 - ERROR - logger.py:74:write() - b'            process.exit(128 + (os_1.constants.signals[signal] ?? 0));\n'
2022-07-22 22:34:41,425 - ERROR - logger.py:74:write() - b'                                                                ^\n'
2022-07-22 22:34:41,426 - ERROR - logger.py:74:write() - b'\n'
2022-07-22 22:34:41,426 - ERROR - logger.py:74:write() - b'SyntaxError: Unexpected token ?\n'
2022-07-22 22:34:41,426 - ERROR - logger.py:74:write() - b'    at Module._compile (internal/modules/cjs/loader.js:723:23)\n'
2022-07-22 22:34:41,426 - ERROR - logger.py:74:write() - b'    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)\n'
2022-07-22 22:34:41,426 - ERROR - logger.py:74:write() - b'    at Module.load (internal/modules/cjs/loader.js:653:32)\n'
2022-07-22 22:34:41,426 - ERROR - logger.py:74:write() - b'    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n'
2022-07-22 22:34:41,426 - ERROR - logger.py:74:write() - b'    at Function.Module._load (internal/modules/cjs/loader.js:585:3)\n'
2022-07-22 22:34:41,427 - CRITICAL - imagebuilder.py:491:create() - Expecting value: line 1 column 1 (char 0)
2022-07-22 22:34:41,427 - ERROR - logger.py:74:write() - b'    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)\n'
2022-07-22 22:34:41,428 - ERROR - entrypoint.py:250:main() - {"message": "ParallelCluster image build infrastructure creation failed.\nExpecting value: line 1 column 1 (char 0)"}
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pcluster/models/imagebuilder.py", line 465, in create
    image_config=self.config, image_id=self.image_id, bucket=self.bucket
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pcluster/templates/cdk_builder.py", line 48, in build_imagebuilder_template
    from aws_cdk.core import App  # pylint: disable=C0415
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/aws_cdk/core/__init__.py", line 986, in <module>
    from ._jsii import *
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/aws_cdk/core/_jsii/__init__.py", line 11, in <module>
    import aws_cdk.cloud_assembly_schema._jsii
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/aws_cdk/cloud_assembly_schema/__init__.py", line 75, in <module>
    from ._jsii import *
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/aws_cdk/cloud_assembly_schema/_jsii/__init__.py", line 15, in <module>
    "cloud-assembly-schema@1.161.0.jsii.tgz",
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jsii/_runtime.py", line 43, in load
    _kernel.load(assembly.name, assembly.version, os.fspath(assembly_path))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jsii/_kernel/__init__.py", line 269, in load
    self.provider.load(LoadRequest(name=name, version=version, tarball=tarball))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 338, in load
    return self._process.send(request, LoadResponse)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jsii/_utils.py", line 24, in wrapped
    stored.append(fgetter(self))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 333, in _process
    process.start()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 275, in start
    self.handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 299, in handshake
    self._next_message(), _HelloResponse
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 242, in _next_message
    return json.loads(self._process.stdout.readline(), object_hook=ohook)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 361, in loads
    return cls(**kw).decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pcluster/api/controllers/common.py", line 145, in wrapper
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pcluster/api/controllers/image_operations_controller.py", line 128, in build_image
    validation_failure_level=FailureLevel[validation_failure_level],
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pcluster/models/imagebuilder.py", line 495, in create
    raise _imagebuilder_error_mapper(e, f"ParallelCluster image build infrastructure creation failed.\n{e}")
pcluster.models.imagebuilder.ImageBuilderActionError: ParallelCluster image build infrastructure creation failed.
Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pcluster/cli/entrypoint.py", line 184, in _run_operation
    return args.func(args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pcluster/cli/entrypoint.py", line 106, in dispatch
    return dispatch_func(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pcluster/cli/model.py", line 211, in call
    ret = func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pcluster/api/controllers/common.py", line 97, in _wrapper_http_success_status_code
    return func(*args, **kwargs), status_code
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pcluster/api/controllers/common.py", line 157, in wrapper
    raise InternalServiceException(str(e)) from e
pcluster.api.errors.InternalServiceException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pcluster/cli/entrypoint.py", line 234, in main
    ret = run(sys.argv[1:])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pcluster/cli/entrypoint.py", line 228, in run
    return _run_operation(model, args, extra_args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pcluster/cli/entrypoint.py", line 195, in _run_operation
    raise APIOperationException(json.loads(error_encoded))
pcluster.cli.exceptions.APIOperationException: {
  "message": "ParallelCluster image build infrastructure creation failed.\nExpecting value: line 1 column 1 (char 0)"
}
```

Any hint what might be going wrong?

**Comment by hanwen-pcluste** [comment]
Hello,

The command and configuration file looks good to me. According to the logs, it looks like a networking issue. Could you try to run and command again and see if the issue persists?

Thank you,
Hanwen

**Comment by pradeeban** [comment]
Hi,
Yes, my first guess, too, was a network issue (as in ssh log-in failure after a time out). But in this case, the failure/log is immediate, and I can reproduce it (tried once again right now). My network is otherwise fine (local network, no VPN, and stable Internet connectivity at 45 Mbps).

```
$ pcluster build-image --image-id ami-emoryhummingbird --image-configuration IMAGE_CONFIG.yaml --region us-east-2
b'    at startup (internal/bootstrap/node.js:283:19)\n'
b'    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)\n'
{
  "message": "ParallelCluster image build infrastructure creation failed.\nExpecting value: line 1 column 1 (char 0)"
}
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 284, in stop
    self._process.stdin.close()
BrokenPipeError: [Errno 32] Broken pipe
```

Thank you.
Pradeeban.

**Comment by pradeeban** [comment]
I had installed pcluster directly. Installing on a venv fixed the above issue.

Closer inspection, I saw version mismatch logs in my direct installation without virtual env. I think one of these version mismatches (perhaps, pyyaml?) caused this.

I will stick to venv from now on.
