### ISSUE TITLE
seven_zip and chef versions misalignment

### ISSUE THREAD

**Issue by ezotkina** [aws/aws-parallelcluster#4269]
Dear All --

I have "cfncluster create RandomName" returning FAILURE. Upon examining the /var/log/cfn-init-cmd.log, I see the root cause:
```
2022-08-12 21:01:26,272 [ERROR] Command chef (chef-client --local-mode --config /etc/chef/client.rb --log_level auto --force-formatter --no-color --chef-zero-port 8889 --json-attributes /etc/chef/dna.json --override-runlist cfncluster::_prep_env) failed
2022-08-12 21:01:26,272 [DEBUG] Command chef output: Starting Chef Client, version 14.2.0
[2022-08-12T21:01:25+00:00] WARN: Run List override has been provided.
[2022-08-12T21:01:25+00:00] WARN: Run List override has been provided.
[2022-08-12T21:01:25+00:00] WARN: Original Run List: [recipe[cfncluster::slurm_config]]
[2022-08-12T21:01:25+00:00] WARN: Original Run List: [recipe[cfncluster::slurm_config]]
[2022-08-12T21:01:25+00:00] WARN: Overridden Run List: [recipe[cfncluster::_prep_env]]
[2022-08-12T21:01:25+00:00] WARN: Overridden Run List: [recipe[cfncluster::_prep_env]]
resolving cookbooks for run list: ["cfncluster::_prep_env"]
Synchronizing Cookbooks:
  - cfncluster (1.6.0)
  - build-essential (8.1.1)
  - tar (2.1.1)
  - poise-python (1.7.0)
  - selinux (2.1.1)
  - nfs (2.5.1)
  - sysctl (1.0.5)
  - yum-epel (3.1.0)
  - openssh (2.6.3)
  - apt (7.0.0)
  - yum (5.1.0)
  - hostname (0.4.2)
  - line (1.0.6)
  - seven_zip (4.2.2)
  - mingw (2.1.4)
  - poise (2.8.2)
  - poise-languages (2.1.2)
  - ohai (5.3.1)
  - iptables (8.0.0)
  - hostsfile (3.0.1)
  - poise-archive (1.5.0)

Running handlers:
[2022-08-12T21:01:26+00:00] ERROR: Running exception handlers
[2022-08-12T21:01:26+00:00] ERROR: Running exception handlers
Running handlers complete
[2022-08-12T21:01:26+00:00] ERROR: Exception handlers complete
[2022-08-12T21:01:26+00:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 03 seconds
[2022-08-12T21:01:26+00:00] FATAL: Stacktrace dumped to /etc/chef/local-mode-cache/cache/chef-stacktrace.out
[2022-08-12T21:01:26+00:00] FATAL: Stacktrace dumped to /etc/chef/local-mode-cache/cache/chef-stacktrace.out
[2022-08-12T21:01:26+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2022-08-12T21:01:26+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2022-08-12T21:01:26+00:00] FATAL: Chef::Exceptions::CookbookChefVersionMismatch: Cookbook 'seven_zip' version '4.2.2' depends on chef version [">= 15.3"], but the running chef version is 14.2.0
[2022-08-12T21:01:26+00:00] FATAL: Chef::Exceptions::CookbookChefVersionMismatch: Cookbook 'seven_zip' version '4.2.2' depends on chef version [">= 15.3"], but the running chef version is 14.2.0

2022-08-12 21:01:26,272 [ERROR] Error encountered during build of chefPrepEnv: Command chef failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 542, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 260, in build
    changes['commands'] = CommandTool().apply(self._config.commands)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/command_tool.py", line 117, in apply
    raise ToolError(u"Command %s failed" % name)
ToolError: Command chef failed
2022-08-12 21:01:26,275 [ERROR] -----------------------BUILD FAILED!------------------------
2022-08-12 21:01:26,275 [ERROR] Unhandled exception during build: Command chef failed
Traceback (most recent call last):
  File "/opt/aws/bin/cfn-init", line 171, in <module>
    worklog.build(metadata, configSets)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 129, in build
    Contractor(metadata).build(configSets, self)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 530, in build
    self.run_config(config, worklog)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 542, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 260, in build
    changes['commands'] = CommandTool().apply(self._config.commands)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/command_tool.py", line 117, in apply
    raise ToolError(u"Command %s failed" % name)
ToolError: Command chef failed
2022-08-12 21:01:26,468 [DEBUG] CloudFormation client initialized with endpoint https://cloudformation.us-east-1.amazonaws.com/
2022-08-12 21:01:26,468 [DEBUG] Signaling resource MasterServer in stack cfncluster-RandomName with unique ID i-0XXXX....XXXX and status FAILURE
```
Would like to get a fix or a workaround suggestion. Thank you.

**Comment by enrico-usai** [comment]
Hi @ezotkina 
you're facing a known issue with an old version of ParallelCluster: https://github.com/aws/aws-parallelcluster/issues/2706

It seems to me you're using cfncluster 1.6.0. 
Can you confirm you're using an old ParallelCluster version?

We strongly suggest you to create a new cluster with the latest version of the product that is 3.2.0.
Please check also [ParallelCluster Support Policy](https://docs.aws.amazon.com/parallelcluster/latest/ug/support-policy.html)

Thanks

**Comment by ezotkina** [comment]
@enrico-usai Yes, the logs above are from the latest version of "cfncluster" (1.6.1, October 2018, as it exists on pypi) that somebody else used in legacy code here. Seems really old.

I switched to latest "parallelcluster" and am able to do now what I want.

Thank you very much.
