### ISSUE TITLE
All or nothing documentation error

### ISSUE THREAD

**Issue by t-brown** [aws/aws-parallelcluster#4384]
## Bug description

The documentation on [all or nothing batch launches](https://github.com/aws/aws-parallelcluster/wiki/Configuring-all_or_nothing_batch-launches) has comments in the `/etc/parallelcluster/slurm_plugin/parallelcluster_slurm_resume.conf` on the same line as the configuration information. For example:

```
all_or_nothing_batch = True      # default: False
max_batch_size = 100             # default: 500
```

This leads to when trying to use it. For example @climbfuji reported the following:

```
2022-09-25 02:28:44,249 - [slurm_plugin.resume:main] - INFO - ResumeProgram startup.
2022-09-25 02:28:44,250 - [slurm_plugin.resume:_get_config] - INFO - Reading /etc/parallelcluster/slurm_plugin/parallelcluster_slurm_resume.conf
2022-09-25 02:28:44,250 - [slurm_plugin.resume:main] - ERROR - Encountered exception when requesting instances for hpc6a-dy-hpc6a-48xlarge-1: invalid literal for int() with base 10: '100             # default: 500'
Traceback (most recent call last):
  File "/opt/parallelcluster/pyenv/versions/3.7.10/envs/node_virtualenv/lib/python3.7/site-packages/slurm_plugin/resume.py", line 204, in main
    resume_config = SlurmResumeConfig(config_file)
  File "/opt/parallelcluster/pyenv/versions/3.7.10/envs/node_virtualenv/lib/python3.7/site-packages/slurm_plugin/resume.py", line 46, in __init__
    self._get_config(config_file_path)
  File "/opt/parallelcluster/pyenv/versions/3.7.10/envs/node_virtualenv/lib/python3.7/site-packages/slurm_plugin/resume.py", line 74, in _get_config
    "slurm_resume", "max_batch_size", fallback=self.DEFAULTS.get("max_batch_size")
  File "/opt/parallelcluster/pyenv/versions/3.7.10/lib/python3.7/configparser.py", line 818, in getint
    fallback=fallback, **kwargs)
  File "/opt/parallelcluster/pyenv/versions/3.7.10/lib/python3.7/configparser.py", line 808, in _get_conv
    **kwargs)
  File "/opt/parallelcluster/pyenv/versions/3.7.10/lib/python3.7/configparser.py", line 802, in _get
    return conv(self.get(section, option, **kwargs))
```

Is it possible to update the documentation by removing the defaults comments in the configuration file?
Thanks.

**Comment by sean-smith** [comment]
+1 to this, I've had customers hit it

**Comment by chenwany** [comment]
Thank you for the feedbacks!
Yes, documentation is updated to remove the defaults comments in the configuration file. The default values are mentioned in the paragraph above the configuration file.

Thanks

**Comment by t-brown** [comment]
Thanks!
