### ISSUE TITLE
Parallel Cluster Creation Chef Error

### ISSUE THREAD

**Issue by wdykas** [aws/aws-parallelcluster#4819]
I am seeing a failure to create a cluster when following the tutorial here: https://docs.aws.amazon.com/parallelcluster/latest/ug/tutorials_05_multi-user-ad.html 
 - AWS ParallelCluster version:3.4.1
 - Cluster name: ad-cluster
 - Output of `pcluster describe-cluster` command.

{
    "instanceType": "t2.micro",
    "state": "running",
  },
  "version": "3.4.1",
  "tags": [
    {
      "value": "3.4.1",
      "key": "parallelcluster:version"
    },
    {
      "value": "ad-cluster",
      "key": "parallelcluster:cluster-name"
    }
  ],
  "cloudFormationStackStatus": "CREATE_FAILED",
  "clusterName": "ad-cluster",
  "computeFleetStatus": "UNKNOWN",
  "lastUpdatedTime": "2023-01-23T21:09:44.343Z",
  "region": "us-west-1",
  "clusterStatus": "CREATE_FAILED",
  "scheduler": {
    "type": "slurm"
  }

**Bug description and how to reproduce:**
When creating a cluster it fails to create properly.   I am seeing an error when setup is trying to run the script:
```
Jan 23 21:14:59 cloud-init[3550]: util.py[WARNING]: Failed running /var/lib/cloud/instance/scripts/part-003 [1]
Jan 23 21:14:59 cloud-init[3550]: util.py[DEBUG]: Failed running /var/lib/cloud/instance/scripts/part-003 [1]
```
I am running the create with 
`cluster create-cluster --cluster-name "ad-cluster" --rollback-on-failure False --cluster-configuration "./ldap_config.yaml"`

My ldap config with some redactions is below:
```

Region: us-west-1
Image:
  Os: alinux2
HeadNode:
  InstanceType: t2.micro
  Networking:
    SubnetId: subnetid
  Ssh:
    KeyName: keyname
Scheduling:
  Scheduler: slurm
  SlurmQueues:
    - Name: queue0
      ComputeResources:
        - Name: queue0-g4dn12xlarge
          InstanceType: g4dn.12xlarge
          MinCount: 2
          MaxCount: 2
      Networking:
        SubnetIds:
          - subnetid
DirectoryService:
  DomainName: dc=corp,dc=pcluster,dc=com
  DomainAddr: ldap://ip,ldap://ip
  PasswordSecretArn: redact
  DomainReadOnlyUser: cn=ReadOnlyUser,ou=Users,ou=CORP,dc=corp,dc=pcluster,dc=com
  AdditionalSssdConfigs:
    ldap_auth_disable_tls_never_use_in_production: True

```
`/var/log/cfn-init.log`
```

2023-01-23 21:14:48,875 [ERROR] Command chef (cinc-client --local-mode --config /etc/chef/client.rb --log_level info --logfile /var/log/chef-client.log --force-formatter --no-color --chef-zero-port 8889 --json-attributes /etc/chef/dna.json --override-runlist aws-parallelcluster::init) failed
2023-01-23 21:14:48,875 [DEBUG] Command chef output:
2023-01-23 21:14:48,875 [ERROR] Error encountered during build of chefPrepEnv: Command chef failed
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/construction.py", line 579, in run_config
    CloudFormationCarpenter(config, self._auth_config, self.strict_mode).build(worklog)
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/construction.py", line 278, in build
    self._config.commands)
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/command_tool.py", line 127, in apply
    raise ToolError(u"Command %s failed" % name)
cfnbootstrap.construction_errors.ToolError: Command chef failed
2023-01-23 21:14:48,882 [ERROR] -----------------------BUILD FAILED!------------------------
2023-01-23 21:14:48,882 [ERROR] Unhandled exception during build: Command chef failed
Traceback (most recent call last):
  File "/opt/aws/bin/cfn-init", line 181, in <module>
    worklog.build(metadata, configSets, strict_mode)
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/construction.py", line 137, in build
    Contractor(metadata, strict_mode).build(configSets, self)
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/construction.py", line 567, in build
    self.run_config(config, worklog)
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/construction.py", line 579, in run_config
    CloudFormationCarpenter(config, self._auth_config, self.strict_mode).build(worklog)
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/construction.py", line 278, in build
    self._config.commands)
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/command_tool.py", line 127, in apply
    raise ToolError(u"Command %s failed" % name)
cfnbootstrap.construction_errors.ToolError: Command chef failed

```
``/var/log/cloud-init.log`,`
```

Jan 23 21:13:53 cloud-init[3550]: util.py[DEBUG]: Running command ['/var/lib/cloud/instance/scripts/part-003'] with allowed return codes [0] (shell=True, capture=False)
Jan 23 21:14:59 cloud-init[3550]: util.py[WARNING]: Failed running /var/lib/cloud/instance/scripts/part-003 [1]
Jan 23 21:14:59 cloud-init[3550]: util.py[DEBUG]: Failed running /var/lib/cloud/instance/scripts/part-003 [1]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cloudinit/util.py", line 913, in runparts
    subp(prefix + [exe_path], capture=False, shell=True)
  File "/usr/lib/python2.7/site-packages/cloudinit/util.py", line 2108, in subp
    cmd=args)
ProcessExecutionError: Unexpected error while running command.
Command: ['/var/lib/cloud/instance/scripts/part-003']
Exit code: 1
Reason: -
Stdout: -
Stderr: -
Jan 23 21:14:59 cloud-init[3550]: cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
Jan 23 21:14:59 cloud-init[3550]: handlers.py[DEBUG]: finish: modules-final/config-scripts-user: FAIL: running config-scripts-user with frequency once-per-instance
Jan 23 21:14:59 cloud-init[3550]: util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_user.pyc'>) failed
Jan 23 21:14:59 cloud-init[3550]: util.py[DEBUG]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_user.pyc'>) failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cloudinit/stages.py", line 851, in _run_modules
    freq=freq)
  File "/usr/lib/python2.7/site-packages/cloudinit/cloud.py", line 54, in run
    return self._runners.run(name, functor, args, freq, clear_on_fail)
  File "/usr/lib/python2.7/site-packages/cloudinit/helpers.py", line 187, in run
    results = functor(*args)
  File "/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_user.py", line 45, in handle
    util.runparts(runparts_path)
  File "/usr/lib/python2.7/site-packages/cloudinit/util.py", line 920, in runparts
    % (len(failed), len(attempted)))
RuntimeError: Runparts: 1 failures in 1 attempted commands

```

**Comment by lukeseawalker** [comment]
because of this error
```
2023-01-23 21:14:48,875 [ERROR] Command chef (cinc-client --local-mode --config /etc/chef/client.rb --log_level info --logfile /var/log/chef-client.log --force-formatter --no-color --chef-zero-port 8889 --json-attributes /etc/chef/dna.json --override-runlist aws-parallelcluster::init) failed
```

please check and report back the output of `/var/log/chef-client.log`

**Comment by wdykas** [comment]
Thanks for the response, turns out it was a Vcpu limit issue. It showed up in some of the slurm logs.  I will close, sorry for the inconvenience

**Comment by enrico-usai** [comment]
Thanks for your answer!
