### ISSUE TITLE
3.5.1: AttributeError: '_NodeProcess' object has no attribute '_process'

### ISSUE THREAD

**Issue by dirkpetersen** [aws/aws-parallelcluster#5231]
installed in a venv in a Debian VM on Windows WSL (no timesync issues) 
V 3.5.0 works just fine, only 3.51. has the problem 

```
pcluster version
Traceback (most recent call last):
  File "/home/dp/pcluster/bin/pcluster", line 5, in <module>
    from pcluster.cli.entrypoint import main
  File "/home/dp/pcluster/lib/python3.9/site-packages/pcluster/cli/entrypoint.py", line 27, in <module>
    import pcluster.api.controllers.cluster_compute_fleet_controller
  File "/home/dp/pcluster/lib/python3.9/site-packages/pcluster/api/controllers/cluster_compute_fleet_controller.py", line 11, in <module>
    from pcluster.api.controllers.common import configure_aws_region, convert_errors, validate_cluster
  File "/home/dp/pcluster/lib/python3.9/site-packages/pcluster/api/controllers/common.py", line 33, in <module>
    from pcluster.models.cluster import Cluster
  File "/home/dp/pcluster/lib/python3.9/site-packages/pcluster/models/cluster.py", line 35, in <module>
    from pcluster.config.cluster_config import BaseClusterConfig, SchedulerPluginScheduling, SlurmScheduling, Tag
  File "/home/dp/pcluster/lib/python3.9/site-packages/pcluster/config/cluster_config.py", line 111, in <module>
    from pcluster.validators.directory_service_validators import (
  File "/home/dp/pcluster/lib/python3.9/site-packages/pcluster/validators/directory_service_validators.py", line 15, in <module>
    from aws_cdk.core import Arn
  File "/home/dp/pcluster/lib/python3.9/site-packages/aws_cdk/core/__init__.py", line 988, in <module>
    from ._jsii import *
  File "/home/dp/pcluster/lib/python3.9/site-packages/aws_cdk/core/_jsii/__init__.py", line 13, in <module>
    import aws_cdk.cloud_assembly_schema._jsii
  File "/home/dp/pcluster/lib/python3.9/site-packages/aws_cdk/cloud_assembly_schema/__init__.py", line 77, in <module>
    from ._jsii import *
  File "/home/dp/pcluster/lib/python3.9/site-packages/aws_cdk/cloud_assembly_schema/_jsii/__init__.py", line 13, in <module>
    __jsii_assembly__ = jsii.JSIIAssembly.load(
  File "/home/dp/pcluster/lib/python3.9/site-packages/jsii/_runtime.py", line 55, in load
    _kernel.load(assembly.name, assembly.version, os.fspath(assembly_path))
  File "/home/dp/pcluster/lib/python3.9/site-packages/jsii/_kernel/__init__.py", line 299, in load
    self.provider.load(LoadRequest(name=name, version=version, tarball=tarball))
  File "/home/dp/pcluster/lib/python3.9/site-packages/jsii/_kernel/providers/process.py", line 352, in load
    return self._process.send(request, LoadResponse)
  File "/home/dp/pcluster/lib/python3.9/site-packages/jsii/_utils.py", line 23, in wrapped
    stored.append(fgetter(self))
  File "/home/dp/pcluster/lib/python3.9/site-packages/jsii/_kernel/providers/process.py", line 347, in _process
    process.start()
  File "/home/dp/pcluster/lib/python3.9/site-packages/jsii/_kernel/providers/process.py", line 260, in start
    self._process = subprocess.Popen(
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'node'
Exception ignored in: <function _NodeProcess.__del__ at 0x7fe43d33ec10>
Traceback (most recent call last):
  File "/home/dp/pcluster/lib/python3.9/site-packages/jsii/_kernel/providers/process.py", line 228, in __del__
    self.stop()
  File "/home/dp/pcluster/lib/python3.9/site-packages/jsii/_kernel/providers/process.py", line 291, in stop
    assert self._process.stdin is not None
AttributeError: '_NodeProcess' object has no attribute '_process'
```

**Comment by enrico-usai** [comment]
Hi @dirkpetersen 

```
FileNotFoundError: [Errno 2] No such file or directory: 'node'
```
 is indicating that the ParallelCluster cli can’t find node in the path. 

Did you follow the steps in the official doc? https://docs.aws.amazon.com/parallelcluster/latest/ug/install-v3-virtual-environment.html

Enrico

**Comment by dirkpetersen** [comment]
No, I used node v14 through the spack HPC system because that LTS version did not run on RHEL7. 3.5.0 worked fine and 3.5.1 did not. I am not sure why it cannot find node, it's in the PATH even though that PATH is long .

BTW: I just tried re-installing and right now the lastest version on PyPI is 3.1.5 , When I try to install 3.5.0 or 3.5.1  I am getting :

```
python3 -m pip install --upgrade "aws-parallelcluster==3.5.1"
Collecting aws-parallelcluster==3.5.1
  Could not find a version that satisfies the requirement aws-parallelcluster==3.5.1 (from versions: 2.0.0rc1, 2.0.0, 2.0.1, 2.0.2, 2.1.0, 2.1.1, 2.2.1, 2.3.1, 2.3.2a1, 2.4.0, 2.4.1, 2.5.0, 2.5.1, 2.6.0, 2.6.1, 2.7.0, 2.8.0, 2.8.1, 2.9.0, 2.9.1, 2.10.0, 2.10.1, 2.10.2, 2.10.3, 2.10.4, 2.11.0, 2.11.1, 2.11.2, 2.11.3, 2.11.4, 2.11.5, 2.11.6, 2.11.7, 2.11.8, 2.11.9, 3.0.0b1, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.1.0b1, 3.1.1, 3.1.2, 3.1.3, 3.1.4, 3.1.5, 3.2.0b1)
No matching distribution found for aws-parallelcluster==3.5.1
You are using pip version 18.1, however version 21.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by hanwen-pcluste** [comment]
Please make sure you are running Python>=3.7.

aws-parallelcluster==3.2.0b1 was the last version supporting Python 3.6

**Comment by dirkpetersen** [comment]
Sorry, wrong python version in last attempt, with a different version of node it works now and I am getting an EOL message. This works for me and I close the issue, Thank you  

```
 pcluster version
b'!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n'
b'!!                                                                                                                  !!\n'
b'!!  Node 14 is approaching end-of-life and will no longer be supported in new releases after 2023-04-30.            !!\n'
b'!!  Please upgrade to a supported node version as soon as possible.
```
