### ISSUE TITLE
PCluster doesn't work with latest Flask

### ISSUE THREAD

**Issue by mathiaslsamuelsen** [aws/aws-parallelcluster#5243]
Hello

There's a change in the 2.3.x update of Flask, so installing/using PCluster without forcing the environment to use Flask 2.2.x will result in an error: 

(apc-ve) root@ip-10-0-0-61:~# pcluster version
Traceback (most recent call last):
  File "/root/apc-ve/bin/pcluster", line 5, in <module>
    from pcluster.cli.entrypoint import main
  File "/root/apc-ve/lib/python3.8/site-packages/pcluster/cli/entrypoint.py", line 27, in <module>
    import pcluster.api.controllers.cluster_compute_fleet_controller
  File "/root/apc-ve/lib/python3.8/site-packages/pcluster/api/controllers/cluster_compute_fleet_controller.py", line 11, in <module>
    from pcluster.api.controllers.common import configure_aws_region, convert_errors, validate_cluster
  File "/root/apc-ve/lib/python3.8/site-packages/pcluster/api/controllers/common.py", line 22, in <module>
    from pcluster.api.errors import (
  File "/root/apc-ve/lib/python3.8/site-packages/pcluster/api/errors.py", line 9, in <module>
    from connexion import ProblemException
  File "/root/apc-ve/lib/python3.8/site-packages/connexion/__init__.py", line 32, in <module>
    from .apps.flask_app import FlaskApp
  File "/root/apc-ve/lib/python3.8/site-packages/connexion/apps/flask_app.py", line 151, in <module>
    class FlaskJSONEncoder(json.JSONEncoder):
AttributeError: module 'flask.json' has no attribute 'JSONEncoder'

**Comment by hanwen-pcluste** [comment]
We've published a Wiki to explain the issue and the mitigation: https://github.com/aws/aws-parallelcluster/wiki/(3.0.0-3.5.1)-ParallelCluster-CLI-raises-exception-%E2%80%9Cmodule-'flask.json'-has-no-attribute-'JSONEncoder'%E2%80%9D

Thank you for letting us know!
