### ISSUE TITLE
dead compute nodes included in sge queue

### ISSUE THREAD

**Issue by aqi-mph** [aws/aws-parallelcluster#566]
We're seeing an issue with v1.5.4 where some compute nodes appear to be terminating soon after they launch (not sure why, still trying to catch one in the act), which causes a problem when the master node tries to include an already-terminated compute node. We see snippets like this in /var/log/sqswatcher on the master:

```
2018-09-27 12:12:14,229 INFO [sqswatcher:pollQueue] eventType=cfncluster:COMPUTE_READY
2018-09-27 12:12:14,229 INFO [sqswatcher:pollQueue] instanceId=i-0435ad2a8a66ae1f8
2018-09-27 12:12:14,353 INFO [sqswatcher:pollQueue] Adding Hostname: 
2018-09-27 12:12:14,354 INFO [sge:addHost] Adding  with 32 slots
error: no option argument provided to "-ah"
...
2018-09-27 12:50:52,637 ERROR [sge:__runSgeCommand] Failed to run ['/opt/sge/bin/lx-amd64/qconf', '-ah']

error: no option argument provided to "-as"
...
2018-09-27 12:50:52,648 ERROR [sge:__runSgeCommand] Failed to run ['/opt/sge/bin/lx-amd64/qconf', '-as']

error: " " is the only character allowed between the attribute name and the value in line 2
error: error reading file: "/tmp/tmp6pHAOd"
invalid format
2018-09-27 12:50:52,661 ERROR [sge:__runSgeCommand] Failed to run ['/opt/sge/bin/lx-amd64/qconf', '-Ae', '/tmp/tmp6pHAOd']

2018-09-27 12:50:52,662 INFO [sge:addHost] Connecting to host:  iter: 0
2018-09-27 12:50:52,663 ERROR [sge:addHost] Socket error: [Errno -2] Name or service not known
2018-09-27 12:51:02,673 INFO [sge:addHost] Connecting to host:  iter: 1
2018-09-27 12:51:02,673 ERROR [sge:addHost] Socket error: [Errno -2] Name or service not known
2018-09-27 12:51:13,684 INFO [sge:addHost] Connecting to host:  iter: 2
2018-09-27 12:51:13,684 ERROR [sge:addHost] Socket error: [Errno -2] Name or service not known
2018-09-27 12:51:25,696 CRITICAL [sge:addHost] Unable to provison host
Traceback (most recent call last):
  File "/usr/bin/sqswatcher", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/sqswatcher/sqswatcher.py", line 219, in main
    pollQueue(scheduler, q, t, proxy_config)
  File "/usr/lib/python2.7/site-packages/sqswatcher/sqswatcher.py", line 170, in pollQueue
    raise e
botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the PutItem operation: One or more parameter values were invalid: An AttributeValue may not contain an empty string
...
```

It appears the hostname is being read as an empty string, triggering a cascade of problems downstream. This may be due to the following code snippet, which doesn't do any checking on the hostname:

```
       hostname = instance.private_dns_name.split('.')[:1][0]
       log.info("Adding Hostname: %s" % hostname)
```

The terminated compute nodes show up in qhost with dashes in place of the normal table values:

```
HOSTNAME                ARCH         NCPU NSOC NCOR NTHR  LOAD  MEMTOT  MEMUSE  SWAPTO  SWAPUS
----------------------------------------------------------------------------------------------
ip-1-2-3-4           -               -    -    -    -     -       -       -       -       -
...
```

**Comment by sean-smith** [comment]
hi @aqi-mph, thanks for the detailed bug report. What OS is this? Are you using spot?

**Comment by aqi-mph** [comment]
OS is Centos 7, and yes we are using spot for compute instances.

**Comment by enrico-usai** [comment]
This issue has been fixed by: https://github.com/aws/aws-parallelcluster-node/pull/94

It will be available with the next release.
