### ISSUE TITLE
Cloudformation Update ParallelCluster 3.6.0 - 3.6.1 : PclusterClusterProvider fails and is stuck in UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRES

### ISSUE THREAD

**Issue by francisreyes-tfs** [aws/aws-parallelcluster#5686]
When updating ParallelCluster via cloudformation, in this instance, the addition of SharedStorage EFS. The HeadNode will update the space, but will fail to rollback cleanly where PclusterClusterProvider gets stuck in UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS . The main cluster stack has errors WaitCondition received failed message: 'Update failed' for uniqueId: i-XXXXXXXXXXXXX. 

Any places on where to begin the diagnosis? And how to reset the stack, as I am currently deleting it and recreating it.

**Comment by enrico-usai** [comment]
Hi @francisreyes-tfs did you change instance types too? 
Because there is a known issue: https://github.com/aws/aws-parallelcluster/wiki/(3.0.0%E2%80%903.7.0)-Cluster-update-rollback-can-fail-when-modifying-the-list-of-instance-types-declared-in-the-Compute-Resources

In any case you should find the root cause of the issue in the `/var/log/chef-client.log` file in the head node.

**Comment by francisreyes-tfs** [comment]
Not in this case, I updated the config to remove two EFS Shared Storage, and I made sure the compute fleet was stopped before doing so. 

The larger issue is that while the parallelcluster is successfully able to rolle back PclusterClusterProvider continues to hang UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS  to the point where a tear down of the entire cluster is the only option. 

If the main cluster stack is successfully able to rollback, why won't the ClusterProvider release the stack?

**Comment by francisreyes-tfs** [comment]
Revisiting this  as there seems to be issues when updating EFS storage (with the slurm queues in stopped state). I added 3 EFS storage to my config and had the existing cluster update. The cloudformation log group for pcluster-cfn is telling.

After a successful pull of the config from the s3 config bucket
2024-02-08T09:52:58.725-07:00

Copy
[INFO]	2024-02-08T16:52:58.725Z	XXXXXXXX	Executing boto3 call: region=us-east-1, service=s3, operation=GetObject, params={'Bucket': 'parallelcluster-XXXXXXX-v1-do-not-delete', 'Key': 'parallelcluster/3.8.0/clusters/c-XXXXXXXX-qu63vfskj2rzfhtz/configs/cluster-config.yaml', 'VersionId': 'E8f05jjDyeWSOd.kF_sHPQOPk40jRVPv'}
[INFO] 2024-02-08T16:52:58.725Z XXXXXXXX Executing boto3 call: region=us-east-1, service=s3, operation=GetObject, params={'Bucket': 'parallelcluster-00d85213a64dbdeb-v1-do-not-delete', 'Key': 'parallelcluster/3.8.0/clusters/c-XXXXXXX-qu63vfskj2rzfhtz/configs/cluster-config.yaml', 'VersionId': 'E8f05jjDyeWSOd.kF_sHPQOPk40jRVPv'}

I receive the following error :

[ERROR]	2024-02-08T16:52:58.837Z	XXXXXXX	c-XXXXXXX:  (LogGroup: /aws/lambda/pcluster-cfn-XXXXXXX-a0f5-11ee-89ba-0ad0cc4b996f)
Traceback (most recent call last):
  File "/opt/python/pcluster/resources/custom_resources/custom_resources_code/crhelper/resource_helper.py", line 205, in _wrap_function
    self.PhysicalResourceId = func(self._event, self._context) if func else ''
  File "/var/task/index.py", line 177, in poll_update
    return poll(event)
  File "/var/task/index.py", line 159, in poll
    raise ValueError(f"{cluster_name}: {reasons} (LogGroup: {log_group})")
ValueError: c-XXXXXXX:  (LogGroup: /aws/lambda/pcluster-cfn-XXXXXXX-a0f5-11ee-89ba-0ad0cc4b996f)

At which point pcluster sends 'FAILED' back to the custom resource. 

The resulting XXXXXXX-PclusterClusterProvider resource doesn't seem to get this call, as its stuck in UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS which doesnt seem to go anywhere, and the parent stack stays at UPDATE_ROLLBACK_FAILED. 


Maybe the communication of the FAILED signal to the parent stack is an AWS issue, but I'm more curious on what the issue is with the ValueError raised by resource_helper.py. 

The headnode in this state does not mount the EFS storage volumes as I requested unfortunately. chef-client on the headnode shows that it successfully mounts the volumes, but then proceeds to unmount the volumes (probably because the stack is rolling back)

**Comment by gmarciani** [comment]
Hello @francisreyes-tfs,

Apologies for the delayed response. To properly investigate this issue, we would need the cluster configuration and the logs for both the cluster and the provider covering the time interval when the failure occurred. Given that this is an older issue, it's possible those logs may no longer be available on your end.

If you still have them, please share them with us and we'll be glad to verify whether the latest version resolves the problem.

In the meantime, I'd encourage you to try [v3.15.0](https://github.com/aws/aws-parallelcluster/releases/tag/v3.15.0), which includes improvements to the resiliency of the cluster update workflow.

Thanks!
