### ISSUE TITLE
pcluster image build fails with RHEL 8 and 9

### ISSUE THREAD

**Issue by mclouds2020** [aws/aws-parallelcluster#6567]
We are using pcluster 3.10.0 to build the custom AMI with RHEL 9.0 

During some steps it fails with below message 

Stdout:     dnf_package[install kernel packages] (aws-parallelcluster-platform::install line 29) had an error: Chef::Exceptions::Package: No candidate version available for kernel-devel

Build Template
======
Build:
  InstanceType: c5a.xlarge
  ParentImage: ami-02b7c8c8a886e9e76
  SubnetId: subnet-06ea1d4ec580c651f
  SecurityGroupIds: 
  - sg-07451c683b5b871b6
  Iam:
    AdditionalIamPolicies:
      - Policy: arn:aws:iam::abccccc:policy/stigKMSFullAccess
DevSettings:
  TerminateInstanceOnFailure: False
  DisableValidateAndTest: True

**Comment by mclouds2020** [comment]
StackTrace

```
enerated at 2024-11-14 04:16:55 +0000
Chef::Exceptions::Package: install_packages[Install OS and extra packages] (aws-parallelcluster-platform::install line 19) had an error: Chef::Exceptions::Package: dnf_pac
kage[install kernel packages] (aws-parallelcluster-platform::install line 29) had an error: Chef::Exceptions::Package: No version specified, and no candidate version avail
able for kernel-devel
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/mixin/why_run.rb:238:in `run'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/mixin/why_run.rb:322:in `block in run'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/mixin/why_run.rb:321:in `each'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/mixin/why_run.rb:321:in `run'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/provider.rb:258:in `process_resource_requirements'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/provider.rb:233:in `run_action'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/resource.rb:601:in `block in run_action'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/resource.rb:628:in `with_umask'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/resource.rb:600:in `run_action'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/runner.rb:74:in `run_action'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/runner.rb:108:in `block in run_all_actions'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/runner.rb:108:in `each'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/runner.rb:108:in `run_all_actions'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/resource_collection.rb:64:in `insert'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/dsl/declare_resource.rb:267:in `declare_resource'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/dsl/resources.rb:36:in `package'
(eval):29:in `block in use'
(eval):2:in `block in action_install_kernel_source'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/provider.rb:304:in `instance_eval'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/provider.rb:304:in `compile_and_converge_action'
(eval):2:in `action_install_kernel_source'
(eval):43:in `block in use'
(eval):2:in `block in action_setup'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/provider.rb:304:in `instance_eval'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/provider.rb:304:in `compile_and_converge_action'
(eval):2:in `action_setup'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/provider.rb:245:in `run_action'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/resource.rb:601:in `block in run_action'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/resource.rb:628:in `with_umask'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/resource.rb:600:in `run_action'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/runner.rb:74:in `run_action'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/runner.rb:108:in `block in run_all_actions'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/runner.rb:108:in `each'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/runner.rb:108:in `run_all_actions'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/runner.rb:132:in `block in converge'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/resource_collection/resource_list.rb:96:in `block in execute_each_resource'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/resource_collection/stepable_iterator.rb:54:in `each_with_index'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/resource_collection/resource_list.rb:94:in `execute_each_resource'
/opt/cinc/embedded/lib/ruby/3.1.0/forwardable.rb:238:in `execute_each_resource'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/runner.rb:130:in `converge'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/client.rb:869:in `block in converge'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/client.rb:864:in `catch'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/client.rb:864:in `converge'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/client.rb:888:in `converge_and_save'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/client.rb:298:in `run'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/application.rb:305:in `run_with_graceful_exit_option'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/application.rb:281:in `block in run_chef_client'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/local_mode.rb:42:in `with_server_connectivity'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/application.rb:264:in `run_chef_client'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/application/base.rb:354:in `run_application'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/application.rb:67:in `run'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-bin-18.4.12/bin/cinc-client:25:in `<top (required)>'
/usr/bin/cinc-client:183:in `load'
/usr/bin/cinc-client:183:in `<main>'

>>>> Caused by Chef::Exceptions::Package: No version specified, and no candidate version available for kernel-devel
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/mixin/why_run.rb:238:in `run'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/mixin/why_run.rb:322:in `block in run'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/mixin/why_run.rb:321:in `each'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/mixin/why_run.rb:321:in `run'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/provider.rb:258:in `process_resource_requirements'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/provider.rb:233:in `run_action'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/resource.rb:601:in `block in run_action'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/resource.rb:628:in `with_umask'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/resource.rb:600:in `run_action'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/runner.rb:74:in `run_action'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/runner.rb:108:in `block in run_all_actions'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/runner.rb:108:in `each'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/runner.rb:108:in `run_all_actions'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/resource_collection.rb:64:in `insert'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/dsl/declare_resource.rb:267:in `declare_resource'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/dsl/resources.rb:36:in `package'
(eval):29:in `block in use'
(eval):2:in `block in action_install_kernel_source'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/provider.rb:304:in `instance_eval'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/provider.rb:304:in `compile_and_converge_action'
(eval):2:in `action_install_kernel_source'
(eval):43:in `block in use'
(eval):2:in `block in action_setup'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/provider.rb:304:in `instance_eval'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/provider.rb:304:in `compile_and_converge_action'
(eval):2:in `action_setup'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/provider.rb:245:in `run_action'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/resource.rb:601:in `block in run_action'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/resource.rb:628:in `with_umask'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/resource.rb:600:in `run_action'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/runner.rb:74:in `run_action'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/runner.rb:108:in `block in run_all_actions'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/runner.rb:108:in `each'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/runner.rb:108:in `run_all_actions'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/runner.rb:132:in `block in converge'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/resource_collection/resource_list.rb:96:in `block in execute_each_resource'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/resource_collection/stepable_iterator.rb:54:in `each_with_index'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/resource_collection/resource_list.rb:94:in `execute_each_resource'
/opt/cinc/embedded/lib/ruby/3.1.0/forwardable.rb:238:in `execute_each_resource'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/runner.rb:130:in `converge'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/client.rb:869:in `block in converge'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/client.rb:864:in `catch'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/client.rb:864:in `converge'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/client.rb:888:in `converge_and_save'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/client.rb:298:in `run'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/application.rb:305:in `run_with_graceful_exit_option'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/application.rb:281:in `block in run_chef_client'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/local_mode.rb:42:in `with_server_connectivity'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/application.rb:264:in `run_chef_client'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/application/base.rb:354:in `run_application'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/application.rb:67:in `run'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-bin-18.4.12/bin/cinc-client:25:in `<top (required)>'
/usr/bin/cinc-client:183:in `load'
/usr/bin/cinc-client:183:in `<main>'
```

**Comment by himani2411** [comment]
Hi @mclouds2020 

It looks like the failure is with respect to the `kernel-devel` package not being available w.r.t to kernel version that you have. From the above message I cannot find the kernel version.
I couldnt find the `ami-02b7c8c8a886e9e76` could you specify the region in which it is available?


Are you still facing the issue?

**Comment by Mic-U** [comment]
@mclouds2020

It seems that your AMI does not have valid `kernel-devel` version.
I think that you should confirm if `ami-02b7c8c8a886e9e76` satisfies requirements public doc says.

https://docs.aws.amazon.com/parallelcluster/latest/ug/Image-v3.html
> To build a RedHat Enterprise Linux custom AMI, you must configure the OS for installing the packages that are provided by the RHUI (AWS) repositories: rhel-<version>-baseos-rhui-rpms, rhel-<version>-appstream-rhui-rpms, and codeready-builder-for-rhel-<version>-rhui-rpms. Moreover, the repositories on the custom AMI must contain kernel-devel packages on the same version as the running kernel version. kernel.
