### ISSUE TITLE
Chef unable to find aws-parallelcluster cookbook on cluster creation

### ISSUE THREAD

**Issue by tgjohnst** [aws/aws-parallelcluster#826]
**Environment:**
 - AWS ParallelCluster / CfnCluster version: ParallelCluster 2.1.1
 - OS: ubuntu 16.04
 - Scheduler: sge
 - Master instance type: r3.2xlarge
 - Compute instance type: r3.2xlarge

**Bug description and how to reproduce:**
We are undergoing an update from Cfncluster 1.6.1 to ParallelCluster 2.1.1 . Our cluster uses a custom AMI modified using Packer from the provided source cfn/parallelcluster AMI for 16.04 which has always worked within cfncluster up to this point. I used packer to generate the new AMI after modifying the configuration to point to the new source AMI (in this case, ami-021d8e65c14865c94) and encountered no issues. I then installed ParallelCluster on my local machine and ported our existing cfncluster configuration file over to parallelcluster (modifying it to include the new AMI, the appropriate parallelcluster.cfn.json template, etc.). However, when I then `pcluster create` with this configuration, the master node sends a failure signal and the cluster cannot be created. I ran again with norollback and checked cfn-init.log, and the error boils down to chef being unable to find the aws-parallelcluster cookbook when running aws-parallelcluster::_prep_env on instance startup. I poked around the node and I can see what appears to be a cfncluster 1.6.0 cookbook located in /etc/chef/cookbooks/cfncluster. I can also see the appropriate parallelcluster cookbook located in /tmp/cookbooks/aws-parallelcluster-cookbook-2.1.1/ but not in /etc/chef/cookbooks. Has anyone else encountered this issue? Any ideas as to why chef is unable to find the parallelcluster cookbook?

**Additional context:**
cfn-init.log excerpt:

```
2019-01-09 22:07:15,125 [DEBUG] CloudFormation client initialized with endpoint https://cloudformation.us-west-2.amazonaws.com
2019-01-09 22:07:15,125 [DEBUG] Describing resource MasterServer in stack parallelcluster-discovery
2019-01-09 22:07:15,341 [INFO] -----------------------Starting build-----------------------
2019-01-09 22:07:15,342 [DEBUG] Not setting a reboot trigger as scheduling support is not available
2019-01-09 22:07:15,343 [INFO] Running configSets: default
2019-01-09 22:07:15,344 [INFO] Running configSet default
2019-01-09 22:07:15,346 [INFO] Running config deployConfigFiles
2019-01-09 22:07:15,346 [DEBUG] No packages specified
2019-01-09 22:07:15,346 [DEBUG] No groups specified
2019-01-09 22:07:15,347 [DEBUG] No users specified
2019-01-09 22:07:15,347 [DEBUG] No sources specified
2019-01-09 22:07:15,347 [DEBUG] Writing content to /etc/chef/client.rb
2019-01-09 22:07:15,347 [DEBUG] Setting mode for /etc/chef/client.rb to 000644
2019-01-09 22:07:15,347 [DEBUG] Setting owner 0 and group 0 for /etc/chef/client.rb
2019-01-09 22:07:15,348 [DEBUG] Writing content to /tmp/dna.json
2019-01-09 22:07:15,348 [DEBUG] Content will be serialized as a JSON structure
2019-01-09 22:07:15,348 [DEBUG] Setting mode for /tmp/dna.json to 000644
2019-01-09 22:07:15,348 [DEBUG] Setting owner 0 and group 0 for /tmp/dna.json
2019-01-09 22:07:15,348 [DEBUG] Writing content to /tmp/extra.json
2019-01-09 22:07:15,349 [DEBUG] Setting mode for /tmp/extra.json to 000644
2019-01-09 22:07:15,349 [DEBUG] Setting owner 0 and group 0 for /tmp/extra.json
2019-01-09 22:07:15,349 [DEBUG] Running command jq
2019-01-09 22:07:15,349 [DEBUG] No test for command jq
2019-01-09 22:07:15,467 [INFO] Command jq succeeded
2019-01-09 22:07:15,467 [DEBUG] Command jq output:
2019-01-09 22:07:15,467 [DEBUG] Running command mkdir
2019-01-09 22:07:15,467 [DEBUG] No test for command mkdir
2019-01-09 22:07:15,472 [INFO] Command mkdir succeeded
2019-01-09 22:07:15,472 [DEBUG] Command mkdir output:
2019-01-09 22:07:15,472 [DEBUG] Running command touch
2019-01-09 22:07:15,472 [DEBUG] No test for command touch
2019-01-09 22:07:15,475 [INFO] Command touch succeeded
2019-01-09 22:07:15,475 [DEBUG] Command touch output:
2019-01-09 22:07:15,475 [DEBUG] No services specified
2019-01-09 22:07:15,478 [INFO] Running config getCookbooks
2019-01-09 22:07:15,478 [DEBUG] No packages specified
2019-01-09 22:07:15,479 [DEBUG] No groups specified
2019-01-09 22:07:15,479 [DEBUG] No users specified
2019-01-09 22:07:15,479 [DEBUG] No sources specified
2019-01-09 22:07:15,479 [DEBUG] No files specified
2019-01-09 22:07:15,479 [DEBUG] Running command berk
2019-01-09 22:07:15,479 [DEBUG] No test for command berk
2019-01-09 22:07:15,483 [INFO] Command berk succeeded
2019-01-09 22:07:15,483 [DEBUG] Command berk output:
2019-01-09 22:07:15,483 [DEBUG] No services specified
2019-01-09 22:07:15,485 [INFO] Running config chefPrepEnv
2019-01-09 22:07:15,486 [DEBUG] No packages specified
2019-01-09 22:07:15,486 [DEBUG] No groups specified
2019-01-09 22:07:15,486 [DEBUG] No users specified
2019-01-09 22:07:15,486 [DEBUG] No sources specified
2019-01-09 22:07:15,486 [DEBUG] No files specified
2019-01-09 22:07:15,486 [DEBUG] Running command chef
2019-01-09 22:07:15,486 [DEBUG] No test for command chef
2019-01-09 22:07:32,598 [ERROR] Command chef (chef-client --local-mode --config /etc/chef/client.rb --log_level auto --force-formatter --no-color --chef-zero-port 8889 --json-attributes /etc/chef/dna.json --override-runlist aws-parallelcluster::_prep_env) failed
2019-01-09 22:07:32,598 [DEBUG] Command chef output: Starting Chef Client, version 14.2.0
[2019-01-09T22:07:32+00:00] WARN: Run List override has been provided.
[2019-01-09T22:07:32+00:00] WARN: Run List override has been provided.
[2019-01-09T22:07:32+00:00] WARN: Original Run List: [recipe[aws-parallelcluster::sge_config]]
[2019-01-09T22:07:32+00:00] WARN: Original Run List: [recipe[aws-parallelcluster::sge_config]]
[2019-01-09T22:07:32+00:00] WARN: Overridden Run List: [recipe[aws-parallelcluster::_prep_env]]
[2019-01-09T22:07:32+00:00] WARN: Overridden Run List: [recipe[aws-parallelcluster::_prep_env]]
resolving cookbooks for run list: ["aws-parallelcluster::_prep_env"]

================================================================================
Error Resolving Cookbooks for Run List:
================================================================================

Missing Cookbooks:
------------------
No such cookbook: aws-parallelcluster

Expanded Run List:
------------------
* aws-parallelcluster::_prep_env

System Info:
------------
chef_version=14.2.0
platform=ubuntu
platform_version=16.04
ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
program_name=/usr/bin/chef-client
executable=/opt/chef/bin/chef-client


Running handlers:
[2019-01-09T22:07:32+00:00] ERROR: Running exception handlers
[2019-01-09T22:07:32+00:00] ERROR: Running exception handlers
Running handlers complete
[2019-01-09T22:07:32+00:00] ERROR: Exception handlers complete
[2019-01-09T22:07:32+00:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 15 seconds
[2019-01-09T22:07:32+00:00] FATAL: Stacktrace dumped to /etc/chef/local-mode-cache/cache/chef-stacktrace.out
[2019-01-09T22:07:32+00:00] FATAL: Stacktrace dumped to /etc/chef/local-mode-cache/cache/chef-stacktrace.out
[2019-01-09T22:07:32+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2019-01-09T22:07:32+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2019-01-09T22:07:32+00:00] FATAL: Net::HTTPServerException: 412 "Precondition Failed"
[2019-01-09T22:07:32+00:00] FATAL: Net::HTTPServerException: 412 "Precondition Failed"

2019-01-09 22:07:32,599 [ERROR] Error encountered during build of chefPrepEnv: Command chef failed
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 542, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 260, in build
    changes['commands'] = CommandTool().apply(self._config.commands)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/command_tool.py", line 117, in apply
    raise ToolError(u"Command %s failed" % name)
ToolError: Command chef failed
2019-01-09 22:07:32,601 [ERROR] -----------------------BUILD FAILED!------------------------
2019-01-09 22:07:32,601 [ERROR] Unhandled exception during build: Command chef failed
Traceback (most recent call last):
  File "/usr/local/bin/cfn-init", line 171, in <module>
    worklog.build(metadata, configSets)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 129, in build
    Contractor(metadata).build(configSets, self)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 530, in build
    self.run_config(config, worklog)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 542, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 260, in build
    changes['commands'] = CommandTool().apply(self._config.commands)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/command_tool.py", line 117, in apply
    raise ToolError(u"Command %s failed" % name)
ToolError: Command chef failed
2019-01-09 22:07:32,837 [DEBUG] CloudFormation client initialized with endpoint https://cloudformation.us-west-2.amazonaws.com
2019-01-09 22:07:32,837 [DEBUG] Signaling resource MasterServer in stack parallelcluster-discovery with unique ID i-00773fd0a3ce13ede and status FAILURE
```
pcluster config file:
```
## pcluster config
[global]
# Default cluster config section.
cluster_template = discovery
# Check for updates
update_check = true
# Check config sanity. (Attempts to validate resources defined in parameters, actually exist)
sanity_check = true

[aws]
# This is the AWS credentials section (required).
# These settings apply to all clusters
# replace these with your AWS keys
# If not defined, boto will attempt to use a) enviornment
# or b) EC2 IAM role.
aws_access_key_id = <CENSORED>
aws_secret_access_key = <CENSORED>
# Uncomment to specify a different Amazon AWS region  (OPTIONAL)
# (Defaults to us-east-1 if not defined in enviornment or below)
aws_region_name = us-west-2

[aliases]
# This is the aliases section, you can configure
# ssh alias here
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}

## pcluster templates
[cluster default]
# Name of an existing EC2 KeyPair to enable SSH access to the instances.
key_name = bean_key
# Override path to cloudformation in S3
# (defaults to https://s3.amazonaws.com/<aws_region_name>-aws-parallelcluster/templates/parallelcluster-<version>.cfn.json)
template_url = https://<CENSORED>/aws-parallelcluster.cfn.json
# Cluster Server EC2 instance type
# (defaults to t2.micro for default template)
compute_instance_type = r3.2xlarge
# Master Server EC2 instance type
# (defaults to t2.micro for default template
master_instance_type = r3.2xlarge
# Inital number of EC2 instances to launch as compute nodes in the cluster.
# (defaults to 2 for default template)
initial_queue_size = 2
# Maximum number of EC2 instances that can be launched in the cluster.
# (defaults to 10 for the default template)
max_queue_size = 35
# Boolean flag to set autoscaling group to maintain initial size and scale back
# (defaults to false for the default template)
maintain_initial_size = true
# Minimum number of vcpus that will be running when scheduler is awsbatch.
# defaults to 0
#min_vcpus = 0
# Initial number of vcpus to launch when scheduler is awsbatch.
# defaults to 4
#desired_vcpus = 4
# Maximum number of vcpus that can be launched when scheduler is awsbatch.
#max_vcpus = 20
# Cluster scheduler
# (defaults to sge for the default template)
#scheduler = sge
# Type of cluster to launch i.e. ondemand or spot
# (defaults to ondemand for the default template)
#cluster_type = spot
# Spot price for the ComputeFleet
#spot_price = 0.00
# Spot bid percentage when the scheduler is set to awsbatch. Should be between 0 and 100
#spot_bid_percentage = 85
# ID of a Custom AMI, to use instead of published AMI's
custom_ami = <CENSORED>
# Specify S3 resource which pcluster nodes will be granted read-only access
# (defaults to NONE for the default template)
#s3_read_resource = arn:aws:s3:::inputs
# Specify S3 resource which pcluster nodes will be granted read-write access
# (defaults to NONE for the default template)
#s3_read_write_resource = arn:aws:s3:::inputs/*
# URL to a preinstall script. This is executed before any of the boot_as_* scripts are run
# (defaults to NONE for the default template)
#pre_install = NONE
# Arguments to be passed to preinstall script
# (defaults to NONE for the default template)
#pre_install_args = NONE
# URL to a postinstall script. This is executed after any of the boot_as_* scripts are run
# (defaults to NONE for the default template)
post_install = https:/<CENSORED>/post_install_all.sh
# Arguments to be passed to postinstall script
# (defaults to NONE for the default template)
# post_install_args =NONE
# HTTP(S) proxy server, typically http://x.x.x.x:8080
# (defaults to NONE for the default template)
#proxy_server = NONE
# Cluster placement group. This placement group must already exist.
# (defaults to NONE for the default template)
#placement_group = NONE
# Cluster placment logic. This enables the whole cluster or only compute to use the placement group
# (defaults to cluster in the default template)
#placement = cluster
# MasterServer root volume size in GB. (AMI must support growroot)
# (defaults to 10 in default template)
master_root_volume_size = 100
# ComputeFleet root volume size in GB. (AMI must support growroot)
# (defaults to 10 in default template)
compute_root_volume_size = 50
# Path/mountpoint for ephemeral drives
# (defaults to /scratch in the default template)
#ephemeral_dir = /scratch
# Path/mountpoint for shared EBS volume
# (defaults to /shared in the default template)
#shared_dir = /shared
# Encrypted ephemeral drives. In-memory keys, non-recoverable.
# (defaults to false in default template)
#encrypted_ephemeral = false
# OS type used in the cluster
# (defaults to centos6 in the default template)
base_os = ubuntu1604
# CloudWatch Logs region
# (defaults to NONE in the default template)
#cwl_region = us-east-1
# CloudWatch Logs Log Group name
# (defaults to NONE in the default template
#cwl_log_group = pcluster
# Existing EC2 IAM role to be assosiated with the EC2 instances
# (defaults to NONE in the default template)
ec2_iam_role = ParallelClusterInstanceRole
# Extra Json to be merged with the dna.json used by Chef
# (defaults to {} in the default template)
#extra_json = {}
# Settings section relating to VPC to be used
vpc_settings = public
# Settings section relating to EBS volume
#ebs_settings = custom
# Settings section relation to scaling
#scaling_settings = custom

## VPC Settings
[vpc public]
vpc_id = <CENSORED>
master_subnet_id = <CENSORED>
# SSH from CIDR
# This is only used when pcluster creates the security group
# (defaults to 0.0.0.0/0 in the default template)
# rather than having it all open by default, restrict to 320WL by default. Additional
#  access is configured in the security groups
# ssh_from = 50.233.20.206/32
# Additional VPC security group Id for all instances
# (defaults to NONE in the default template)
# this is pcluster all, which allows access within and around cluster
additional_sg = <CENSORED>
# Existing EC2 security group to be assosiated with the EC2 instances
# (defaults to NONE in the default template)
# this is juno-access, which allows whitelisted broad access
vpc_security_group_id = <CENSORED>

#[vpc private-new]
# ID of the VPC you want to provision cluster into.
#vpc_id = vpc-
# ID of the Subnet you want to provision the Master server into
#master_subnet_id = subnet-
# CIDR for new backend subnet i.e. 10.0.100.0/24
#compute_subnet_cidr = 10.0.100.0/24

#[vpc private-existing]
# ID of the VPC you want to provision cluster into.
#vpc_id =
# ID of the Subnet you want to provision the Master server into
#master_subnet_id = subnet-
# CIDR for new backend subnet i.e. 10.0.100.0/24
#compute_subnet_id = subnet-

## First EBS Settings
#[ebs custom1]
# Path/mountpoint for shared EBS volume. REQUIRED when using > 1 EBS volumes. Example below mounts to /vol1
#shared_dir = vol1
# Id of EBS snapshot if using snapshot as source for volume
# (defaults to NONE for default template)
#ebs_snapshot_id = snap-
# Type of volume to create either new or from snapshot
# (defaults to gp2 for default template)
#volume_type = io1
# Size of volume to be created if not using a snapshot
# (defaults to 20GB for default template)
#volume_size = 20
# Number of IOPS for io1 type volumes
#volume_iops = 200
# Use encrypted volume (should not be used with snapshots)
# (defaults to false for default template)
#encrypted = false
# Existing EBS volume to be attached to the MasterServer
# (defaults to NONE)
#ebs_volume_id = NONE

## Second EBS Settings
#[ebs custom2]
# Path/mountpoint for shared EBS volume. REQUIRED when using > 1 EBS volumes. Example below mounts to /vol2
#shared_dir = vol2
# ... More EBS options if needed

## More EBS settings if needed. Supports up to 5 volumes in total
#[ebs ...]
#shared_dir = ...
# ... More EBS options if needed

## Scaling settings
#[scaling custom]
# Threshold for triggering CloudWatch ScaleUp action
# (defaults to 4 for default template)
scaling_threshold = 1
# Number of instances to add when called CloudWatch ScaleUp action
# (defaults to 2 for default template)
scaling_adjustment = 1
# Threshold for triggering CloudWatch ScaleUp action
# (defaults to 4 for default template)
scaling_threshold2 = 10
# Number of instances to add when called CloudWatch ScaleUp2 action
# (defaults to 20 for default template)
scaling_adjustment2 = 2
# Period to measure ScalingThreshold
# (defaults to 60 for default template)
scaling_period = 60
# Period to measure ScalingThreshold
# (defaults to 2 for default template)
scaling_evaluation_periods = 1
# Amount of time in seconds to wait before attempting further scaling actions
# (defaults to 120 for the default template
scaling_cooldown = 300
# idle time without receiving a job before shutting down, now that billing is per minute
scaledown_idletime = 10

## EFS Settings
#[efs customfs]
# Shared directory for the file system. REQUIRED if using EFS file system. Below example mounts to /efs
shared_dir = efs
# Use encrypted file system
# (defaults to false)
#encrypted = false
# Performance Mode of the file system; generalPurpose or maxIO (case sensitive)
# (defaults to generalPurpose)
#performance_mode = generalPurpose
# Throughput mode of the file system; bursting or provisioned (case sensitive)
# (defaults to bursting)
#throughput_mode = provisioned
# The throughput, measured in MiB/s, that you want to provision for a file system that you're creating. The limit on throughput is 0.0 - 1024 MiB/s. You can get these limits increased by contacting AWS Support.
# Can only be used when throughput_mode is set to provisioned
# (defaults to NONE)
#provisioned_throughput = 1024
# File system ID of an existing EFS file system to use. Specifying this option will void all EFS options but shared_dir
# Requires the given file system to: not have a mount target in the stack's availability zone OR have a mount target with inbound and outbound permissions for NFS traffic from 0.0.0.0/0
# (defaults to NONE)
efs_fs_id = <CENSORED>

## RAID Settings
#[raid rs]
# Shared directory for the RAID drive. REQUIRED if using RAID drive.  Below example mounts to /raid
#shared_dir = raid
# RAID type for the drive. REQUIRED if using RAID drive. Allowed values are 0 and 1.
#raid_type = 1
# Number of EBS volumes to use with RAID, min of 2 and max of 5
# (defaults to 2)
#num_of_raid_volumes = 4
# Type of volume for the RAID volumes
# (defaults to gp2)
#volume_type = io1
# Size of volumes to be created
# (defaults to 20GB)
#volume_size = 20
# Number of IOPS for io1 type volumes
#volume_iops = 500
# Use encrypted volume
# (defaults to false)
#encrypted = false

# Make sure ganglia is enabled for cluster monitoring. This requires port 80 access
extra_json = { "cluster" : { "ganglia_enabled" : "yes" } }

```

**Comment by sean-smith** [comment]
Hi,

When we create ami's we use packer to copy the cookbook into `/etc/chef`, this is done for every version we release.

See https://github.com/aws/aws-parallelcluster-cookbook/blob/34b915feab6d3d607310ef8673d479f70ad34acd/amis/packer_alinux.json#L235

I think in your case, it thinks the instance is already bootstrapped (`/opt/parallelcluster/.bootstrapped` exists) since you're using an older ami and it skips the download cookbook step. Where is the ami you're using coming from?

**Comment by tgjohnst** [comment]
Thanks Sean for your quick response! I just checked back when trying to address your response, and I believe I may have forgotten to update the custom_ami in the ParallelCluster config to reflect the new one we just built, hence the cfncluster cookbook being present but not the parallelcluster one. whoops :man_facepalming:
