### ISSUE TITLE
v2.1.1 fails when using a proxy due to fatal parse/config error in attachVolume.py

### ISSUE THREAD

**Issue by chrisdag** [aws/aws-parallelcluster#832]
**Environment:**
 - AWS ParallelCluster 2.1.1
 - OS: Centos6
 - Scheduler: SGE
 - Master instance type:  m1.large
 - Compute instance type: m1.large

**Bug description and how to reproduce:**

I need to run parallelcluster or cfncluster in a VPC that only has private subnets and EC2 nodes are not allowed internet access by default. I have a different issue filed related to proxy errors with version 2.0.2 (issue #726 ) still outstanding

This new error was seen after doing a pip upgrade to aws-parallelcluster 2.1.1

Steps to reproduce:

 - Set a proxy_server to either "http://<IP>:port" or "https://<ip>:<port>"  

Try to launch a cluster. The master node will fail to deploy and the /var/log/cfn-init.log will show a fatal error when /usr/local/sbin/attachVolume.py is called 

**Additional context:**

This is the error with Centos7, SGE and setting proxy_server to an "https://<ip>:<port>" value:

>     ================================================================================
    Error executing action `run` on resource 'execute[attach_volume_0]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of /usr/local/sbin/attachVolume.py vol-0ae44c77577b4da23 ----
    STDOUT:
    STDERR: Traceback (most recent call last):
      File "/usr/local/sbin/attachVolume.py", line 90, in <module>
        main()
      File "/usr/local/sbin/attachVolume.py", line 61, in main
        proxy_config = Config(proxies={'https': "{}:{}".format(proxy, proxy_port)})
    ValueError: zero length field name in format
    ---- End output of /usr/local/sbin/attachVolume.py vol-0ae44c77577b4da23 ----
    Ran /usr/local/sbin/attachVolume.py vol-0ae44c77577b4da23 returned 1

    Resource Declaration:
    ---------------------
    # In /etc/chef/local-mode-cache/cache/cookbooks/aws-parallelcluster/recipes/_master_base_config.rb

     54:   execute "attach_volume_#{index}" do
     55:     command "/usr/local/sbin/attachVolume.py #{volumeid}"
     56:     creates dev_path[index]
     57:   end
     58:

    Compiled Resource:
    ------------------
    # Declared in /etc/chef/local-mode-cache/cache/cookbooks/aws-parallelcluster/recipes/_master_base_config.rb:54:in `block in from_file'

    execute("attach_volume_0") do
      action [:run]
      default_guard_interpreter :execute
      command "/usr/local/sbin/attachVolume.py vol-0ae44c77577b4da23"
      backup 5
      declared_type :execute
      cookbook_name "aws-parallelcluster"
      recipe_name "_master_base_config"
      domain nil
      user nil
      creates "/dev/disk/by-ebs-volumeid/vol-0ae44c77577b4da23"
    end

    System Info:
    ------------
    chef_version=14.2.0
    platform=centos
    platform_version=6.9
    ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
    program_name=/usr/bin/chef-client
    executable=/opt/chef/bin/chef-client

Thinking I also replaced the HTTPS proxy URL with one that was HTTP instead and this is the output on that failed deploy:

> 2019-01-23 15:11:05,418 P2282 [INFO] 	[2019-01-23T15:11:05+00:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: execute[attach_volume_0] (aws-parallelcluster::_master_base_config line 54) had an error: Mix
lib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
2019-01-23 15:11:05,418 P2282 [INFO] 	---- Begin output of /usr/local/sbin/attachVolume.py vol-086992b1924c892a2 ----
2019-01-23 15:11:05,419 P2282 [INFO] 	STDOUT:
2019-01-23 15:11:05,419 P2282 [INFO] 	STDERR: Traceback (most recent call last):
2019-01-23 15:11:05,419 P2282 [INFO] 	  File "/usr/local/sbin/attachVolume.py", line 90, in <module>
2019-01-23 15:11:05,419 P2282 [INFO] 	    main()
2019-01-23 15:11:05,419 P2282 [INFO] 	  File "/usr/local/sbin/attachVolume.py", line 61, in main
2019-01-23 15:11:05,420 P2282 [INFO] 	    proxy_config = Config(proxies={'https': "{}:{}".format(proxy, proxy_port)})
2019-01-23 15:11:05,420 P2282 [INFO] 	ValueError: zero length field name in format
2019-01-23 15:11:05,420 P2282 [INFO] 	---- End output of /usr/local/sbin/attachVolume.py vol-086992b1924c892a2 ----
2019-01-23 15:11:05,420 P2282 [INFO] 	Ran /usr/local/sbin/attachVolume.py vol-086992b1924c892a2 returned 1
2019-01-23 15:11:05,420 P2282 [INFO] 	[2019-01-23T15:11:05+00:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: execute[attach_volume_0] (aws-parallelcluster::_master_base_config line 54) had an error: Mix
lib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
2019-01-23 15:11:05,420 P2282 [INFO] 	---- Begin output of /usr/local/sbin/attachVolume.py vol-086992b1924c892a2 ----
2019-01-23 15:11:05,421 P2282 [INFO] 	STDOUT:
2019-01-23 15:11:05,421 P2282 [INFO] 	STDERR: Traceback (most recent call last):
2019-01-23 15:11:05,421 P2282 [INFO] 	  File "/usr/local/sbin/attachVolume.py", line 90, in <module>
2019-01-23 15:11:05,421 P2282 [INFO] 	    main()
2019-01-23 15:11:05,421 P2282 [INFO] 	  File "/usr/local/sbin/attachVolume.py", line 61, in main
2019-01-23 15:11:05,421 P2282 [INFO] 	    proxy_config = Config(proxies={'https': "{}:{}".format(proxy, proxy_port)})
2019-01-23 15:11:05,422 P2282 [INFO] 	ValueError: zero length field name in format
2019-01-23 15:11:05,422 P2282 [INFO] 	---- End output of /usr/local/sbin/attachVolume.py vol-086992b1924c892a2 ----
2019-01-23 15:11:05,422 P2282 [INFO] 	Ran /usr/local/sbin/attachVolume.py vol-086992b1924c892a2 returned 1
2019-01-23 15:11:05,422 P2282 [INFO] ------------------------------------------------------------
2019-01-23 15:11:05,422 P2282 [ERROR] Exited with error code 1

**Comment by chrisdag** [comment]
Update:   This issue happens to me on Centos6  (did not test Centos7)

And specifically this is a python 2.6 bug related to line 61 of attachVolume.py:

This line:
`proxy_config = Config(proxies={'https': "{}:{}".format(proxy, proxy_port)})`

I think needs to look like this on python 2.6.6. which is what I see inside CentOs 6:
`proxy_config = Config(proxies={'https': "{0}:{1}".format(proxy, proxy_port)})`
