### ISSUE TITLE
Master node launch failure

### ISSUE THREAD

**Issue by carlitador** [aws/aws-parallelcluster#840]
Hi everybody,
I updated from cfncluster to parallelcluster recently.
I have a configuration which worked on cfncluster and crashes with parallelcluster. The only thing I added is the EFS configuration and the new security group.
My configuration looks like this :
```

[aws]
aws_region_name = us-east-1
aws_access_key_id = XXX
aws_secret_access_key =XXX

[cluster default]
vpc_settings = public
key_name = XXX
compute_instance_type = t2.micro
master_instance_type = t2.micro
initial_queue_size = 0
max_queue_size = 2
maintain_initial_size = false
custom_ami = ami-XXX
master_root_volume_size = 20
compute_root_volume_size = 20
efs_settings = customfs
additional_sg = sg-XXX

[vpc public]
master_subnet_id = subnet-XXX
vpc_id = vpc-XXX

[global]
update_check = true
sanity_check = true
cluster_template = default

[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}


[efs customfs]
shared_dir = efs
encrypted = false
performance_mode = generalPurpose
efs_fs_id = fs-XXX
```

And it gives me this error :

```
Creating stack named: parallelcluster-mycluster
Status: parallelcluster-mycluster - ROLLBACK_IN_PROGRESS                        
Cluster creation failed.  Failed events:
  - AWS::EC2::Instance MasterServer Received FAILURE signal with UniqueId i-07af1cb218dd6a081

```

Thank you for you help
Bye
```

**Comment by sean-smith** [comment]
Hi @carlitador 

Please re-run creation with the `--norollback` flag and check the output of `/var/log/cfn-init.log` and `/var/log/cloud-init-output.log`. Also take a look at the special requirements for EFS (when you provide a `efs_fs_id `):

https://aws-parallelcluster.readthedocs.io/en/latest/configuration.html#efs-fs-id

**Comment by carlitador** [comment]
> 
> 
> Hi @carlitador
> 
> Please re-run creation with the `--norollback` flag and check the output of `/var/log/cfn-init.log` and `/var/log/cloud-init-output.log`. Also take a look at the special requirements for EFS (when you provide a `efs_fs_id `):
> 
> https://aws-parallelcluster.readthedocs.io/en/latest/configuration.html#efs-fs-id

Hi @sean-smith,
I used the command but nothing appears in /var/log. Are you sure of the directory ? 
Thank you

**Comment by carlitador** [comment]
@sean-smith  I am sorry I didnt look at the right place.
Here is cfn-init.log 
```
2019-01-30 00:01:16,628 [DEBUG] CloudFormation client initialized with endpoint https://cloudformation.us-east-1.amazonaws.com
2019-01-30 00:01:16,629 [DEBUG] Describing resource MasterServer in stack parallelcluster-mycluster
2019-01-30 00:01:16,743 [INFO] -----------------------Starting build-----------------------
2019-01-30 00:01:16,744 [DEBUG] Not setting a reboot trigger as scheduling support is not available
2019-01-30 00:01:16,745 [INFO] Running configSets: default
2019-01-30 00:01:16,747 [INFO] Running configSet default
2019-01-30 00:01:16,748 [INFO] Running config deployConfigFiles
2019-01-30 00:01:16,749 [DEBUG] No packages specified
2019-01-30 00:01:16,749 [DEBUG] No groups specified
2019-01-30 00:01:16,749 [DEBUG] No users specified
2019-01-30 00:01:16,749 [DEBUG] No sources specified
2019-01-30 00:01:16,749 [DEBUG] Writing content to /etc/chef/client.rb
2019-01-30 00:01:16,749 [DEBUG] Setting mode for /etc/chef/client.rb to 000644
2019-01-30 00:01:16,749 [DEBUG] Setting owner 0 and group 0 for /etc/chef/client.rb
2019-01-30 00:01:16,750 [DEBUG] Writing content to /tmp/dna.json
2019-01-30 00:01:16,750 [DEBUG] Content will be serialized as a JSON structure
2019-01-30 00:01:16,750 [DEBUG] Setting mode for /tmp/dna.json to 000644
2019-01-30 00:01:16,750 [DEBUG] Setting owner 0 and group 0 for /tmp/dna.json
2019-01-30 00:01:16,750 [DEBUG] Writing content to /tmp/extra.json
2019-01-30 00:01:16,750 [DEBUG] Setting mode for /tmp/extra.json to 000644
2019-01-30 00:01:16,751 [DEBUG] Setting owner 0 and group 0 for /tmp/extra.json
2019-01-30 00:01:16,751 [DEBUG] Running command jq
2019-01-30 00:01:16,751 [DEBUG] No test for command jq
2019-01-30 00:01:16,757 [INFO] Command jq succeeded
2019-01-30 00:01:16,757 [DEBUG] Command jq output: 
2019-01-30 00:01:16,757 [DEBUG] Running command mkdir
2019-01-30 00:01:16,758 [DEBUG] No test for command mkdir
2019-01-30 00:01:16,761 [INFO] Command mkdir succeeded
2019-01-30 00:01:16,761 [DEBUG] Command mkdir output: 
2019-01-30 00:01:16,761 [DEBUG] Running command touch
2019-01-30 00:01:16,761 [DEBUG] No test for command touch
2019-01-30 00:01:16,764 [INFO] Command touch succeeded
2019-01-30 00:01:16,765 [DEBUG] Command touch output: 
2019-01-30 00:01:16,765 [DEBUG] No services specified
2019-01-30 00:01:16,767 [INFO] Running config getCookbooks
2019-01-30 00:01:16,767 [DEBUG] No packages specified
2019-01-30 00:01:16,767 [DEBUG] No groups specified
2019-01-30 00:01:16,767 [DEBUG] No users specified
2019-01-30 00:01:16,767 [DEBUG] No sources specified
2019-01-30 00:01:16,767 [DEBUG] No files specified
2019-01-30 00:01:16,767 [DEBUG] Running command berk
2019-01-30 00:01:16,767 [DEBUG] No test for command berk
2019-01-30 00:01:16,771 [INFO] Command berk succeeded
2019-01-30 00:01:16,771 [DEBUG] Command berk output: 
2019-01-30 00:01:16,771 [DEBUG] No services specified
2019-01-30 00:01:16,773 [INFO] Running config chefPrepEnv
2019-01-30 00:01:16,773 [DEBUG] No packages specified
2019-01-30 00:01:16,773 [DEBUG] No groups specified
2019-01-30 00:01:16,773 [DEBUG] No users specified
2019-01-30 00:01:16,773 [DEBUG] No sources specified
2019-01-30 00:01:16,773 [DEBUG] No files specified
2019-01-30 00:01:16,773 [DEBUG] Running command chef
2019-01-30 00:01:16,774 [DEBUG] No test for command chef
2019-01-30 00:01:20,690 [ERROR] Command chef (chef-client --local-mode --config /etc/chef/client.rb --log_level auto --force-formatter --no-color --chef-zero-port 8889 --json-attributes /etc/chef/dna.json --override-runlist aws-parallelcluster::_prep_env) failed
2019-01-30 00:01:20,690 [DEBUG] Command chef output: Starting Chef Client, version 14.2.0
[2019-01-30T00:01:20+00:00] WARN: Run List override has been provided.
[2019-01-30T00:01:20+00:00] WARN: Run List override has been provided.
[2019-01-30T00:01:20+00:00] WARN: Original Run List: [recipe[aws-parallelcluster::sge_config]]
[2019-01-30T00:01:20+00:00] WARN: Original Run List: [recipe[aws-parallelcluster::sge_config]]
[2019-01-30T00:01:20+00:00] WARN: Overridden Run List: [recipe[aws-parallelcluster::_prep_env]]
[2019-01-30T00:01:20+00:00] WARN: Overridden Run List: [recipe[aws-parallelcluster::_prep_env]]
resolving cookbooks for run list: ["aws-parallelcluster::_prep_env"]

================================================================================
Error Resolving Cookbooks for Run List:
================================================================================

Missing Cookbooks:
------------------
No such cookbook: aws-parallelcluster

Expanded Run List:
------------------
* aws-parallelcluster::_prep_env

System Info:
------------
chef_version=14.2.0
platform=amazon
platform_version=2
ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
program_name=/bin/chef-client
executable=/opt/chef/bin/chef-client


Running handlers:
[2019-01-30T00:01:20+00:00] ERROR: Running exception handlers
[2019-01-30T00:01:20+00:00] ERROR: Running exception handlers
Running handlers complete
[2019-01-30T00:01:20+00:00] ERROR: Exception handlers complete
[2019-01-30T00:01:20+00:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 02 seconds
[2019-01-30T00:01:20+00:00] FATAL: Stacktrace dumped to /etc/chef/local-mode-cache/cache/chef-stacktrace.out
[2019-01-30T00:01:20+00:00] FATAL: Stacktrace dumped to /etc/chef/local-mode-cache/cache/chef-stacktrace.out
[2019-01-30T00:01:20+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2019-01-30T00:01:20+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2019-01-30T00:01:20+00:00] FATAL: Net::HTTPServerException: 412 "Precondition Failed"
[2019-01-30T00:01:20+00:00] FATAL: Net::HTTPServerException: 412 "Precondition Failed"

2019-01-30 00:01:20,691 [ERROR] Error encountered during build of chefPrepEnv: Command chef failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 542, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 260, in build
    changes['commands'] = CommandTool().apply(self._config.commands)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/command_tool.py", line 117, in apply
    raise ToolError(u"Command %s failed" % name)
ToolError: Command chef failed
2019-01-30 00:01:20,743 [ERROR] -----------------------BUILD FAILED!------------------------
2019-01-30 00:01:20,754 [ERROR] Unhandled exception during build: Command chef failed
Traceback (most recent call last):
  File "/opt/aws/bin/cfn-init", line 171, in <module>
    worklog.build(metadata, configSets)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 129, in build
    Contractor(metadata).build(configSets, self)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 530, in build
    self.run_config(config, worklog)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 542, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 260, in build
    changes['commands'] = CommandTool().apply(self._config.commands)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/command_tool.py", line 117, in apply
    raise ToolError(u"Command %s failed" % name)
ToolError: Command chef failed
2019-01-30 00:01:21,177 [DEBUG] CloudFormation client initialized with endpoint https://cloudformation.us-east-1.amazonaws.com
2019-01-30 00:01:21,182 [DEBUG] Signaling resource MasterServer in stack parallelcluster-mycluster with unique ID i-06338db54db0574d5 and status FAILURE
```

**Comment by carlitador** [comment]
Hi @sean-smith,
Let me clarify:
- Same config file without the custom ami -> working. EFS is correctly mounted.
- The ami I am using is just a basic amazon linux ami on which I installed a software and save it as another ami. I was using this ami with cfncluster but this is not a proper cfncluster ami

What is the pcluster cli ?
Thank you again
Bye

**Comment by demartinofra** [comment]
Hi @carlitador,

please take a look at this doc page that explains how to create a custom ami to be used with parallelcluster: https://aws-parallelcluster.readthedocs.io/en/latest/tutorials/02_ami_customization.html.

pcluster is simply the new cli that gets installed with aws-parallelcluster and that replaced cfncluster. It also simplifies the creation of custom AMIs as explained in the linked page.

Let us know if some of your questions remain unanswered.

Cheers,
Francesco

**Comment by sean-smith** [comment]
Hi @carlitador 

Any update on this?
