### ISSUE TITLE
compute nodes fail initialization intermittently due to failing setup-ephemeral-drives.sh

### ISSUE THREAD

**Issue by keien** [aws/aws-parallelcluster#859]
**Environment:**
 - AWS ParallelCluster / CfnCluster version: 2.1.1
 - OS: Centos 7.6
 - Scheduler: SGE
 - Master instance type: t2.medium
 - Compute instance type: z1d.6/12xlarge

**Bug description and how to reproduce:**
`z1d.6xlarge` instances sometimes (about 20-30% of the time) fail to initialize and add themselves to SGE due to `setup-ephemeral-drives.sh` failing, as well as `cfn-signal` then subsequently failing to remove the node from the ASG, resulting in orphaned nodes sitting around wasting cost and preventing the ASG from scaling up for more jobs.

**Additional context:**

failure in `/var/log/cfn-init.log`:
```
Running handlers:
[2019-02-14T10:08:47-08:00] ERROR: Running exception handlers
[2019-02-14T10:08:47-08:00] ERROR: Running exception handlers
Running handlers complete
[2019-02-14T10:08:47-08:00] ERROR: Exception handlers complete
[2019-02-14T10:08:47-08:00] ERROR: Exception handlers complete
Chef Client failed. 24 resources updated in 26 seconds
[2019-02-14T10:08:47-08:00] FATAL: Stacktrace dumped to /etc/chef/local-mode-cache/cache/chef-stacktrace.out
[2019-02-14T10:08:47-08:00] FATAL: Stacktrace dumped to /etc/chef/local-mode-cache/cache/chef-stacktrace.out
[2019-02-14T10:08:47-08:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2019-02-14T10:08:47-08:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2019-02-14T10:08:47-08:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: execute[setup ephemeral] (aws-parallelcluster::base_config line 25) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /usr/local/sbin/setup-ephemeral-drives.sh ----
STDOUT: parallelcluster: setup-ephemeral-drives.sh - Failed to detect and/or partition ephemeral devices.
STDERR: + . /etc/parallelcluster/cfnconfig
++ stack_name=parallelcluster-z1d-6xlarge-ami-0839501b46bd62d04
++ cfn_preinstall=s3://cb-parallelcluster/pre_install.sh
++ cfn_preinstall_args=NONE
++ cfn_postinstall=s3://cb-parallelcluster/post_install.sh
++ cfn_postinstall_args=NONE
++ cfn_region=us-west-2
++ cfn_scheduler=sge
++ cfn_scheduler_slots=cores
++ cfn_instance_slots=12
++ cfn_encrypted_ephemeral=false
++ cfn_ephemeral_dir=/scratch
++ cfn_shared_dir=/shared
++ cfn_proxy=NONE
++ cfn_node_type=ComputeFleet
++ cfn_cluster_user=centos
++ cfn_sqs_queue=https://sqs.us-west-2.amazonaws.com/171496337684/parallelcluster-z1d-6xlarge-ami-0839501b46bd62d04-SQS-12BRN6WEX9M61
++ cfn_master=ip-172-31-128-101.us-west-2.compute.internal
+ setup_ephemeral_drives
+ RC=0
+ mkdir -p /scratch
+ chmod 1777 /scratch
+ ls /dev/nvme0 /dev/nvme0n1 /dev/nvme0n1p1 /dev/nvme1 /dev/nvme1n1 /dev/nvme2 /dev/nvme2n1 /dev/nvme3 /dev/nvme3n1
+ IS_NVME=1
++ realpath --relative-to=/dev/ -P /dev/disk/by-id/nvme-Amazon_EC2_NVMe_Instance_Storage_AWS14AF2918C6F54B5DA
+ MAPPING=nvme3n1
+ NUM_DEVS=0
+ for m in '$MAPPING'
+ umount /dev/nvme3n1
+ stat -t /dev/nvme3n1
+ check=0
+ '[' 0 -eq 0 ']'
+ DEVS='nvme3n1 '
+ let NUM_DEVS++
+ '[' 1 -gt 0 ']'
+ for d in '$DEVS'
+ d=/dev/nvme3n1
+ dd if=/dev/zero of=/dev/nvme3n1 bs=32k count=1
1+0 records in
1+0 records out
32768 bytes (33 kB) copied, 0.000281882 s, 116 MB/s
+ parted -s /dev/nvme3n1 mklabel gpt
+ parted -s /dev/nvme3n1
+ parted -s -a optimal /dev/nvme3n1 mkpart primary 1MB 100%
Error: Partition(s) 1 on /dev/nvme3n1 have been written, but we have been unable to inform the kernel of the change, probably because it/they are in use.  As a result, the old partition(s) will remain in use.  You should reboot now before making further changes.
+ RC=1
+ partprobe
+ parted -s /dev/nvme3n1 set 1 lvm on
+ '[' 1 -eq 1 ']'
+ PARTITIONS='/dev/nvme3n1p1 '
+ '[' 1 -ne 0 ']'
+ error_exit 'Failed to detect and/or partition ephemeral devices.'
++ basename /usr/local/sbin/setup-ephemeral-drives.sh
+ script=setup-ephemeral-drives.sh
+ echo 'parallelcluster: setup-ephemeral-drives.sh - Failed to detect and/or partition ephemeral devices.'
+ logger -t parallelcluster 'setup-ephemeral-drives.sh - Failed to detect and/or partition ephemeral devices.'
+ exit 1
---- End output of /usr/local/sbin/setup-ephemeral-drives.sh ----
Ran /usr/local/sbin/setup-ephemeral-drives.sh returned 1
[2019-02-14T10:08:47-08:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: execute[setup ephemeral] (aws-parallelcluster::base_config line 25) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /usr/local/sbin/setup-ephemeral-drives.sh ----
STDOUT: parallelcluster: setup-ephemeral-drives.sh - Failed to detect and/or partition ephemeral devices.
STDERR: + . /etc/parallelcluster/cfnconfig
++ stack_name=parallelcluster-z1d-6xlarge-ami-0839501b46bd62d04
++ cfn_preinstall=s3://cb-parallelcluster/pre_install.sh
++ cfn_preinstall_args=NONE
++ cfn_postinstall=s3://cb-parallelcluster/post_install.sh
++ cfn_postinstall_args=NONE
++ cfn_region=us-west-2
++ cfn_scheduler=sge
++ cfn_scheduler_slots=cores
++ cfn_instance_slots=12
++ cfn_encrypted_ephemeral=false
++ cfn_ephemeral_dir=/scratch
++ cfn_shared_dir=/shared
++ cfn_proxy=NONE
++ cfn_node_type=ComputeFleet
++ cfn_cluster_user=centos
++ cfn_sqs_queue=https://sqs.us-west-2.amazonaws.com/171496337684/parallelcluster-z1d-6xlarge-ami-0839501b46bd62d04-SQS-12BRN6WEX9M61
++ cfn_master=ip-172-31-128-101.us-west-2.compute.internal
+ setup_ephemeral_drives
+ RC=0
+ mkdir -p /scratch
+ chmod 1777 /scratch
+ ls /dev/nvme0 /dev/nvme0n1 /dev/nvme0n1p1 /dev/nvme1 /dev/nvme1n1 /dev/nvme2 /dev/nvme2n1 /dev/nvme3 /dev/nvme3n1
+ IS_NVME=1
++ realpath --relative-to=/dev/ -P /dev/disk/by-id/nvme-Amazon_EC2_NVMe_Instance_Storage_AWS14AF2918C6F54B5DA
+ MAPPING=nvme3n1
+ NUM_DEVS=0
+ for m in '$MAPPING'
+ umount /dev/nvme3n1
+ stat -t /dev/nvme3n1
+ check=0
+ '[' 0 -eq 0 ']'
+ DEVS='nvme3n1 '
+ let NUM_DEVS++
+ '[' 1 -gt 0 ']'
+ for d in '$DEVS'
+ d=/dev/nvme3n1
+ dd if=/dev/zero of=/dev/nvme3n1 bs=32k count=1
1+0 records in
1+0 records out
32768 bytes (33 kB) copied, 0.000281882 s, 116 MB/s
+ parted -s /dev/nvme3n1 mklabel gpt
+ parted -s /dev/nvme3n1
+ parted -s -a optimal /dev/nvme3n1 mkpart primary 1MB 100%
Error: Partition(s) 1 on /dev/nvme3n1 have been written, but we have been unable to inform the kernel of the change, probably because it/they are in use.  As a result, the old partition(s) will remain in use.  You should reboot now before making further changes.
+ RC=1
+ partprobe
+ parted -s /dev/nvme3n1 set 1 lvm on
+ '[' 1 -eq 1 ']'
+ PARTITIONS='/dev/nvme3n1p1 '
+ '[' 1 -ne 0 ']'
+ error_exit 'Failed to detect and/or partition ephemeral devices.'
++ basename /usr/local/sbin/setup-ephemeral-drives.sh
+ script=setup-ephemeral-drives.sh
+ echo 'parallelcluster: setup-ephemeral-drives.sh - Failed to detect and/or partition ephemeral devices.'
+ logger -t parallelcluster 'setup-ephemeral-drives.sh - Failed to detect and/or partition ephemeral devices.'
+ exit 1
---- End output of /usr/local/sbin/setup-ephemeral-drives.sh ----
Ran /usr/local/sbin/setup-ephemeral-drives.sh returned 1

2019-02-14 10:08:47,667 [ERROR] Error encountered during build of chefConfig: Command chef failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 542, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 260, in build
    changes['commands'] = CommandTool().apply(self._config.commands)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/command_tool.py", line 117, in apply
    raise ToolError(u"Command %s failed" % name)
ToolError: Command chef failed
2019-02-14 10:08:47,669 [ERROR] -----------------------BUILD FAILED!------------------------
2019-02-14 10:08:47,670 [ERROR] Unhandled exception during build: Command chef failed
Traceback (most recent call last):
  File "/bin/cfn-init", line 171, in <module>
    worklog.build(metadata, configSets)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 129, in build
    Contractor(metadata).build(configSets, self)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 530, in build
    self.run_config(config, worklog)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 542, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 260, in build
    changes['commands'] = CommandTool().apply(self._config.commands)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/command_tool.py", line 117, in apply
    raise ToolError(u"Command %s failed" % name)
ToolError: Command chef failed
2019-02-14 10:08:47,893 [DEBUG] CloudFormation client initialized with endpoint https://cloudformation.us-west-2.amazonaws.com
2019-02-14 10:08:47,894 [DEBUG] Signaling resource ComputeFleet in stack parallelcluster-z1d-6xlarge-ami-0839501b46bd62d04 with unique ID i-0c6d410af4346e612 and status FAILURE
```
subsequently, in `/var/log/messages`:
```
Feb 14 10:08:47 ip-172-31-128-14 cloud-init: + cfn-signal --exit-code=1 '--reason=Failed to run cfn-init. If --norollback was specified, check
                                                               /var/log/cfn-init.log and /var/log/cloud-init-output.log.' --stack=parallelcluster-z1d-6xlarge-amregion=us-west-2d04 --resourc
Feb 14 10:08:48 ip-172-31-128-14 cloud-init: ValidationError: Stack arn:aws:cloudformation:us-west-2:171496337684:stack/parallelcluster-z1d-6xl
                                                               arge-ami-0839501b46bd62d04/f7fbf950-2b29-11e9-a271-0a33685a019e is in CREATE_COMPLETE state and cannot be signaled
Feb 14 10:08:48 ip-172-31-128-14 cloud-init: + exit 1
Feb 14 10:08:48 ip-172-31-128-14 cloud-init: 2019-02-14 18:08:48,023 - util.py[WARNING]: Failed running /var/lib/cloud/instance/scripts/part-00
                                                               2 [1]
Feb 14 10:08:48 ip-172-31-128-14 cloud-init: /usr/bin/yum
Feb 14 10:08:48 ip-172-31-128-14 cloud-init: which: no apt-get in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin)
Feb 14 10:08:48 ip-172-31-128-14 cloud-init: 2019-02-14 18:08:48,036 - util.py[WARNING]: Failed running /var/lib/cloud/instance/scripts/runcmd
                                                               [1]
Feb 14 10:08:48 ip-172-31-128-14 cloud-init: 2019-02-14 18:08:48,036 - cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts
                                                               in /var/lib/cloud/instance/scripts)
Feb 14 10:08:48 ip-172-31-128-14 cloud-init: 2019-02-14 18:08:48,042 - util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config
                                                               .cc_scripts_user' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_user.pyc'>) failed
```

notably, we can manually rerun `setup-ephemeral-drives.sh` after removing the `RC -ne 0` checks and it successfully creates the `/scratch` partition, so there doesn't seem to be an issue with the partition itself

we suspect that this is a race-condition with something else running `/usr/local/sbin/parallelcluster-ebsnvme-id` (which we see in `/var/log/secure` around the same time) that causes the `parted` issues

the secondary issue is the fact that `cfn-signal` fails, which seems like a bug; this is really the part that causes problems, as it leaves the nodes around eating our money and also prevents the ASG from scaling up, meaning jobs are left sitting in queue for no reason.

this seems related to #252, though that issue doesn't have much detail and the forum post that was referenced is unrelated to our issue

**Comment by lukeseawalker** [comment]
We are marking this as an issue. Could you please send the configuration?

**Comment by keien** [comment]
```
[global]
update_check = true
sanity_check = true
cluster_template = z1d-6xlarge-ami-0839501b46bd62d0

[cluster z1d-6xlarge-ami-0839501b46bd62d0]
custom_ami = ami-0839501b46bd62d0
compute_instance_type = z1d.6xlarge
cluster_type = ondemand
spot_price = 0.00
master_instance_type = t2.medium
master_root_volume_size = 100
compute_root_volume_size = 100
initial_queue_size = 0
max_queue_size = 25
maintain_initial_size = false
base_os=centos7
key_name = ec2-admin
pre_install = s3://XXXXXX/pre_install.sh
post_install = s3://XXXXXX/post_install.sh
extra_json = { "cluster" : { "cfn_scheduler_slots" : "cores" } }
vpc_settings = default
scaling_settings = default
# below is inserted from config/vpc-default
[vpc default]
vpc_id = XXXXXX
master_subnet_id = XXXXXX
vpc_security_group_id = XXXXXX
use_public_ips = false
# below is inserted from config/scaling-profiles
[scaling default]
# Threshold for triggering CloudWatch ScaleUp action
# (defaults to 1 for default template)
scaling_threshold = 1
# Number of instances to add when called CloudWatch ScaleUp action
# (defaults to 1 for default template)
scaling_adjustment = 1
# Threshold for triggering CloudWatch ScaleUp2 action
# (defaults to 200 for default template)
#scaling_threshold2 = 200
# Number of instances to add when called CloudWatch ScaleUp2 action
# (defaults to 20 for default template)
#scaling_adjustment2 = 20
# Period to measure ScalingThreshold
# (defaults to 60 for default template)
scaling_period = 30
# Period to measure ScalingThreshold
# (defaults to 2 for default template)
scaling_evaluation_periods = 2
# Amount of time in seconds to wait before attempting further scaling actions
# (defaults to 300 for the default template
scaling_cooldown = 300

# scaling config for aggressive one-job-one-instance burst usage
[scaling one-to-one]
scaling_threshold = 1
scaling_adjustment = 1
scaling_threshold2 = 20
scaling_adjustment2 = 10
```

**Comment by demartinofra** [comment]
With the most recent versions of ParallelCluster we have improved the handling of this sporadic failures and added some logic to automatically replace a node that is failing to be bootstrapped.

Resolving this but feel free to reopen if the issue still appears.

**Comment by WajdiH** [comment]
Hi
I am facing the same issue:
- aws-parallelcluster==2.10.3
- base_os = centos8
- scheduler = slurm
- master_instance_type = c6g.2xlarge
- instance_type = c6gd.metal

**Log:**
```
mount: /scratch: wrong fs type, bad option, bad superblock on /dev/mapper/ephemeral_luks, missing codepage or helper program, or other error.
Ran /usr/local/sbin/setup-ephemeral-drives.sh returned 1
Reporting instance as unhealthy and dumping logs to /home/logs/compute/i-09515b166afb5308d.tar.gz

```
**configuration file:**
```
[global]
update_check = true
sanity_check = true
cluster_template = slurm
[aws]
aws_region_name = ap-south-1

[scaling customsc]
scaledown_idletime = 30  

[cluster slurm]
key_name = key
base_os = centos8
custom_ami= xxxx
scheduler = slurm
master_instance_type = c6g.2xlarge
vpc_settings = default
scaling_settings = customsc 
queue_settings = spot ,ondemand
ebs_settings = customebs
compute_root_volume_size = 150
master_root_volume_size = 150
encrypted_ephemeral = true
s3_read_resource =  arn:aws:s3:::xxxx/*
post_install = s3://xxxxx/postinstallsetup.sh


ephemeral_dir = /scratch

[queue spot]
compute_resource_settings = spot_crs
compute_type = spot 

[compute_resource spot_crs]
instance_type = c6gd.metal
min_count = 0 
max_count = 20 

[queue ondemand]
compute_resource_settings = ondemand_crs

[compute_resource ondemand_crs]
instance_type = c6gd.metal
min_count = 0 
max_count = 20

```
Could you please help. I will have to work with awsparallelcluster 2.10.3 for a while before migrating to the latest version as we are still working on the custom ami.
